<script>
        function showNext(obj)
        {
                var nextTr=$(obj).parent("tr").next("tr");
                if($(nextTr).is(":hidden")){
                        $(nextTr).show();
                }else{
                        $(nextTr).hide();
                }
        }
</script>
<table width="100%">
        <tr>
                <th colspan="4"  onclick="showNext(this);" style="font-color:blue;">妇科考核评分标准</th>
    </tr>
    <tr hidden>
        <td colspan="4">
                <div id="msg"><p style="text-indent:24px;line-height:150%"><span
                    style=";font-size:16px">1．检查住院病历及报告病历评分标准(总分&nbsp;100&nbsp;分)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)主诉：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要症状及发病时间有错误……3(“……”为应扣分数，下类同)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②主要症状及发病时间有遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(2)现病史：20&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①起病情况及发病经过叙述不清条理性差或有遗漏……&nbsp;2～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②主要症状特点不清……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③伴随症状不清……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④有关鉴别的症状或重要的阴性症状不清……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑤治疗经过叙述不全面……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑥一般症状未叙述……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(3)月经史：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①项目有明显错误……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②部分项目有遗漏……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(4)其他病史：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①项目有遗漏者每项……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②有关阳性病史未提及……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(5)体检：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①项目有遗漏……1</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②重要阳性体征遗漏……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③结果不符……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(6)妇检：10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①检查项目有遗漏……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②重要阳性或阴性体征有遗漏……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③结果不符……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④顺序有错误……1</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(7)辅助检查：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①与诊断有关的化验检查有遗漏，每项……1</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②有关特殊检查如胎心、监护、B&nbsp;超有遗漏．每项……1</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(8)诊断：10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要诊断错误或有重要遗漏……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②次要诊断错误或有遗漏……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③顺序错误……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(9)诊断分析：10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要及次要诊断不全面……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②未作必要的鉴别诊断者……2～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(10)治疗计划：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①有错误……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②不全面……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(11)病程记录：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①治疗经过有遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②病情变化有遗漏……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(12)文字规范、整齐：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①不符合医学术语……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②字迹潦草不清晰……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③错别字……1</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(13)报告病历准确性：10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①欠完整有部份遗漏……2～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②病史有主要错误.....2～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③主要及次要诊断有遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④治疗措施欠全面……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">2．妇科检查或产科检查评分标准(各&nbsp;100&nbsp;分，抽一项检查)</span>
                </p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">A．妇科检查：100&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)窥器检查：30&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①操作不正确……5～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②操作不熟练……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③检查结果不正确……5～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④检查结果不完整……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(2)双合诊与三合诊检查：70&nbsp;分(其中子宫占&nbsp;60％，附件占&nbsp;40％)</span>
                </p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①子宫大小有错误……20</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②子宫大小不太准确……5～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③子宫位置不正确……5～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④子宫硬度、活动度不准确……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑤双侧输卵管、卵巢……10～25</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">B．产科检查(总分&nbsp;100&nbsp;分)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)检查有错误……10～15&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(2)检查不熟练……5～10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(3)检查顺序不正确……3～5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(4)胎方位：20&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(5)胎心音：15&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(6)骨盆外测量：35&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①方法不正确：……15～20</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②检查结果不准确……5～l0</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③检查不熟练……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">3．门诊处理病人评分标准(总分&nbsp;100&nbsp;分)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)病历：20&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主诉不确切……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②起病情况叙述不清……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③有关鉴别诊断的阳性或阴性症状遗漏……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④治疗经过叙述不清……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑤与本病有关的既往史有遗漏……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(2)体检：5&nbsp;分．</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①与本病有关的体检遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②与本病有关的体检错误……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(3)妇检(或产检)：30&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①妇检(或产检)有错误……10～15</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②妇检(或产检)有部分遗漏……5～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③妇检(或产检)不熟练……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(4)诊断：10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要诊断不正确……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②次要诊断遗漏......3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(5)处理：10&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要的处理有错误……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②处理不够完整……2～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③处理不切合实际……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(6)交代病情：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①未交待病情.......2～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②交待不全面……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(7)书写处方：5&nbsp;分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①字迹不清有错别字或涂改……2～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②不签全名……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(8)回答问题：15&nbsp;分</span></p>
                <p><span style=";font-size:14px">教师提出与本病诊断、鉴别诊断、治疗原则有关的问题&nbsp;5&nbsp;个，每题&nbsp;3&nbsp;分(要&nbsp;求在&nbsp;20-30&nbsp;分钟内完成)。</span>
                </p>
                <p><br></p>
        </td>
    </tr>
</table>