<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8"%>
{
    "resultId": ${resultId},
    "resultType": ${pdfn:toJsonString(resultType)}
	 <c:if test="${resultId eq '200' }">
    ,
    "title":[
        {
            "id":"BETotal",
            "name":"总余额：",
            "value":${pdfn:toJsonString(cost.BETotal)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"BEYear",
            "name":"年份：",
            "value":${pdfn:toJsonString(empty cost.BEYear?year:cost.BEYear)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"CHSName",
            "name":"科室：",
            "value":${pdfn:toJsonString(cost.CHSName)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        }
    ],
    "datas":
            [
                {
                    "id":"BEID",
                    "name":"数据主键：",
                    "value":${pdfn:toJsonString(cost.BEID)},
                    "hidden":true,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BECycleHosFlow",
                    "name":"BECycleHosFlow",
                    "value":${pdfn:toJsonString(cost.BECycleHosFlow)},
                    "hidden":true,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BELastYearJSF",
                    "name":"上年结余建设费：",
                    "value":${pdfn:toJsonString(cost.BELastYearJSF)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BELastYearBT",
                    "name":"上年结余补贴：",
                    "value":${pdfn:toJsonString(cost.BELastYearBT)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BELastYearPX",
                    "name":"上年结余培训：",
                    "value":${pdfn:toJsonString(cost.BELastYearPX)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEYearMoney",
                    "name":"本年度发放：",
                    "value":${pdfn:toJsonString(cost.BEYearMoney)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BELastYearMoney",
                    "name":"总额：",
                    "value":${pdfn:toJsonString(cost.BELastYearMoney)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEOneJSF",
                    "name":"一季度建设费：",
                    "value":${pdfn:toJsonString(cost.BEOneJSF)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEOneBT",
                    "name":"一季度管理人员补贴：",
                    "value":${pdfn:toJsonString(cost.BEOneBT)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEOnePX",
                    "name":"一季度培训：",
                    "value":${pdfn:toJsonString(cost.BEOnePX)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BETwoJSF",
                    "name":"二季度建设费：",
                    "value":${pdfn:toJsonString(cost.BETwoJSF)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BETwoBT",
                    "name":"二季度管理人员补贴：",
                    "value":${pdfn:toJsonString(cost.BETwoBT)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BETwoPX",
                    "name":"二季度培训：",
                    "value":${pdfn:toJsonString(cost.BETwoPX)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEThreeJSF",
                    "name":"三季度建设费：",
                    "value":${pdfn:toJsonString(cost.BEThreeJSF)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEThreeBT",
                    "name":"三季度管理人员补贴：",
                    "value":${pdfn:toJsonString(cost.BEThreeBT)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEThreePX",
                    "name":"三季度培训：",
                    "value":${pdfn:toJsonString(cost.BEThreePX)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEFourJSF",
                    "name":"四季度建设费：",
                    "value":${pdfn:toJsonString(cost.BEFourJSF)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEFourBT",
                    "name":"四季度管理人员补贴：",
                    "value":${pdfn:toJsonString(cost.BEFourBT)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEFourPX",
                    "name":"四季度培训：",
                    "value":${pdfn:toJsonString(cost.BEFourPX)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BENowYearMoney",
                    "name":"使用合计：",
                    "value":${pdfn:toJsonString(cost.BENowYearMoney)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BESYJSF",
                    "name":"各项余额建设费：",
                    "value":${pdfn:toJsonString(cost.BESYJSF )},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BESYBT",
                    "name":"各项余额管理人员补贴：",
                    "value":${pdfn:toJsonString(cost.BESYBT)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BESYPX",
                    "name":"各项余额培训：",
                    "value":${pdfn:toJsonString(cost.BESYPX  )},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BETime",
                    "name":"创建时间：",
                    "value":${pdfn:toJsonString(cost.BETime)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"LastYear",
                    "name":"上一年结余：",
                    "value":${pdfn:toJsonString(cost.LastYear)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEOne",
                    "name":"一季度总计：",
                    "value":${pdfn:toJsonString(cost.BEOne)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BETwo",
                    "name":"二季度总计：",
                    "value":${pdfn:toJsonString(cost.BETwo)},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEThree",
                    "name":"三季度总计：",
                    "value":${pdfn:toJsonString(cost.BEThree )},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"BEFour",
                    "name":"四季度总计：",
                    "value":${pdfn:toJsonString(cost.BEFour )},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                },
                {
                    "id":"SyMoney",
                    "name":"总余额：",
                    "value":${pdfn:toJsonString(cost.SyMoney   )},
                    "hidden":false,
                    "readonly":true,
                    "type":"text"
                }
            ]
	</c:if>
}
