build:
  stage: build
  script:
    - mvn clean package -s settings.xml -Ptest
    - ossutil64 cp /home/gitlab-runner/builds/bbPBAsMT/0/research/jsres-doctor-pdsci/pdsci2/target/pdsci.war oss://njpdkj/upgrade/jsres/master/$(date '+%Y%m%d')/ --update --force
    - ossutil64 cp /home/gitlab-runner/builds/bbPBAsMT/0/research/jsres-doctor-pdsci/pdapp/target/pdapp.war oss://njpdkj/upgrade/jsres/master/$(date '+%Y%m%d')/ --update --force