<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		<c:if test="${sSwitch && !isAudit}">
			"save":"保存", 
			"del":"删除"
		</c:if>
		<c:if test="${tSwitch && !isAudit}">
			"save":"审核"
		</c:if>
	},
	"inputs":[
		{
			"inputId":"case",
			"inputType":"select",
			"label":"病例类型",
			"placeholder":"",
			 "options":[{
				"optionId":"一般病例",
				"optionDesc":"一般病例"
				},
				{
					"optionId":"抢救病例",
					"optionDesc":"抢救病例"
				}
			]
			,
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		},
		{
			"inputId":"diseaseName",
			"inputType":"text",
			"label":"疾病名称",
			"placeholder":"",
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		}
		,
		{
			"inputId":"caseNumber",
			"inputType":"text",
			"label":"病历号",
			"placeholder":"",
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		},
		{
			"inputId":"date",
			"inputType":"date",
			"label":"日期",
			"placeholder":"",
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		}
		,
		{
			"inputId":"teacherSignature",
			"inputType":"text",
			"label":"导师姓名",
			"placeholder":"",
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		}
		,
		{
			"inputId":"summary",
			"inputType":"textarea",
			"label":"心得体会",
			"placeholder":"",
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		}
	]
	,
	"values":[
		{
			"inputId":"case",
			<c:set var="c" value="case"/>
			"value":${pdfn:toJsonString(formDataMap[c])}
		},
		{
			"inputId":"diseaseName",
			"value":${pdfn:toJsonString(formDataMap.diseaseName)}
		}
		,
		{
			"inputId":"caseNumber",
			"value":${pdfn:toJsonString(formDataMap.caseNumber)}
		}
		,
		{
			"inputId":"date",
			"value":${pdfn:toJsonString(formDataMap.date)}
		}
		,
		{
			"inputId":"teacherSignature",
			"value":${pdfn:toJsonString(formDataMap.teacherSignature)}
		}
		,
		{
			"inputId":"summary",
			"value":${pdfn:toJsonString(formDataMap.summary)}
		}
	]
