<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<a href='<s:url value="/res/stdp/test"></s:url>'>标准化住培</a><br>
<a href='<s:url value="/res/njmu/test"></s:url>'>南医大专硕</a><br>
<a href='<s:url value="/res/nydyjs/test"></s:url>'>南医大研究生</a><br>
<a href='<s:url value="/res/nfyy/student/test"></s:url>'>南方医院学生端</a><br>
<a href='<s:url value="/res/nfyy/teacher/test"></s:url>'>南方医院老师端</a><br>
<a href='<s:url value="/res/nfyy/secretarie/test"></s:url>'>南方医院教秘端</a><br>
<a href='<s:url value="/res/gzzyres/student/test"></s:url>'>广州中医学生端</a><br>
<a href='<s:url value="/res/gzzyres/teacher/test"></s:url>'>广州中医老师端</a><br>
<a href='<s:url value="/res/gzzyres/secretarie/test"></s:url>'>广州中医教秘端</a><br>
<a href='<s:url value="/res/hzyy/student/test"></s:url>'>惠州医院学生端</a><br>
<a href='<s:url value="/res/hzyy/teacher/test"></s:url>'>惠州医院老师端</a><br>
<a href='<s:url value="/res/hzyy/kzr/test"></s:url>'>惠州医院科主任端</a><br>
<a href='<s:url value="/res/hzyy/secretarie/test"></s:url>'>惠州医院教秘端</a><br>
<a href='<s:url value="/res/hzyy/tutor/test"></s:url>'>惠州医院导师端</a><br>
<a href='<s:url value="/res/bengyify/student/test"></s:url>'>蚌医附院学生端</a><br>
<a href='<s:url value="/res/bengyify/teacher/test"></s:url>'>蚌医附院老师端</a><br>
<a href='<s:url value="/res/jswjw/test"></s:url>'>江苏卫计委学生端</a><br>
<a href='<s:url value="/res/jswjw/teacher/test"></s:url>'>江苏卫计委老师端</a><br>
<a href='<s:url value="/res/jswjw/kzr/test"></s:url>'>江苏卫计委科主任端</a><br>
<a href='<s:url value="/res/jswjw/admin/test"></s:url>'>江苏卫计委医院管理员端</a><br>
<a href='<s:url value="/res/njmu2/test"></s:url>'>南医大实习生</a><br>
<a href='<s:url value="/res/jszy/test"></s:url>'>江苏中医</a><br>
<a href='<s:url value="/exam/stdp/test"></s:url>'>标准化考试系统</a><br>
<a href='<s:url value="/res/sctcm120/test"></s:url>'>成都中医药大学</a><br>
<a href='<s:url value="/res/hbres/test"></s:url>'>湖北住院医师</a><br>
<a href='<s:url value="/res/ruijin/test"></s:url>'>瑞金云医</a><br>
<a href='<s:url value="/res/gzzl/test"></s:url>'>广州肿瘤医师</a><br>
<a href='<s:url value="/res/osca/test"></s:url>'>临床技能考核考官</a><br>
<a href='<s:url value="/res/osca/admin/test"></s:url>'>临床技能考核管理员</a><br>
<a href='<s:url value="/res/osca/student/test"></s:url>'>临床技能考核学员</a><br>
<a href='<s:url value="/res/xnres/test"></s:url>'>西南住院医师</a><br>
<a href='<s:url value="/res/ezhupei/test"></s:url>'>e住培app</a><br>
<a href='<s:url value="/res/appPushExam/test"></s:url>'>app推送i-医考</a><br>
<a href='<s:url value="/res/lcjn/test"></s:url>'>临床技能管理系统</a><br>
<a href='<s:url value="/res/nfykdx/test"></s:url>'>南方医科大学住院医师</a><br>
<a href='<s:url value="/res/eval/test"></s:url>'>基地评估专家PAD</a><br>
<a href='<s:url value="/res/zsey/test"></s:url>'>中山二院继教科过程管理系统</a><br>
<a href='<s:url value="/res/mbgl/test"></s:url>'>慢病管理</a><br>
<a href='<s:url value="/res/gzdh/test"></s:url>'>广州东华学生端</a><br>
<a href='<s:url value="/res/gzdh/teacher/test"></s:url>'>广州东华老师端</a><br>
<a href='<s:url value="/res/gzdh/kzr/test"></s:url>'>广州东华科主任端</a><br>
<a href='<s:url value="/res/gzdh/admin/test"></s:url>'>广州东华医院管理员端</a><br>
<a href='<s:url value="/res/gzzyyy/test"></s:url>'>广州中医医院</a><br>
<a href='<s:url value="/res/gydxj/test"></s:url>'>广医大研究生学籍系统</a><br>
<a href='<s:url value="/res/qpres/test"></s:url>'>上海青浦</a><br>
<a href='<s:url value="/res/shfx/test"></s:url>'>上海奉贤</a><br>