package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Casediscuss;
import com.pinde.res.model.njmu.mo.CasediscussExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CasediscussMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(CasediscussExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(CasediscussExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer cadisid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Casediscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Casediscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Casediscuss> selectByExample(CasediscussExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	Casediscuss selectByPrimaryKey(Integer cadisid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Casediscuss record,
			@Param("example") CasediscussExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Casediscuss record,
			@Param("example") CasediscussExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(Casediscuss record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.CaseDiscuss
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(Casediscuss record);
}