package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Dicitem;
import com.pinde.res.model.njmu.mo.DicitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DicitemMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(DicitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(DicitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer dicitemid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Dicitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Dicitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Dicitem> selectByExample(DicitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	Dicitem selectByPrimaryKey(Integer dicitemid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Dicitem record,
			@Param("example") DicitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Dicitem record,
			@Param("example") DicitemExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(Dicitem record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(Dicitem record);
}