package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Outsecbrief;
import com.pinde.res.model.njmu.mo.OutsecbriefExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OutsecbriefMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer briefid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Outsecbrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Outsecbrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Outsecbrief> selectByExampleWithBLOBs(OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Outsecbrief> selectByExample(OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	Outsecbrief selectByPrimaryKey(Integer briefid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Outsecbrief record,
			@Param("example") OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") Outsecbrief record,
			@Param("example") OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Outsecbrief record,
			@Param("example") OutsecbriefExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(Outsecbrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(Outsecbrief record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(Outsecbrief record);
}