package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.RecCaseclass;
import com.pinde.res.model.njmu.mo.RecCaseclassExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecCaseclassMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(RecCaseclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(RecCaseclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer recid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(RecCaseclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(RecCaseclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<RecCaseclass> selectByExample(RecCaseclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	RecCaseclass selectByPrimaryKey(Integer recid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") RecCaseclass record,
			@Param("example") RecCaseclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") RecCaseclass record,
			@Param("example") RecCaseclassExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(RecCaseclass record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_CaseClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(RecCaseclass record);
}