package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.RecOperateskill;
import com.pinde.res.model.njmu.mo.RecOperateskillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecOperateskillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer recid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(RecOperateskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(RecOperateskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<RecOperateskill> selectByExampleWithBLOBs(
			RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<RecOperateskill> selectByExample(RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	RecOperateskill selectByPrimaryKey(Integer recid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") RecOperateskill record,
			@Param("example") RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") RecOperateskill record,
			@Param("example") RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") RecOperateskill record,
			@Param("example") RecOperateskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(RecOperateskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(RecOperateskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(RecOperateskill record);
}