package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.RecPosskill;
import com.pinde.res.model.njmu.mo.RecPosskillExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecPosskillMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(RecPosskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(RecPosskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer recid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(RecPosskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(RecPosskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<RecPosskill> selectByExample(RecPosskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	RecPosskill selectByPrimaryKey(Integer recid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") RecPosskill record,
			@Param("example") RecPosskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") RecPosskill record,
			@Param("example") RecPosskillExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(RecPosskill record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_POSSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(RecPosskill record);
}