package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Userrealcyclesec;
import com.pinde.res.model.njmu.mo.UserrealcyclesecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserrealcyclesecMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(UserrealcyclesecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(UserrealcyclesecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Userrealcyclesec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Userrealcyclesec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Userrealcyclesec> selectByExample(UserrealcyclesecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Userrealcyclesec record,
			@Param("example") UserrealcyclesecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Userrealcyclesec record,
			@Param("example") UserrealcyclesecExample example);
}