package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Usersectionmanager;
import com.pinde.res.model.njmu.mo.UsersectionmanagerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UsersectionmanagerMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(UsersectionmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(UsersectionmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Usersectionmanager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Usersectionmanager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Usersectionmanager> selectByExample(UsersectionmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	Usersectionmanager selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Usersectionmanager record,
			@Param("example") UsersectionmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Usersectionmanager record,
			@Param("example") UsersectionmanagerExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(Usersectionmanager record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserSectionManager
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(Usersectionmanager record);
}