package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Userinfo;
import com.pinde.res.model.njmu.mo.UserinfoExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserinfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Userinfo> selectByExample(UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	Userinfo selectByPrimaryKey(Integer userid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Userinfo record,
			@Param("example") UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Userinfo record,
			@Param("example") UserinfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKeySelective(Userinfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserInfo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByPrimaryKey(Userinfo record);
}