package com.pinde.res.dao.njmu.base;

import com.pinde.res.model.njmu.mo.Userrealtec;
import com.pinde.res.model.njmu.mo.UserrealtecExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserrealtecMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int countByExample(UserrealtecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int deleteByExample(UserrealtecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insert(Userrealtec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int insertSelective(Userrealtec record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	List<Userrealtec> selectByExample(UserrealtecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Userrealtec record,
			@Param("example") UserrealtecExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	int updateByExample(@Param("record") Userrealtec record,
			@Param("example") UserrealtecExample example);
}