<script>
        function showNext(obj)
        {
                var nextTr=$(obj).parent("tr").next("tr");
                if($(nextTr).is(":hidden")){
                        $(nextTr).show();
                }else{
                        $(nextTr).hide();
                }
        }
</script>
<table width="100%">
    <tr>
        <th colspan="4"  onclick="showNext(this);" style="font-color:blue;">儿科临床技能相关评分标准</th>
    </tr>
    <tr hidden>
        <td colspan="4">
                <p style=";margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                    style=";font-size:14px">1．病历评分标准(总分100分)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)主诉：5分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要症状及发病时间有错误……3(“……”为应扣分数，下类同)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②主要症状及发病时间有遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(2)现病史：25</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①起病情况叙述不清、时间表达不准确……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②发</span><span
                        style=";font-size:14px">病经过顺序不清</span><span
                        style=";font-size:14px">、条理性差或遗漏……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③主要症状描述不清……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④伴随症状不清……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑤有关鉴别的症状和重要阴性症状不清……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑥治疗经过叙述不全面……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑦发病后一般情况不清……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(3)个人史：5</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①项目有遗漏者……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②有关病史不清……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(4)其他病史：5</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①项目有遗漏者……1～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②有关的阳性或阴性病史未提及……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(5)体检：15</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①项目有遗漏……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②重要阳性或阴性体症有遗漏……1～4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③结果不符…1&mdash;4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④顺序错误……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(6)辅助检查：5</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">包括三大常规及有关诊断的重要化验(X</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">线、超声、心电图、血生化……)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(7)诊断：10</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要诊断错误或有重要遗漏……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②次要诊断错误或遗漏……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③顺序错误……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(8)诊断分析：15</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要及次要诊断分析不全面……2～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②未作必要的鉴别诊断者……2～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③仅罗列书本内容、化验结果，缺少对本病实际情况的分析……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(9)治疗计划：10</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①有错误……3～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②有遗漏……2～5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(10)文字书写：5</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①不符合医学术语……l～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②字迹潦草……1～2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③有涂改、错别字……1</span></p>
                <p style=";margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">2．体格检查（总分100分）</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)速度：10</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分。要求</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">40</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分钟内完成全面系统检查，过时扣分如下：</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①超过</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">5</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分钟……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑦超过</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">10</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分钟……10</span></p>
                <p style="margin-top:3px;margin-right:201px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%">
                    <span style=";font-size:14px">(2)方法：40</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分，检查方法不正确扣分如下：</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">皮肤、淋巴……1</span> <span
                        style=";font-size:14px">心脏</span> <span
                        style=";font-size:14px">视诊……1</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">头</span><span
                        style=";font-size:14px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span
                        style=";font-size:14px">颅……3</span> <span
                        style=";font-size:14px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span
                        style=";font-size:14px">触诊…1</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">眼、耳、鼻……3</span> <span
                        style=";font-size:14px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span
                        style=";font-size:14px">叩诊…3</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">口腔、咽部……3</span> <span
                        style=";font-size:14px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span
                        style=";font-size:14px">听诊…3</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">颈</span><span
                        style=";font-size:14px">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span><span
                        style=";font-size:14px">部……2</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">肺</span><span
                        style=";font-size:14px">&nbsp;&nbsp;&nbsp;&nbsp;</span><span
                        style=";font-size:14px">视诊……1</span> <span
                        style=";font-size:14px">腹部</span> <span
                        style=";font-size:14px">视诊…l</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">触诊……1</span> &nbsp;<span
                        style=";font-size:14px">触诊…2</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">叩诊……2</span> &nbsp;<span
                        style=";font-size:14px">叩诊…1</span><span
                        style=";font-size:14px">&nbsp;</span></p>
                <p style="text-indent:28px;text-autospace:none;line-height:150%"><span
                        style=";font-size:14px">听诊……3</span> &nbsp;<span
                        style=";font-size:14px">听诊…l</span></p>
                <p style=";margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">肛门及外生殖器……1</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">脊柱及四肢……2</span></p>
                <p style=";margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">神经系统…3(包括：腹壁反射、膝腱反射、脑膜刺激，病理神经反射)顺序错误…2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(3)准确性：50分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①与主要诊断有关的阳性体征遗漏……25</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②与次要诊断有关的阳性体征遗漏……10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③实际阴性体征查出阳性结果……15</span></p>
                <p style=";margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">3．门诊处理病人(总分100分)</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(1)病历：20分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主诉不确切……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②起病情况叙述不清……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③有关鉴别诊断阳性症状及阴性症状遗漏……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④治疗经过叙述不清……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑤与本病有关的其他病史和接触史未提及……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(2)查体：15分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①重要阳性体征遗漏……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②有关阴性体征遗漏……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③结果不符合……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④患儿一般状态未提及……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(3)诊断：20分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①主要诊断错误……5～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②主要诊断有遗漏……5</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③次要诊断有错误……2～3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④次要诊断有遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(4)处理：20分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①治疗原则错误……8～10</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②主要药物用错……3</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③主要药物剂量错误……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">④药名写错……1</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">⑤处理不全面……4</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(5)交代病情：6</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①交代诊断不清……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②交代注意事项不清……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">③传染病的隔离、检疫有遗漏……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(6)处方书写：4</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">①字迹不清有错别字或涂改……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">②不签全名……2</span></p>
                <p style="margin-top:3px;margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">(7)回答问题：15分</span></p>
                <p style=";margin-left:37px;text-autospace:none;text-align:left;line-height:150%"><span
                        style=";font-size:14px">4．门诊药物考核</span></p>
                <p><span style=";font-size:14px">请写出</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">15</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">个小儿常用药物剂量(要求</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">20</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分钟内完成)每个</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">1</span><span
                        style=";font-size:14px">&nbsp;</span><span
                        style=";font-size:14px">分。</span></p>
                <p><br></p>
        </td>
    </tr>
</table>