
package com.transfer.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InfoTransfer", targetNamespace = "http://transfer.pd.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InfoTransfer {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getResrecData", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.GetResrecData")
    @ResponseWrapper(localName = "getResrecDataResponse", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.GetResrecDataResponse")
    @Action(input = "http://transfer.pd.com/InfoTransfer/getResrecDataRequest", output = "http://transfer.pd.com/InfoTransfer/getResrecDataResponse")
    public String getResrecData(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synEmpInfo", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.SynEmpInfo")
    @ResponseWrapper(localName = "synEmpInfoResponse", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.SynEmpInfoResponse")
    @Action(input = "http://transfer.pd.com/InfoTransfer/synEmpInfoRequest", output = "http://transfer.pd.com/InfoTransfer/synEmpInfoResponse")
    public String synEmpInfo(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "synDeptInfo", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.SynDeptInfo")
    @ResponseWrapper(localName = "synDeptInfoResponse", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.SynDeptInfoResponse")
    @Action(input = "http://transfer.pd.com/InfoTransfer/synDeptInfoRequest", output = "http://transfer.pd.com/InfoTransfer/synDeptInfoResponse")
    public String synDeptInfo(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHRR", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.GetHRR")
    @ResponseWrapper(localName = "getHRRResponse", targetNamespace = "http://transfer.pd.com/", className = "com.transfer.ws.GetHRRResponse")
    @Action(input = "http://transfer.pd.com/InfoTransfer/getHRRRequest", output = "http://transfer.pd.com/InfoTransfer/getHRRResponse")
    public String getHRR(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1);

}
