
package com.transfer.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InfoTransferService", targetNamespace = "http://transfer.pd.com/", wsdlLocation = "http://58.248.185.218:9996/InfoTransfer?wsdl")
public class InfoTransferService
    extends Service
{

    private final static URL INFOTRANSFERSERVICE_WSDL_LOCATION;
    private final static WebServiceException INFOTRANSFERSERVICE_EXCEPTION;
    private final static QName INFOTRANSFERSERVICE_QNAME = new QName("http://transfer.pd.com/", "InfoTransferService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://58.248.185.218:9996/InfoTransfer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INFOTRANSFERSERVICE_WSDL_LOCATION = url;
        INFOTRANSFERSERVICE_EXCEPTION = e;
    }

    public InfoTransferService() {
        super(__getWsdlLocation(), INFOTRANSFERSERVICE_QNAME);
    }

    public InfoTransferService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INFOTRANSFERSERVICE_QNAME, features);
    }

    public InfoTransferService(URL wsdlLocation) {
        super(wsdlLocation, INFOTRANSFERSERVICE_QNAME);
    }

    public InfoTransferService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INFOTRANSFERSERVICE_QNAME, features);
    }

    public InfoTransferService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InfoTransferService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InfoTransfer
     */
    @WebEndpoint(name = "InfoTransferPort")
    public InfoTransfer getInfoTransferPort() {
        return super.getPort(new QName("http://transfer.pd.com/", "InfoTransferPort"), InfoTransfer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InfoTransfer
     */
    @WebEndpoint(name = "InfoTransferPort")
    public InfoTransfer getInfoTransferPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://transfer.pd.com/", "InfoTransferPort"), InfoTransfer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INFOTRANSFERSERVICE_EXCEPTION!= null) {
            throw INFOTRANSFERSERVICE_EXCEPTION;
        }
        return INFOTRANSFERSERVICE_WSDL_LOCATION;
    }

}
