<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
{
    "resultId": ${resultId}, 
    "resultType": ${pdfn:toJsonString(resultType)}
    <c:if test="${resultId eq '200' }">
    	,
		"action":{
			"save":"保存"
		},
		"roleId":${pdfn:toJsonString(roleId)},
		"args":[
			{"inputId": "eduUser.userFlow", "label": "学籍用户flow", "value": ${pdfn:toJsonString(eduUser.userFlow)} ,"readonly":true, "isHidden": true},
			{"inputId": "sysUser.userFlow", "label": "系统用户flow", "value": ${pdfn:toJsonString(sysUser.userFlow)} ,"readonly":true, "isHidden": true},
			{"inputId": "resDoctor.doctorFlow", "label": "医师用户flow", "value": ${pdfn:toJsonString(resDoctor.doctorFlow)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.joinTime", "label": "转入年月日", "value": ${pdfn:toJsonString(extInfoForm.joinTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.ssyjsgain", "label": "是否获得硕士研究生学历", "value": ${pdfn:toJsonString(extInfoForm.ssyjsgain)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterGraduateTime", "label": "硕士研究生毕业年月", "value": ${pdfn:toJsonString(extInfoForm.masterGraduateTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterDiplomaCode", "label": "硕士研究生毕业证编号", "value": ${pdfn:toJsonString(extInfoForm.masterDiplomaCode)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterUnitName", "label": "硕士研究生毕业单位名称", "value": ${pdfn:toJsonString(extInfoForm.masterUnitName)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterGraduateMajor", "label": "硕士研究生毕业专业名称", "value": ${pdfn:toJsonString(extInfoForm.masterGraduateMajor)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.ssxwgain", "label": "是否获得硕士学位", "value": ${pdfn:toJsonString(extInfoForm.ssxwgain)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterStudyForm", "label": "获得硕士学位的学习形式", "value": ${pdfn:toJsonString(extInfoForm.masterStudyForm)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterAwardDegreeTime", "label": "获得硕士学位年月", "value": ${pdfn:toJsonString(extInfoForm.masterAwardDegreeTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterDegreeCertCode", "label": "硕士学位证书编号", "value": ${pdfn:toJsonString(extInfoForm.masterDegreeCertCode)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterAwardDegreeOrg", "label": "获得硕士学位单位名称", "value": ${pdfn:toJsonString(extInfoForm.masterAwardDegreeOrg)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterSubject", "label": "获得硕士学位学科门类", "value": ${pdfn:toJsonString(extInfoForm.masterSubject)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.gotMasterCertSpe", "label": "获得硕士学位专业", "value": ${pdfn:toJsonString(extInfoForm.gotMasterCertSpe)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.awardSubjectCategory", "label": "授予学科门类", "value": ${pdfn:toJsonString(extInfoForm.awardSubjectCategory)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.sendUnit", "label": "具体派遣单位", "value": ${pdfn:toJsonString(extInfoForm.sendUnit)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.reportAddressId", "label": "具体派遣单位id", "value": ${pdfn:toJsonString(extInfoForm.reportAddressId)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.reportAddressName", "label": "具体派遣单位", "value": ${pdfn:toJsonString(extInfoForm.reportAddressName)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.sendNature", "label": "派遣性质", "value": ${pdfn:toJsonString(extInfoForm.sendNature)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.sentMemo", "label": "备注", "value": ${pdfn:toJsonString(extInfoForm.sentMemo)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.sendTime", "label": "派遣时间", "value": ${pdfn:toJsonString(extInfoForm.sendTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.graduationWhereabouts", "label": "毕业去向", "value": ${pdfn:toJsonString(extInfoForm.graduationWhereabouts)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.unitCode", "label": "单位组织机构代码", "value": ${pdfn:toJsonString(extInfoForm.unitCode)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workUnit", "label": "具体就业单位", "value": ${pdfn:toJsonString(extInfoForm.workUnit)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workType", "label": "单位类型", "value": ${pdfn:toJsonString(extInfoForm.workType)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workOfIndustry", "label": "单位所属行业", "value": ${pdfn:toJsonString(extInfoForm.workOfIndustry)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workOfAreaId", "label": "单位所属地区id", "value": ${pdfn:toJsonString(extInfoForm.workOfAreaId)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workOfAreaName", "label": "单位所属地区", "value": ${pdfn:toJsonString(extInfoForm.workOfAreaName)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workLinkMan", "label": "单位联系人", "value": ${pdfn:toJsonString(extInfoForm.workLinkMan)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.occupationType", "label": "职业类型", "value": ${pdfn:toJsonString(extInfoForm.occupationType)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workLinkPhone", "label": "单位联系电话", "value": ${pdfn:toJsonString(extInfoForm.workLinkPhone)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workPay", "label": "薪酬", "value": ${pdfn:toJsonString(extInfoForm.workPay)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.userAim", "label": "使用意图", "value": ${pdfn:toJsonString(extInfoForm.userAim)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.signTime", "label": "签约时间", "value": ${pdfn:toJsonString(extInfoForm.signTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.majorCounterpart", "label": "是否专业对口", "value": ${pdfn:toJsonString(extInfoForm.majorCounterpart)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.workEmail", "label": "用人单位邮箱", "value": ${pdfn:toJsonString(extInfoForm.workEmail)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.employmentLevel", "label": "是否就业困难", "value": ${pdfn:toJsonString(extInfoForm.employmentLevel)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.employAgreementUrl", "label": "就业协议书上传", "value": ${pdfn:toJsonString(extInfoForm.employAgreementUrl)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.employSign", "label": "暂缓就业表登记", "value": ${pdfn:toJsonString(extInfoForm.employSign)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.recipients", "label": "收件联系人", "value": ${pdfn:toJsonString(extInfoForm.recipients)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.recipientsPhone", "label": "收件人电话", "value": ${pdfn:toJsonString(extInfoForm.recipientsPhone)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.archivesPlaceCode", "label": "档案去向邮政编码", "value": ${pdfn:toJsonString(extInfoForm.archivesPlaceCode)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.archivesEmsNum", "label": "Ems单号", "value": ${pdfn:toJsonString(extInfoForm.archivesEmsNum)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.archivesEmsAddressId", "label": "档案去向邮寄地址id", "value": ${pdfn:toJsonString(extInfoForm.archivesEmsAddressId)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.archivesEmsAddressName", "label": "档案去向邮寄地址", "value": ${pdfn:toJsonString(extInfoForm.archivesEmsAddressName)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.mailTime", "label": "寄出时间", "value": ${pdfn:toJsonString(extInfoForm.mailTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.archivesUnit", "label": "档案去向单位", "value": ${pdfn:toJsonString(extInfoForm.archivesUnit)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.studentPhone", "label": "学生电话", "value": ${pdfn:toJsonString(extInfoForm.studentPhone)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.studentCode", "label": "学生学号", "value": ${pdfn:toJsonString(extInfoForm.studentCode)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.studentName", "label": "学生姓名", "value": ${pdfn:toJsonString(extInfoForm.studentName)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.joinMedicalYear", "label": "本次参保起始年份", "value": ${pdfn:toJsonString(extInfoForm.joinMedicalYear)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.enterSchoolYear", "label": "入学年份", "value": ${pdfn:toJsonString(extInfoForm.enterSchoolYear)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.isNewStudent", "label": "是否新生", "value": ${pdfn:toJsonString(extInfoForm.isNewStudent)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.college", "label": "学院", "value": ${pdfn:toJsonString(extInfoForm.college)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.countryAreaId", "label": "国家地区id", "value": ${pdfn:toJsonString(extInfoForm.countryAreaId)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.countryAreaName", "label": "国家地区", "value": ${pdfn:toJsonString(extInfoForm.countryAreaName)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.whetherPracticeCert", "label": "有无执业医师资格证", "value": ${pdfn:toJsonString(extInfoForm.whetherPracticeCert)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.practiceCertCode", "label": "执业医师资格证编号", "value": ${pdfn:toJsonString(extInfoForm.practiceCertCode)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.practiceCertUrl", "label": "执业医师资格证上传", "value": ${pdfn:toJsonString(extInfoForm.practiceCertUrl)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.whetherBuyMedicalCard", "label": "是否购买医保", "value": ${pdfn:toJsonString(extInfoForm.whetherBuyMedicalCard)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.unitOfDoctor", "label": "导师所在单位", "value": ${pdfn:toJsonString(extInfoForm.unitOfDoctor)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.dormitoryNo", "label": "宿舍楼号", "value": ${pdfn:toJsonString(extInfoForm.dormitoryNo)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.dormitoryFloor", "label": "宿舍楼层", "value": ${pdfn:toJsonString(extInfoForm.dormitoryFloor)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.dormitoryRoomNumber", "label": "宿舍房号", "value": ${pdfn:toJsonString(extInfoForm.dormitoryRoomNumber)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.partyMembershipTime", "label": "（党员）入党时间", "value": ${pdfn:toJsonString(extInfoForm.partyMembershipTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.partyMemberFormalTime", "label": "（党员）转正时间", "value": ${pdfn:toJsonString(extInfoForm.partyMemberFormalTime)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.emsUrl", "label": "EMS截图上传", "value": ${pdfn:toJsonString(extInfoForm.emsUrl)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.highSchool", "label": "高中", "value": ${pdfn:toJsonString(extInfoForm.highSchool)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.university", "label": "大学", "value": ${pdfn:toJsonString(extInfoForm.university)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterAdmissionSign", "label": "录取登记表", "value": ${pdfn:toJsonString(extInfoForm.masterAdmissionSign)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterScienceDegree", "label": "科学学位（审批表）", "value": ${pdfn:toJsonString(extInfoForm.masterScienceDegree)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterGraduationSign", "label": "毕业登记表", "value": ${pdfn:toJsonString(extInfoForm.masterGraduationSign)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterClinicalDegree", "label": "临床学位（答辩表）", "value": ${pdfn:toJsonString(extInfoForm.masterClinicalDegree)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.masterSchoolReport", "label": "成绩单", "value": ${pdfn:toJsonString(extInfoForm.masterSchoolReport)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.doctorAdmissionSign", "label": "录取登记表", "value": ${pdfn:toJsonString(extInfoForm.doctorAdmissionSign)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.doctorScienceDegree", "label": "科学学位（审批表）", "value": ${pdfn:toJsonString(extInfoForm.doctorScienceDegree)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.doctorGraduationSign", "label": "毕业登记表", "value": ${pdfn:toJsonString(extInfoForm.doctorGraduationSign)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.doctorClinicalDegree", "label": "临床学位（答辩表）", "value": ${pdfn:toJsonString(extInfoForm.doctorClinicalDegree)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.doctorSchoolReport", "label": "成绩单", "value": ${pdfn:toJsonString(extInfoForm.doctorSchoolReport)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUserExtInfoForm.expertChitLetter", "label": "专家推荐信2封", "value": ${pdfn:toJsonString(extInfoForm.expertChitLetter)} ,"readonly":true, "isHidden": true}

		],
		"baseInfoInputList": [
			{"inputId": "eduUser.sid", "label": "学号", "value": ${pdfn:toJsonString(eduUser.sid)} ,"readonly":true},
			{"inputId": "sysUser.userName", "label": "姓名", "value": ${pdfn:toJsonString(sysUser.userName)} ,"readonly":true},
			{"inputId": "eduUser.nameSpell", "label": "姓名拼音", "value": ${pdfn:toJsonString(eduUser.nameSpell)} ,"readonly":true},
			{"inputId": "sysUser.userBirthday", "label": "出生日期", "value": ${pdfn:toJsonString(sysUser.userBirthday)} ,"readonly":true, "inputType":"date"},
			{"inputId": "sysUser.cretTypeId", "label": "证件类型", "value": ${pdfn:toJsonString(sysUser.cretTypeId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${certificateTypeEnumList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.id)},"optionDesc": ${pdfn:toJsonString(data.name)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "sysUser.idNo", "label": "证件号码", "value": ${pdfn:toJsonString(sysUser.idNo)} ,"readonly":true},
			{"inputId": "sysUser.nationId", "label": "民族", "value": ${pdfn:toJsonString(sysUser.nationId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${userNationEnumList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.id)},"optionDesc": ${pdfn:toJsonString(data.name)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.period", "label": "入学年级", "value": ${pdfn:toJsonString(eduUser.period)} ,"readonly":true},
			{"inputId": "eduUser.className", "label": "班级", "value": ${pdfn:toJsonString(eduUser.className)} ,"readonly":true},
			{"inputId": "eduUser.majorId", "label": "专业名称", "value": ${pdfn:toJsonString(eduUser.majorId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyMajorList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.trainTypeId", "label": "培养层次", "value": ${pdfn:toJsonString(eduUser.trainTypeId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyTrainTypeList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.is5plus3", "label": "是否5+3培养模式", "value": ${pdfn:toJsonString(eduUser.is5plus3)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "resDoctor.orgFlow", "label": "培养单位flow", "value": ${pdfn:toJsonString(resDoctor.orgFlow)} ,"readonly":true, "isHidden": true},
			{"inputId": "resDoctor.orgName", "label": "培养单位", "value": ${pdfn:toJsonString(resDoctor.orgName)} ,"readonly":true},
			{"inputId": "eduUser.trainCategoryId", "label": "培养类型", "value": ${pdfn:toJsonString(eduUser.trainCategoryId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyTrainCategoryList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.barCode", "label": "条形码号", "value": ${pdfn:toJsonString(eduUser.barCode)} ,"readonly":true},
			{"inputId": "eduUser.researchDirName", "label": "研究方向", "value": ${pdfn:toJsonString(eduUser.researchDirName)} ,"readonly":true},
			{"inputId": "eduUser.firstTeacherFlow", "label": "导师一flow", "value": ${pdfn:toJsonString(eduUser.firstTeacherFlow)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUser.firstTeacher", "label": "导师一", "value": ${pdfn:toJsonString(eduUser.firstTeacher)} ,"readonly":true},
			{"inputId": "eduUser.secondTeacherFlow", "label": "导师二flow", "value": ${pdfn:toJsonString(eduUser.secondTeacherFlow)} ,"readonly":true, "isHidden": true},
			{"inputId": "eduUser.secondTeacher", "label": "导师二", "value": ${pdfn:toJsonString(eduUser.secondTeacher)} ,"readonly":true},
			{"inputId": "eduUser.schoolRollStatusId", "label": "学籍状态", "value": ${pdfn:toJsonString(eduUser.schoolRollStatusId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGySchoolRollStatusList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.xjRegDate", "label": "学籍注册时间", "value": ${pdfn:toJsonString(extInfoForm.xjRegDate)} ,"readonly":true, "inputType":"date"},
			{"inputId": "eduUser.isReported", "label": "是否报到", "value": ${pdfn:toJsonString(eduUser.isReported)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.reportedDate", "label": "报到时间", "value": ${pdfn:toJsonString(extInfoForm.reportedDate)} ,"readonly":true, "inputType":"date"},
			{"inputId": "eduUser.atSchoolStatusId", "label": "在校状态", "value": ${pdfn:toJsonString(eduUser.atSchoolStatusId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyAtSchoolStatusList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.studyFormId", "label": "学习形式", "value": ${pdfn:toJsonString(eduUser.studyFormId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyStudyFormList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.isOutOfSchool", "label": "是否休学", "value": ${pdfn:toJsonString(eduUser.isOutOfSchool)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.outOfSchoolDate", "label": "休学日期", "value": ${pdfn:toJsonString(extInfoForm.outOfSchoolDate)} ,"readonly":true},
			{"inputId": "eduUser.isBackToSchool", "label": "是否复学", "value": ${pdfn:toJsonString(eduUser.isBackToSchool)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.backToSchoolDate", "label": "复学日期", "value": ${pdfn:toJsonString(extInfoForm.backToSchoolDate)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.dropOutSchoolDate", "label": "退学时间", "value": ${pdfn:toJsonString(extInfoForm.dropOutSchoolDate)} ,"readonly":true, "inputType":"date"}
		],
		"recruitInfoInputList": [
			{"inputId": "eduUser.studentCode", "label": "考生编号", "value": ${pdfn:toJsonString(eduUser.studentCode)} ,"readonly":true},
			{"inputId": "eduUser.studentSourceId", "label": "考生来源", "value": ${pdfn:toJsonString(eduUser.majorId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyStudentSourceList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.admitTypeId", "label": "录取类别", "value": ${pdfn:toJsonString(eduUser.admitTypeId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyAdmitTypeList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.recruitSeasonId", "label": "招生季节", "value": ${pdfn:toJsonString(eduUser.recruitSeasonId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyRecruitSeasonList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.recruitType", "label": "招录方式", "value": ${pdfn:toJsonString(extInfoForm.recruitType)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyRecruitTypeList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUser.isExceptionalId", "label": "是否破格", "value": ${pdfn:toJsonString(eduUser.isExceptionalId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyIsExceptionalList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.foreignLanguageName", "label": "外国语名称", "value": ${pdfn:toJsonString(extInfoForm.foreignLanguageName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.foreignLanguageScore", "label": "外国语成绩", "value": ${pdfn:toJsonString(extInfoForm.foreignLanguageScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.politicalTheoryName", "label": "政治理论", "value": ${pdfn:toJsonString(extInfoForm.politicalTheoryName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.politicalTheoryScore", "label": "政治理论成绩", "value": ${pdfn:toJsonString(extInfoForm.politicalTheoryScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.firstSubjectName", "label": "业务课一", "value": ${pdfn:toJsonString(extInfoForm.firstSubjectName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.firstSubjectScore", "label": "业务课一成绩", "value": ${pdfn:toJsonString(extInfoForm.firstSubjectScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.secondSubjectName", "label": "业务课二", "value": ${pdfn:toJsonString(extInfoForm.secondSubjectName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.secondSubjectScore", "label": "业务课二成绩", "value": ${pdfn:toJsonString(extInfoForm.secondSubjectScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.firstAddExamName", "label": "加试科一", "value": ${pdfn:toJsonString(extInfoForm.firstAddExamName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.firstAddExamScore", "label": "加试科一成绩", "value": ${pdfn:toJsonString(extInfoForm.firstAddExamScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.secondAddExamName", "label": "加试科二", "value": ${pdfn:toJsonString(extInfoForm.secondAddExamName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.secondAddExamScore", "label": "加试科二成绩", "value": ${pdfn:toJsonString(extInfoForm.secondAddExamScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.reexamineScore", "label": "复试成绩", "value": ${pdfn:toJsonString(extInfoForm.reexamineScore)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.totalPointsScore", "label": "总分", "value": ${pdfn:toJsonString(extInfoForm.totalPointsScore)} ,"readonly":true}
		],
		"needInfoInputList": [
			{"inputId": "sysUser.userHeadImg", "label": "头像url", "value": ${pdfn:toJsonString(sysUser.userHeadImg)} ,"readonly":true,"isHidden": true},
			{"inputId": "sysUser.nativePlaceProvId", "label": "籍贯-省id", "value": ${pdfn:toJsonString(sysUser.nativePlaceProvId)} ,"readonly":true,"isHidden": true},
			{"inputId": "sysUser.nativePlaceCityId", "label": "籍贯-市id", "value": ${pdfn:toJsonString(sysUser.nativePlaceCityId)} ,"readonly":true,"isHidden": true},
			{"inputId": "sysUser.nativePlaceAreaId", "label": "籍贯-区id", "value": ${pdfn:toJsonString(sysUser.nativePlaceAreaId)} ,"readonly":true,"isHidden": true},
			{"inputId": "sysUser.nativePlaceProvName", "label": "籍贯-省", "value": ${pdfn:toJsonString(sysUser.nativePlaceProvName)} ,"readonly":true},
			{"inputId": "sysUser.nativePlaceCityName", "label": "籍贯-市", "value": ${pdfn:toJsonString(sysUser.nativePlaceCityName)} ,"readonly":true},
			{"inputId": "sysUser.nativePlaceAreaName", "label": "籍贯-区", "value": ${pdfn:toJsonString(sysUser.nativePlaceAreaName)} ,"readonly":true},
			{"inputId": "sysUser.maritalId", "label": "婚姻状况", "value": ${pdfn:toJsonString(sysUser.maritalId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${marriageTypeEnumList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.id)},"optionDesc": ${pdfn:toJsonString(data.name)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "sysUser.bearName", "label": "生育状况", "value": ${pdfn:toJsonString(sysUser.bearName)} ,"readonly":true},
			{"inputId": "sysUser.politicsStatusId", "label": "政治面貌", "value": ${pdfn:toJsonString(sysUser.politicsStatusId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${politicsAppearanceEnumList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.id)},"optionDesc": ${pdfn:toJsonString(data.name)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.joinOrgTime", "label": "入党（团）时间", "value": ${pdfn:toJsonString(extInfoForm.joinOrgTime)} ,"readonly":true, "inputType":"date"},
			{"inputId": "eduUserExtInfoForm.isRelationInto", "label": "党团关系是否转入", "value": ${pdfn:toJsonString(extInfoForm.isRelationInto)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "sysUser.partyBranchId", "label": "所属党支部", "value": ${pdfn:toJsonString(sysUser.partyBranchId)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyXjPartyBranchList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "sysUser.domicilePlaceId", "label": "入学前户口所在地id", "value": ${pdfn:toJsonString(sysUser.domicilePlaceId)} ,"readonly":true,"isHidden": true},
			{"inputId": "sysUser.domicilePlaceName", "label": "入学前户口所在地", "value": ${pdfn:toJsonString(sysUser.domicilePlaceName)} ,"readonly":true},
			{"inputId": "sysUser.domicilePlaceAddress", "label": "入学前户口所在详细地址", "value": ${pdfn:toJsonString(sysUser.domicilePlaceAddress)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.hkInSchool", "label": "户口是否需要迁入我校", "value": ${pdfn:toJsonString(extInfoForm.hkInSchool)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "1","optionDesc":"是"},{"optionId": "2","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.hkChangeNo", "label": "户口迁移证编号", "value": ${pdfn:toJsonString(extInfoForm.hkChangeNo)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.oldOrgName", "label": "原学习或工作单位", "value": ${pdfn:toJsonString(extInfoForm.oldOrgName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.oldFileLocationOrg", "label": "原档案所在单位", "value": ${pdfn:toJsonString(extInfoForm.oldFileLocationOrg)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.oldFileLocationOrgCode", "label": "原档案所在单位邮编", "value": ${pdfn:toJsonString(extInfoForm.oldFileLocationOrgCode)} ,"readonly":true},
			{"inputId": "eduUser.recordLocationId", "label": "档案所在地id", "value": ${pdfn:toJsonString(eduUser.recordLocationId)} ,"readonly":true,"isHidden": true},
			{"inputId": "eduUser.recordLocationName", "label": "档案所在地", "value": ${pdfn:toJsonString(eduUser.recordLocationName)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.nowResideAddress", "label": "现家庭住址", "value": ${pdfn:toJsonString(extInfoForm.nowResideAddress)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.postCode", "label": "邮政编码", "value": ${pdfn:toJsonString(extInfoForm.postCode)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.linkMan", "label": "紧急联系人姓名", "value": ${pdfn:toJsonString(extInfoForm.linkMan)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.telephone", "label": "紧急联系人电话", "value": ${pdfn:toJsonString(extInfoForm.telephone)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.isDoctorQuaCert", "label": "是否有医师资格证", "value": ${pdfn:toJsonString(extInfoForm.isDoctorQuaCert)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.codeDoctorQuaCert", "label": "资格证编号", "value": ${pdfn:toJsonString(extInfoForm.codeDoctorQuaCert)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.isMedicalPractitioner", "label": "是否有执业医师执照", "value": ${pdfn:toJsonString(extInfoForm.isMedicalPractitioner)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.codeMedicalPractitioner", "label": "执照编号", "value": ${pdfn:toJsonString(extInfoForm.codeMedicalPractitioner)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.isStay", "label": "是否住宿", "value": ${pdfn:toJsonString(extInfoForm.isStay)} ,"readonly":true, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.roomNumStay", "label": "宿舍号", "value": ${pdfn:toJsonString(extInfoForm.roomNumStay)} ,"readonly":false},
			{"inputId": "sysUser.userPhone", "label": "本人手机号码", "value": ${pdfn:toJsonString(sysUser.userPhone)} ,"readonly":true},
			{"inputId": "sysUser.userEmail", "label": "电子邮箱", "value": ${pdfn:toJsonString(sysUser.userEmail)} ,"readonly":true},
			{"inputId": "sysUser.weiXinName", "label": "微信号", "value": ${pdfn:toJsonString(sysUser.weiXinName)} ,"readonly":true},
			{"inputId": "sysUser.userQq", "label": "QQ号", "value": ${pdfn:toJsonString(sysUser.userQq)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.height", "label": "身高", "value": ${pdfn:toJsonString(extInfoForm.height)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.bloodType", "label": "血型", "value": ${pdfn:toJsonString(extInfoForm.bloodType)} ,"readonly":true},
			{"inputId": "eduUserExtInfoForm.ybCardNo", "label": "医保卡号", "value": ${pdfn:toJsonString(extInfoForm.ybCardNo)} ,"readonly":true}
		],
		"selectInfoInputList": [
			{"inputId": "eduUserExtInfoForm.mandarinLevel", "label": "普通话水平", "value": ${pdfn:toJsonString(extInfoForm.mandarinLevel)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.foreignLanguageLevel", "label": "外语水平", "value": ${pdfn:toJsonString(extInfoForm.foreignLanguageLevel)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.computerLevel", "label": "计算机水平", "value": ${pdfn:toJsonString(extInfoForm.computerLevel)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.schoolSystem", "label": "学制", "value": ${pdfn:toJsonString(extInfoForm.schoolSystem)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.studentSourceArea", "label": "生源省市", "value": ${pdfn:toJsonString(extInfoForm.studentSourceArea)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.dormitoryAdd", "label": "宿舍地址", "value": ${pdfn:toJsonString(extInfoForm.dormitoryAdd)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.homePhone", "label": "家庭电话", "value": ${pdfn:toJsonString(extInfoForm.homePhone)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.mateName", "label": "配偶姓名", "value": ${pdfn:toJsonString(extInfoForm.mateName)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.mateIdNo", "label": "配偶身份证", "value": ${pdfn:toJsonString(extInfoForm.mateIdNo)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.spouseUnit", "label": "配偶工作单位", "value": ${pdfn:toJsonString(extInfoForm.spouseUnit)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.speciality", "label": "特长", "value": ${pdfn:toJsonString(extInfoForm.speciality)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.mainResume", "label": "本人主要简历", "value": ${pdfn:toJsonString(extInfoForm.mainResume)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.reAndPuStatusContent", "label": "入学前奖惩情况", "value": ${pdfn:toJsonString(extInfoForm.reAndPuStatusContent)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.scientificTogether", "label": "曾担任过合作教学工作和进行何种科研工作", "value": ${pdfn:toJsonString(extInfoForm.scientificTogether)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.remark", "label": "备注", "value": ${pdfn:toJsonString(extInfoForm.remark)} ,"readonly":false}
		],
		"feeInfoInputList": [
			{"inputId": "eduUserExtInfoForm.accountNum", "label": "缴费账号", "value": ${pdfn:toJsonString(extInfoForm.accountNum)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.tuitionFee", "label": "学费总额", "value": ${pdfn:toJsonString(extInfoForm.tuitionFee)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.paytuitionFee", "label": "已缴纳学费", "value": ${pdfn:toJsonString(extInfoForm.paytuitionFee)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.arrearageFee", "label": "欠缴纳学费", "value": ${pdfn:toJsonString(extInfoForm.arrearageFee)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.dormitoryFee", "label": "住宿费", "value": ${pdfn:toJsonString(extInfoForm.dormitoryFee)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.payDormitoryFee", "label": "已缴纳住宿费", "value": ${pdfn:toJsonString(extInfoForm.payDormitoryFee)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.arrearageDormitoryFee", "label": "欠缴纳住宿费", "value": ${pdfn:toJsonString(extInfoForm.arrearageDormitoryFee)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.paidFee", "label": "是否缴清费用", "value": ${pdfn:toJsonString(extInfoForm.paidFee)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "Y","optionDesc":"是"},{"optionId": "N","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.paidFeeNo", "label": "缴费编号", "value": ${pdfn:toJsonString(extInfoForm.paidFeeNo)} ,"readonly":false}
		],
		"gotCertInfoInputList": [
			{"inputId": "eduUserExtInfoForm.firstEducationContentId", "label": "第一学历", "value": ${pdfn:toJsonString(extInfoForm.firstEducationContentId)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyFirstEducationList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.preGraduation", "label": "前置学历", "value": ${pdfn:toJsonString(extInfoForm.preGraduation)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyPreGraduationList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.bkgain", "label": "是否获得本科学历", "value": ${pdfn:toJsonString(extInfoForm.bkgain)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "1","optionDesc":"是"},{"optionId": "2","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.underStudyForm", "label": "获得本科学历的学习形式", "value": ${pdfn:toJsonString(extInfoForm.underStudyForm)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyUnderStudyFormList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.underGraduateTime", "label": "本科毕业年月", "value": ${pdfn:toJsonString(extInfoForm.underGraduateTime)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.underDiplomaCode", "label": "本科毕业证书编号", "value": ${pdfn:toJsonString(extInfoForm.underDiplomaCode)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.underGraduateOrgName", "label": "本科毕业单位名称", "value": ${pdfn:toJsonString(extInfoForm.underGraduateOrgName)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.underGraduateMajor", "label": "本科毕业专业名称", "value": ${pdfn:toJsonString(extInfoForm.underGraduateMajor)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.xsgain", "label": "是否获得学士学位", "value": ${pdfn:toJsonString(extInfoForm.xsgain)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "1","optionDesc":"是"},{"optionId": "2","optionDesc":"否"}]},
			{"inputId": "eduUserExtInfoForm.underAwardDegreeTime", "label": "获得学士学位年月", "value": ${pdfn:toJsonString(extInfoForm.underAwardDegreeTime)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.underDegreeCertCode", "label": "学士学位证书编号", "value": ${pdfn:toJsonString(extInfoForm.underDegreeCertCode)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.underAwardDegreeOrg", "label": "获学士学位单位名称", "value": ${pdfn:toJsonString(extInfoForm.underAwardDegreeOrg)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.underMajor", "label": "获学士学位专业名称", "value": ${pdfn:toJsonString(extInfoForm.underMajor)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.gotBachelorCertSubject", "label": "获得学士学位学科门类", "value": ${pdfn:toJsonString(extInfoForm.gotBachelorCertSubject)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.code", "label": "最后学位证编号", "value": ${pdfn:toJsonString(extInfoForm.code)} ,"readonly":false}
		],
		"certReqInfoInputList": [
			{"inputId": "eduUserExtInfoForm.planGraduateTime", "label": "预毕业时间", "value": ${pdfn:toJsonString(extInfoForm.planGraduateTime)} ,"readonly":false, "inputType":"date"},
			{"inputId": "eduUserExtInfoForm.graduateFlag", "label": "是否毕业", "value": ${pdfn:toJsonString(extInfoForm.graduateFlag)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},{"optionId": "1","optionDesc":"是"},{"optionId": "2","optionDesc":"否"}]}
		],
		"paperInfoInputList": [
			{"inputId": "eduUserExtInfoForm.paperTitle", "label": "论文题目", "value": ${pdfn:toJsonString(extInfoForm.paperTitle)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.paperSource", "label": "论文选题来源", "value": ${pdfn:toJsonString(extInfoForm.paperSource)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyPaperSourceList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]},
			{"inputId": "eduUserExtInfoForm.paperKey", "label": "论文关键词", "value": ${pdfn:toJsonString(extInfoForm.paperKey)} ,"readonly":false},
			{"inputId": "eduUserExtInfoForm.paperType", "label": "论文类型", "value": ${pdfn:toJsonString(extInfoForm.paperType)} ,"readonly":false, "inputType":"select", "options":[{"optionId": "","optionDesc": "请选择"},<c:forEach items="${dictTypeEnumGyPaperTypeList}" var="data" varStatus="s">{"optionId": ${pdfn:toJsonString(data.dictId)},"optionDesc": ${pdfn:toJsonString(data.dictName)}}<c:if test="${not s.last }">,</c:if></c:forEach>]}
		]
    </c:if>
}