CREATE TABLE "PDSCI"."LOCAL_APP_USERINFO" 
   (	"RECORD_FLOW" VARCHAR2(120) NOT NULL ENABLE, 
	"K_ID" VARCHAR2(30), 
	"PID" VARCHAR2(50), 
	"MONTH_DATE" VARCHAR2(50), 
	"IS_CONTAIN" VARCHAR2(50) DEFAULT 'N', 
	"CREATE_TIME" VARCHAR2(50), 
	"ORG_FLOW" VARCHAR2(50), 
	"K_LEVEL" VARCHAR2(50), 
	"SPE_ID" VARCHAR2(50), 
	"SPE_NAME" VARCHAR2(50), 
	"DOCTOR_RATE_TRAINSUM" VARCHAR2(50), 
	"DOCTOR_RATE_USESUM" VARCHAR2(50), 
	"DOCTOR_RATE_RATE" VARCHAR2(50), 
	"MASTER_RATE_TRAINSUM" VARCHAR2(50), 
	"MASTER_RATE_USESUM" VARCHAR2(50), 
	"MASTER_RATE_RATE" VARCHAR2(50), 
	"AVG_RATE_TRAINSUM" VARCHAR2(50), 
	"AVG_RATE_USESUM" VARCHAR2(50), 
	"AVG_RATE_RATE" VARCHAR2(50), 
	 CHECK ("RECORD_FLOW" IS NOT NULL) ENABLE, 
	 PRIMARY KEY ("RECORD_FLOW")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

CREATE UNIQUE INDEX "PDSCI"."SYS_C0014260" ON "PDSCI"."LOCAL_APP_USERINFO" ("RECORD_FLOW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";