CREATE TABLE "PDSCI"."PCU_DOCTOR_OUTOFFICE" 
   (	"RECORD_FLOW" VARCHAR2(120) NOT NULL ENABLE, 
	"NO" VARCHAR2(30), 
	"PARENT_ORG_FLOW" VARCHAR2(50), 
	"MONTH_DATE" VARCHAR2(50), 
	"IS_CONTAIN" VARCHAR2(50) DEFAULT 'N', 
	"CREATE_TIME" VARCHAR2(50), 
	"ORG_FLOW" VARCHAR2(50), 
	"ORG_NAME" VARCHAR2(50), 
	"NOT_GRADUATE" VARCHAR2(50), 
	"GRADUATE" VARCHAR2(50), 
	"MONTH_OUTOFFICE_SUM" VARCHAR2(50), 
	"MONTH_ACTUAL_OUTOFFICE_SUM" VARCHAR2(50), 
	"MONTH_NOT_OUTOFFICE_SUM" VARCHAR2(50), 
	"OUTOFFICE_EXCEPTION_RATE" VARCHAR2(50), 
	"OUTOFFICE_DATA_FINISH_RATE" VARCHAR2(50), 
	"ROLE_FLAG" VARCHAR2(50), 
	"PROVINCE" VARCHAR2(50), 
	"CITY" VARCHAR2(50), 
	"UNIVERSITY" VARCHAR2(50), 
	 PRIMARY KEY ("RECORD_FLOW")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";

CREATE UNIQUE INDEX "PDSCI"."SYS_C0014282" ON "PDSCI"."PCU_DOCTOR_OUTOFFICE" ("RECORD_FLOW") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM";