<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8"%>
{
    "resultId": ${resultId},
    "resultType": ${pdfn:toJsonString(resultType)}
	 <c:if test="${resultId eq '200' }">
    ,
    "datas":[

        {
            "id":"RoleName",
            "name":"学员类型：",
            "value":${pdfn:toJsonString(detail.RoleName)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"TrueName",
            "name":"姓名：",
            "value":${pdfn:toJsonString(detail.TrueName)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"TecName",
            "name":"带教老师：",
            "value":${pdfn:toJsonString(detail.TecName)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"SpName",
            "name":"专业：",
            "value":${pdfn:toJsonString(detail.SpName)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"HosSecName",
            "name":"轮转科室：",
            "value":${pdfn:toJsonString(detail.HosSecName)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"RStartTime",
            "name":"入科时间：",
            "value":${pdfn:toJsonString(detail.RStartTime)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"REndTime",
            "name":"出科时间：",
            "value":${pdfn:toJsonString(detail.REndTime)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"UserNowState",
            "name":"报到状态：",
            "value":${pdfn:toJsonString(detail.UserNowState)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"complete",
            "name":"学生填写情况：",
            "value":${pdfn:toJsonString(complete)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"Eval",
            "name":"导师综合评价：",
            "value":${pdfn:toJsonString(detail.Eval)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"OutBriefTecState",
            "name":"带教审核：",
            "value":${pdfn:toJsonString(detail.OutBriefTecState)},
            "hidden":false,
            "readonly":true,
            "type":"text"
        },
        {
            "id":"OutBriefState",
            "name":"教秘审核：",
            "value":${pdfn:toJsonString(detail.OutBriefState)},
            "hidden":false,
            "readonly":true,
            <c:if test="${detail.OutBriefTecState eq '已审核'}">
                "type":"click"
            </c:if>
            <c:if test="${detail.OutBriefTecState ne '已审核'}">
                "type":"text"
            </c:if>
        }
    ]
	</c:if>
}
