
		<div>
			<nav>
				<ul>
					<li>
						<a>通知公告</a>
					</li>
					<li>
						<a>招录</a>
						<ul>
							<li><a>招生简章</a></li>
							<li><a href="<s:url value='/jsp/inx/zseyjxres/register.jsp'/>" >报名申请</a></li>
							<li><a>审核资格</a></li>
							<li><a>录取通知</a></li>
							
						</ul>
					</li>
					<li>
						<a>学员信息</a>
						<ul>
							<li><a>个人基本信息</a></li>
							<li><a>个人轮科信息</a></li>
							<li><a>个人成绩信息</a></li>
							<li><a>个人考勤信息</a></li>
							<li><a>个人奖惩信息</a></li>
							
						</ul>
					</li>
					<li><a>培训计划</a>
						<ul>
							<li><a>培训年限</a></li>
							<li><a>培训计划</a></li>
							
						</ul>
					</li>
					<li><a>考试考核</a>
						<ul>
							<li><a>日常考核</a></li>
							<li><a>出科考核</a></li>
							<li><a>年度考核</a></li>
							<li><a>结业考核</a></li>
							<li><a>执业医资格考核</a></li>
							<li><a>题库</a></li>
						</ul>
					</li>
					<li><a>教学活动</a>
						<ul>
							<li><a>活动通知</a></li>
							<li><a>活动记录</a></li>
							
						</ul>
					</li>
					<li><a>技能培训</a>
						<ul>
							<li><a>培训课程</a></li>
							<li><a>预约培训</a></li>
							<li><a>预约考核</a></li>
							
						</ul>
					</li>
					<li><a>教学资源</a>
						<ul>
							<li><a>教学视频</a></li>
							<li><a>电子课件</a></li>
							<li><a>医学图库</a></li>
						</ul>
					</li>
					<li><a>360&#176;评价</a>
						<ul>
							<li><a>学员对带教老师评价表</a></li>
							<li><a>学员对轮转科室评价表</a></li>
							<li><a>带教老师对学员评价表</a></li>
							<li><a>规培秘书对学员评价表</a></li>
							<li><a>护士对学员评价表</a></li>
							<li><a>患者对学员评价表</a></li>

						</ul>
					</li>
					<li><a>考勤管理</a>
						<ul>
							<li><a>请假申请</a></li>
							<li><a>销假申请</a></li>
						</ul>
					</li>
					<li><a>专业基地信息</a>
					</li>
					<li><a>统计分析</a>
						<ul>
							<li><a>招录</a></li>
							<li><a>学员信息</a></li>
							<li><a>培训计划</a></li>
							<li><a>考试考核</a></li>
							<li><a>教学活动</a></li>
							<li><a>技能培训</a></li>
							<li><a>教学资源</a></li>
							<li><a>360&#176;评价</a></li>
							<li><a>考勤管理</a></li>
						</ul>
					</li>
				</ul>
			</nav>
		</div>