
<div class="nav2">
	<li><a href="<s:url value='/inx/zseyGate?roleFlow=642caf7e58494875b528734dcf8b6829&tabId=tab1&modelId=${empty param.modelId ?\'All\':param.modelId}'/>"<c:if test="${param.tabId eq 'tab1'}">class="select" </c:if>>护理教学</a></li>
	<li><a href="<s:url value='/inx/zseyGate?roleFlow=642caf7e58494875b528734dcf8b6829&tabId=tab2&modelId=${empty param.modelId ?\'All\':param.modelId}'/>"<c:if test="${param.tabId eq 'tab2'}">class="select" </c:if>>护士培训</a></li>
</div>
<c:if test="${param.tabId eq 'tab1'}">
	<div>
		<nav>
			<ul>
				<li>
					<a>注册</a>
					<ul>
						<li><a href="<s:url value='/jsp/inx/zseyjxres/register.jsp'/>" >报名登记</a></li>
						<li><a>录取查询</a></li>
					</ul>
				</li>
				<li>
					<a>学生信息</a>
					<ul>
						<li><a>基本信息</a></li>
						<li><a>学生事件</a></li>
						<li><a>学生获奖情况</a></li>
						<li><a>学生请假审批</a></li>
					</ul>
				</li>
				<li><a>教学管理</a>
					<ul>
						<li><a>教学基地管理</a></li>
						<li><a>教学行政查房</a></li>
						<li><a>教务制度</a></li>
					</ul>
				</li>
				<li><a>教学计划</a>
					<ul>
						<li><a>本科生轮转</a></li>
						<li><a>研究生轮转</a></li>
						<li><a>夜大、自考</a></li>
						<li><a>见习轮转</a></li>
					</ul>
				</li>
				<li><a>考试考核</a>
					<ul>
						<li><a href="http://61.155.106.48:88/login/loginxiyi.aspx" target="_blank">理论考试</a></li>
						<li><a>技能考核</a></li>
						<li><a>护理教育小课考核</a></li>
						<li><a>题库</a></li>
					</ul>
				</li>
				<li><a>教学活动</a>
					<ul>
						<li><a>岗前培训</a></li>
						<li><a>小课</a></li>
						<li><a>查房</a></li>
						<li><a>公休会</a></li>
						<li><a>教学通知</a></li>
					</ul>
				</li>
				<li><a>技能培训</a>
					<ul>
						<li><a>操作示范</a></li>
						<li><a>操作考核</a></li>
						<li><a>技能中心预约</a></li>
					</ul>
				</li>
				<li><a>教学资源</a>
					<ul>
						<li><a>教学视频</a></li>
						<li><a>教学课件</a></li>
						<li><a>评分标准</a></li>
						<li><a>医学图库</a></li>
					</ul>
				</li>
				<li><a>教师管理</a>
					<ul>
						<li><a>师资信息</a></li>
						<li><a>教学工作量</a></li>
						<li><a>教师获奖情况</a></li>
						<li><a>教学事故登记</a></li>
					</ul>
				</li>
				<li><a>教学评价</a>
					<ul>
						<li><a>老师对学生评价</a></li>
						<li><a>病人对学生评价</a></li>
						<li><a>学生对教学评价</a></li>
						<li><a>教学评估</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>

</c:if>
<c:if test="${param.tabId eq 'tab2'}">
	<div>
		<nav>
			<ul>
				<li>
					<a>护士招录</a>
					<ul>
						<li><a>简历筛查</a></li>
						<li><a>理论考试</a></li>
						<li><a>试工管理</a></li>
						<li><a>面试成绩</a></li>
						<li><a>录取情况</a></li>
					</ul>
				</li>
				<li>
					<a>护士信息</a>
					<ul>
						<li><a>基本资料</a></li>
						<li><a>培训记录</a></li>
						<li><a>社会任职</a></li>
						<li><a>科研成绩</a></li>
					</ul>
				</li>
				<li><a>层级培训</a>
					<ul>
						<li><a>N0级培训</a></li>
						<li><a>N1a级培训</a></li>
						<li><a>N1b级培训</a></li>
						<li><a>N2级培训</a></li>
						<li><a>N3级培训</a></li>
						<li><a>N4级培训</a></li>
						<li><a>N5级培训</a></li>
						<li><a>N6级培训</a></li>
					</ul>
				</li>
				<li><a>培训资源</a>
					<ul>
						<li><a>培训视频</a></li>
						<li><a>电子课件</a></li>
						<li><a>评分标准</a></li>
						<li><a>医学图库</a></li>
					</ul>
				</li>
				<li><a>培训管理</a>
					<ul>
						<li><a>培训制度</a></li>
						<li><a>师资力量</a></li>
						<li><a>院内学习</a></li>
						<li><a>外出学习</a></li>
						<li><a>统计分析</a></li>
					</ul>
				</li>
			</ul>
		</nav>
	</div>

</c:if>