
		<div>
			<nav>
				<ul>
					<li>
						<a>注册</a>
						<ul>
							<li><a>复试登记</a></li>
							<li><a>录取信息</a></li>
						</ul>
					</li>
					<li>
						<a>学生信息</a>
						<ul>
							<li><a>学籍信息</a></li>
							<li><a>学生资助情况</a></li>
							<li><a>学生请假情况</a></li>
							<li><a>学生事件</a></li>
							<li><a>学生科研情况</a></li>
						</ul>
					</li>
					<li><a>学生管理</a>
						<ul>
							<li><a>出国资助申请</a></li>
							<li><a>资助金申请</a></li>
						</ul>
					</li>
					<li><a>教学管理</a>
						<ul>
							<li><a>临床型硕士轮科计划（继教科）</a></li>
							<li><a>临床实践课程表</a></li>
							<li><a>实验操作课程表</a></li>
						</ul>
					</li>
					<li><a>考试考核</a>
						<ul>
							<li><a>临床技能考试</a></li>
							<li><a>专业课考试</a></li>
							<li><a>小课考试</a></li>
							<li><a>题库</a></li>
						</ul>
					</li>
					<li><a>临床技能培训</a>
						<ul>
							<li><a>技能中心培训课程</a></li>
							<li><a>技能中心预约</a></li>
							<li><a>技能中心考核</a></li>
						</ul>
					</li>
					<li><a>导师管理</a>
						<ul>
							<li><a>导师信息</a></li>
							<li><a>导师考核</a></li>
							<li><a>导师科研业绩（科研科）</a></li>
							<li><a>导师指导小组</a></li>
							<li><a>招生计划申请</a></li>
						</ul>
					</li>
					<li><a>教学评价</a>
						<ul>
							<li><a>老师对学生评价</a></li>
							<li><a>病人对学生评价</a></li>
							<li><a>学生对教学评价</a></li>
						</ul>
					</li>
					<li><a>规章制度</a>
						<ul>
							<li><a>医院各项规章制度</a></li>
							<li><a>学校相关规章制度</a></li>
						</ul>
					</li>
					<li><a>教学资源</a>
						<ul>
							<li><a>教学视频</a></li>
							<li><a>教学课件</a></li>
						</ul>
					</li>
				</ul>
			</nav>
		</div>