<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
{
	 "resultId": ${resultId},
     "resultType": ${pdfn:toJsonString(resultType)}
    <c:if test="${resultId eq '200' }">
    ,
	"inputs":[
			{
				"inputId":"name",
				"inputType":"text",
				"label":"姓名",
				"readonly":true
			},
			{
				"inputId":"sessional",
				"inputType":"text",
				"label":"界别",
				"readonly":true
			}
			,
			{
				"inputId":"trainMajor",
				"inputType":"text",
				"label":"培训专业",
				"readonly":true
			}
			,
			{
				"inputId":"deptName",
				"inputType":"text",
				"label":"轮转科室名称",
				"readonly":true
			},
			{
				"inputId":"cycleTimeQ",
				"inputType":"text",
				"label":"开始时间",
				"readonly":true
			}
			,
			{
				"inputId":"cycleTimeH",
				"inputType":"text",
				"label":"结束时间",
				"readonly":true
			}
			,
			{
				"inputId":"kq",
				"inputType":"title",
				"label":"考勤"
			},
			{
				"inputId":"attendance",
				"inputType":"text",
				"label":"全勤",
				"required":false
			}
			,
			{
				"inputId":"leave",
				"inputType":"text",
				"label":"事假",
				"required":false
			}
			,
			{
				"inputId":"sickLeave",
				"inputType":"text",
				"label":"病假",
				"required":false
			}
			,
			{
				"inputId":"materLeave",
				"inputType":"text",
				"label":"产假",
				"required":false
			}
			,
			{
				"inputId":"absenteeism",
				"inputType":"text",
				"label":"旷工",
				"required":false
			}
			,
			{
				"inputId":"wcql",
				"inputType":"title",
				"label":"临床实践指标完成情况"
			}
			,
			{
				"inputId":"blsywc",
				"inputType":"text",
				"label":"病历数应完成",
				"readonly":true
			}
			,
			{
				"inputId":"blsyjwc",
				"inputType":"text",
				"label":"病历数已完成",
				"readonly":true
			}
			,
			{
				"inputId":"blswcbl",
				"inputType":"text",
				"label":"病历数完成比例",
				"readonly":true
			}
			,
			{
				"inputId":"bzsywc",
				"inputType":"text",
				"label":"病种数应完成",
				"readonly":true
			}
			,
			{
				"inputId":"bzsyjwc",
				"inputType":"text",
				"label":"病种数已完成",
				"readonly":true
			}
			,
			{
				"inputId":"bzswcbl",
				"inputType":"text",
				"label":"病种数完成比例",
				"readonly":true
			}
			,
			{
				"inputId":"czsywc",
				"inputType":"text",
				"label":"操作数应完成",
				"readonly":true
			}
			,
			{
				"inputId":"czsyjwc",
				"inputType":"text",
				"label":"操作数已完成",
				"readonly":true
			}
			,
			{
				"inputId":"czswcbl",
				"inputType":"text",
				"label":"操作数完成比例",
				"readonly":true
			}
			,
			{
				"inputId":"sssywc",
				"inputType":"text",
				"label":"手术数应完成",
				"readonly":true
			}
			,
			{
				"inputId":"sssyjwc",
				"inputType":"text",
				"label":"手术数已完成",
				"readonly":true
			}
			,
			{
				"inputId":"ssswcbl",
				"inputType":"text",
				"label":"手术数完成比例",
				"readonly":true
			}
			,
			{
				"inputId":"jxcb",
				"inputType":"text",
				"label":"教学查房",
				"readonly":true
			}
			,
			{
				"inputId":"nwzbltl",
				"inputType":"text",
				"label":"疑难、危重病例讨论",
				"readonly":true
			}
			,
			{
				"inputId":"xsjz",
				"inputType":"text",
				"label":"学术讲座",
				"readonly":true
			}
			,
			{
				"inputId":"swbltl",
				"inputType":"text",
				"label":"死亡病例讨论",
				"readonly":true
			}
			,
			{
				"inputId":"pj1",
				"inputType":"title",
				"label":"医德医风人际沟通团队合作"
			}
			,
			{
				"inputId":"zsgjflfg",
				"inputType":"select",
				"options":[{
					"optionDesc":"优",
					"optionId":"1"
				},{
					"optionDesc":"良",
					"optionId":"2"
				},{
					"optionDesc":"中",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"遵守国家法律法规、医院规章制度"
			}
			,
			{
				"inputId":"lxgwzz",
				"inputType":"select",
				"options":[{
					"optionDesc":"优",
					"optionId":"1"
				},{
					"optionDesc":"良",
					"optionId":"2"
				},{
					"optionDesc":"中",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"履行岗位职责"
			}
			,
			{
				"inputId":"ybrwzx",
				"inputType":"select",
				"options":[{
					"optionDesc":"优",
					"optionId":"1"
				},{
					"optionDesc":"良",
					"optionId":"2"
				},{
					"optionDesc":"中",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"以病人为中心，体现人文关怀"
			}
			,
			{
				"inputId":"rjgtbdnl",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"人际（医患）沟通和表达能力"
			}
			,
			{
				"inputId":"tjxzjsxm",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"团结协作精神"
			}
			,
			{
				"inputId":"pj2",
				"inputType":"title",
				"label":"临床综合能力"
			}
			,
			{
				"inputId":"jbllzwcd",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"临床基本知识、基本理论掌握程度"
			}
			,
			{
				"inputId":"njbjnzwcd",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"临床基本技能掌握程度"
			}
			,
			{
				"inputId":"lcswnl",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"临床思维能力"
			}
			,
			{
				"inputId":"lczlnl",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"临床诊疗能力"
			}
			,
			{
				"inputId":"jjclnl",
				"inputType":"select",
				"options":[{
					"optionDesc":"强",
					"optionId":"1"
				},{
					"optionDesc":"较强",
					"optionId":"2"
				},{
					"optionDesc":"一般",
					"optionId":"3"
				},{
					"optionDesc":"差",
					"optionId":"4"
				}],
				"label":"重病人的识别及紧急处理能力"
			}
			,
			{
				"inputId":"ckkh",
				"inputType":"title",
				"label":"出科考核"
			}
			,
			{
				"inputId":"theoreResult",
				"inputType":"text",
				"label":"理论成绩",
				"required":true
			}
			,
			{
				"inputId":"skillName",
				"inputType":"text",
				"label":"技能考核名称",
				"required":true
			}
			,
			{
				"inputId":"score",
				"inputType":"text",
				"label":"得分",
				"required":true
			}
			,
			{
				"inputId":"examiner1",
				"inputType":"text",
				"label":"考官1",
				"required":true
			}
			,
			{
				"inputId":"examiner2",
				"inputType":"text",
				"label":"考官2",
				"required":false
			}
			,
			{
				"inputId":"szkskhxzztpj",
				"inputType":"select",
				"options":[{
					"optionDesc":"通过",
					"optionId":"1"
				},{
					"optionDesc":"不通过",
					"optionId":"0"
				}],
				"label":"考核小组总体评价",
				"required":true
			}
			,
			{
				"inputId":"teacherName",
				"inputType":"text",
				"label":"带教老师签名",
				"required":true
			},
			{
				"inputId":"teacherDate",
				"inputType":"date",
				"label":"带教老师日期",
				"required":true
			},
			{
				"inputId":"directorName",
				"inputType":"text",
				"label":"科主任签名",
				"required":true
			},
			{
				"inputId":"directorDate",
				"inputType":"date",
				"label":"科主任日期",
				"required":true
			}
		],
		"values":[
			{
				"inputId":"name",
				"value":"张三"
			},
			{
				"inputId":"sessional",
				"value":"2015"
			}
			,
			{
				"inputId":"trainMajor",
				"value":"内科"
			}
			,
			{
				"inputId":"deptName",
				"value":"呼吸内科"
			},
			{
				"inputId":"cycleTimeQ",
				"value":"2015-12-01"
			}
			,
			{
				"inputId":"cycleTimeH",
				"value":"2015-12-31"
			}
			,
			{
				"inputId":"attendance",
				"value":"31天"
			}
			,
			{
				"inputId":"leave",
				"value":"0天"
			}
			,
			{
				"inputId":"sickLeave",
				"value":"0天"
			}
			,
			{
				"inputId":"materLeave",
				"value":"0天"
			}
			,
			{
				"inputId":"absenteeism",
				"value":"0天"
			}
			,
			{
				"inputId":"blsywc",
				"value":"20"
			}
			,
			{
				"inputId":"blsyjwc",
				"value":"20"
			}
			,
			{
				"inputId":"blswcbl",
				"value":"100"
			}
			,
			{
				"inputId":"bzsywc",
				"value":"20"
			}
			,
			{
				"inputId":"bzsyjwc",
				"value":"20"
			}
			,
			{
				"inputId":"bzswcbl",
				"value":"100"
			}
			,
			{
				"inputId":"czsywc",
				"value":"20"
			}
			,
			{
				"inputId":"czsyjwc",
				"value":"20"
			}
			,
			{
				"inputId":"czswcbl",
				"value":"100"
			}
			,
			{
				"inputId":"sssywc",
				"value":"20"
			}
			,
			{
				"inputId":"sssyjwc",
				"value":"20"
			}
			,
			{
				"inputId":"ssswcbl",
				"value":"100"
			}
			,
			{
				"inputId":"jxcb",
				"value":"50"
			}
			,
			{
				"inputId":"nwzbltl",
				"value":"10"
			}
			,
			{
				"inputId":"xsjz",
				"value":"10"
			}
			,
			{
				"inputId":"swbltl",
				"value":"10"
			}
			,
			{
				"inputId":"zsgjflfg",
				"value":"1"
			}
			,
			{
				"inputId":"lxgwzz",
				"value":"1"
			}
			,
			{
				"inputId":"ybrwzx",
				"value":"1"
			}
			,
			{
				"inputId":"rjgtbdnl",
				"value":"1"
			}
			,
			{
				"inputId":"tjxzjsxm",
				"value":"1"
			}
			,
			{
				"inputId":"jbllzwcd",
				"value":"1"
			}
			,
			{
				"inputId":"njbjnzwcd",
				"value":"1"
			}
			,
			{
				"inputId":"lcswnl",
				"value":"1"
			}
			,
			{
				"inputId":"lczlnl",
				"value":"1"
			}
			,
			{
				"inputId":"jjclnl",
				"value":"1"
			}
			,
			{
				"inputId":"theoreResult",
				"value":"90"
			}
			,
			{
				"inputId":"skillName",
				"value":"静脉注射"
			}
			,
			{
				"inputId":"score",
				"value":"95"
			}
			,
			{
				"inputId":"examiner1",
				"value":"王军"
			}
			,
			{
				"inputId":"examiner2",
				"value":"吴军"
			}
			,
			{
				"inputId":"szkskhxzztpj",
				"value":"1"
			}
			,
			{
				"inputId":"teacherName",
				"value":"李老师"
			}
			,
			{
				"inputId":"teacherDate",
				"value":"2015-12-31"
			}
			,
			{
				"inputId":"directorName",
				"value":"李主任"
			}
			,
			{
				"inputId":"teacherDate",
				"value":"2015-12-31"
			}
		]
	</c:if>
}