<div style="overflow:hidden;">
    <ul id="tags">
        <li id="tag0"
            <c:if test='${param.pageName=="step1" || empty param.pageName}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step1')" href="javascript:void(0)">封面信息</a></li>
        <li id="tag1"
            <c:if test='${param.pageName=="step2"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step2')" href="javascript:void(0)">基本信息</a></li>
        <li id="tag2"
            <c:if test='${param.pageName=="step3"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step3')" href="javascript:void(0)">推广项目内容</a></li>
        <li id="tag3"
            <c:if test='${param.pageName=="step4"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step4')" href="javascript:void(0)">成果技术水平</a></li>
        <li id="tag4"
            <c:if test='${param.pageName=="step5"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step5')" href="javascript:void(0)">已推广应用情况</a></li>
        <li id="tag5"
            <c:if test='${param.pageName=="step6"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step6')" href="javascript:void(0)">拟推广应用范围</a></li>
        <li id="tag6"
            <c:if test='${param.pageName=="step7"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step7')" href="javascript:void(0)">拟推广应用方式</a></li>
        <li id="tag7"
            <c:if test='${param.pageName=="step8"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step8')" href="javascript:void(0)">推广应用计划进度</a></li>
        <li id="tag8"
            <c:if test='${param.pageName=="step9"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step9')" href="javascript:void(0)">推广单位可提供的条件</a></li>
        <li id="tag9"
            <c:if test='${param.pageName=="step10"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step10')" href="javascript:void(0)">受推单位需具备的条件</a></li>
        <li id="tag10"
            <c:if test='${param.pageName=="step11"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step11')" href="javascript:void(0)">预期目标及健康、社会效益</a></li>
        <li id="tag11"
            <c:if test='${param.pageName=="step12"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step12')" href="javascript:void(0)">审核意见</a></li>
        <li id="tag12"
            <c:if test='${param.pageName=="step13"}'>class="selectTag"</c:if>><a
                onclick="nextOpt('step13')" href="javascript:void(0)">附件信息</a></li>
    </ul>
</div>