<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"save":"一键审核"
	},
	"search":[
        {
            "name":"未审核",
            "key":"join",
            "value":"NotAudit",
            "type":"tab"
        },
        {
            "name":"已审核",
            "key":"join",
            "value":"Audited", 
            "type":"tab"
        }
    ],
	"head":[
		{
			"headId":"cata",
			"label":" 类型"
		},
		{
			"headId":"time",
			"label":"填写日期"
		},
		{
			"headId":"content",
			"label":"填写内容"
		}
	],
	"datas":[
		{
			"dataFlow":"35991",
			"cata":"教学记录",
			"time":"2015-12-12",
			"content":"肺脓肿与肺曲霉的鉴别",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		},
		{
			"dataFlow":"35991",
			"cata":"大病历",
			"time":"2015-12-12",
			"content":"肛瘘(201230)",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		},
		{
			"dataFlow":"35991",
			"cata":"操作技能",
			"time":"2015-12-12",
			"content":"腹腔穿刺(一助)",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		},
		{
			"dataFlow":"35991",
			"cata":"管床记录",
			"time":"2015-12-12",
			"content":"结肠癌(150719056)",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		},
		{
			"dataFlow":"35991",
			"cata":"危重记录",
			"time":"2015-12-12",
			"content":"中风(123123)",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		},
		{
			"dataFlow":"35991",
			"cata":"参加活动",
			"time":"2015-12-12",
			"content":"肺脓肿与肺曲霉的鉴别",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		}
		,
		{
			"dataFlow":"35991",
			"cata":"实习记录",
			"time":"2015-12-12",
			"content":"门诊常规心电图操作",
			"statusDesc":"未审核",
			"statusId":"NotAudit"
		}
	]