<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"save":"提交" 
	},
	"inputs":[
		{
			"inputId":"name",
			"inputType":"title",
			"label":"姓名"
		},
		{
			"inputId":"personalSummary",
			"inputType":"textarea",
			"label":"个人小结",
			"readonly":true,
			"required":true
		}
		,
		{
			"inputId":"internshipEvaluation",
			"inputType":"select",
			"label":"实习表现评价",
			"placeholder":"实习表现评价",
			 "options":[{
				"optionId":"优",
				"optionDesc":"优"
			},
			{
				"optionId":"良",
				"optionDesc":"良"
			}
			,
			{
				"optionId":"中",
				"optionDesc":"中"
			}
			,
			{
				"optionId":"合格",
				"optionDesc":"合格"
			},
			{
				"optionId":"不合格",
				"optionDesc":"不合格"
			}]
			,
			"required":true
		},
		{
			"inputId":"theoryTest",
			"inputType":"text",
			"label":"理论考试（20分）",
			"placeholder":"根据实际分数折算",
			"required":true
		}
		,
		{
			"inputId":"skillTest",
			"inputType":"text",
			"label":"技能考核（80分）",
			"placeholder":"根据实际分数折算",
			"required":true
		},
		{
			"inputId":"total",
			"inputType":"text",
			"label":"总分",
			"placeholder":"满分100分",
			"readonly":true,
			"required":true
		}
	]
	,
	"values":[
		{
			"inputId":"name",
			"value":"张三"
		},
		{
			"inputId":"personalSummary",
			"value":"时光飞逝，转眼一周的实习已经结束....."
		}
		,
		{
			"inputId":"internshipEvaluation",
			"value":"优"
		}
		,
		{
			"inputId":"theoryTest",
			"value":"18"
		}
		,
		{
			"inputId":"skillTest",
			"value":"70"
		}
		,
		{
			"inputId":"total",
			"value":"88"
		}
	]
