package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

import java.math.BigDecimal;
import java.util.Date;

public class Casediscuss extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer cadisid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer hossecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer cysecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date cadistime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisContent
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String cadiscontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisPlayClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String cadisplayclass;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisPeriod
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private BigDecimal cadisperiod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisMainSpeaker
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String cadismainspeaker;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer checkstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaDisDes
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String cadisdes;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer docgrpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer doccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String caname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaAddress
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String caaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.CaseDiscuss.CaPeople
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String capeople;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisID
	 * @return  the value of dbo.CaseDiscuss.CaDisID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getCadisid() {
		return cadisid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisID
	 * @param cadisid  the value for dbo.CaseDiscuss.CaDisID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadisid(Integer cadisid) {
		this.cadisid = cadisid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.HosSecID
	 * @return  the value of dbo.CaseDiscuss.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getHossecid() {
		return hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.HosSecID
	 * @param hossecid  the value for dbo.CaseDiscuss.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setHossecid(Integer hossecid) {
		this.hossecid = hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CySecID
	 * @return  the value of dbo.CaseDiscuss.CySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getCysecid() {
		return cysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CySecID
	 * @param cysecid  the value for dbo.CaseDiscuss.CySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCysecid(Integer cysecid) {
		this.cysecid = cysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisTime
	 * @return  the value of dbo.CaseDiscuss.CaDisTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getCadistime() {
		return cadistime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisTime
	 * @param cadistime  the value for dbo.CaseDiscuss.CaDisTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadistime(Date cadistime) {
		this.cadistime = cadistime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisContent
	 * @return  the value of dbo.CaseDiscuss.CaDisContent
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCadiscontent() {
		return cadiscontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisContent
	 * @param cadiscontent  the value for dbo.CaseDiscuss.CaDisContent
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadiscontent(String cadiscontent) {
		this.cadiscontent = cadiscontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisPlayClass
	 * @return  the value of dbo.CaseDiscuss.CaDisPlayClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCadisplayclass() {
		return cadisplayclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisPlayClass
	 * @param cadisplayclass  the value for dbo.CaseDiscuss.CaDisPlayClass
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadisplayclass(String cadisplayclass) {
		this.cadisplayclass = cadisplayclass;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisPeriod
	 * @return  the value of dbo.CaseDiscuss.CaDisPeriod
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public BigDecimal getCadisperiod() {
		return cadisperiod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisPeriod
	 * @param cadisperiod  the value for dbo.CaseDiscuss.CaDisPeriod
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadisperiod(BigDecimal cadisperiod) {
		this.cadisperiod = cadisperiod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisMainSpeaker
	 * @return  the value of dbo.CaseDiscuss.CaDisMainSpeaker
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCadismainspeaker() {
		return cadismainspeaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisMainSpeaker
	 * @param cadismainspeaker  the value for dbo.CaseDiscuss.CaDisMainSpeaker
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadismainspeaker(String cadismainspeaker) {
		this.cadismainspeaker = cadismainspeaker;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CheckStatus
	 * @return  the value of dbo.CaseDiscuss.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getCheckstatus() {
		return checkstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CheckStatus
	 * @param checkstatus  the value for dbo.CaseDiscuss.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCheckstatus(Integer checkstatus) {
		this.checkstatus = checkstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaDisDes
	 * @return  the value of dbo.CaseDiscuss.CaDisDes
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCadisdes() {
		return cadisdes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaDisDes
	 * @param cadisdes  the value for dbo.CaseDiscuss.CaDisDes
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCadisdes(String cadisdes) {
		this.cadisdes = cadisdes;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.UserID
	 * @return  the value of dbo.CaseDiscuss.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.UserID
	 * @param userid  the value for dbo.CaseDiscuss.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.DocGRPID
	 * @return  the value of dbo.CaseDiscuss.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDocgrpid() {
		return docgrpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.DocGRPID
	 * @param docgrpid  the value for dbo.CaseDiscuss.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDocgrpid(Integer docgrpid) {
		this.docgrpid = docgrpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.DocCount
	 * @return  the value of dbo.CaseDiscuss.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDoccount() {
		return doccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.DocCount
	 * @param doccount  the value for dbo.CaseDiscuss.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDoccount(Integer doccount) {
		this.doccount = doccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaName
	 * @return  the value of dbo.CaseDiscuss.CaName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCaname() {
		return caname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaName
	 * @param caname  the value for dbo.CaseDiscuss.CaName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCaname(String caname) {
		this.caname = caname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaAddress
	 * @return  the value of dbo.CaseDiscuss.CaAddress
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCaaddress() {
		return caaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaAddress
	 * @param caaddress  the value for dbo.CaseDiscuss.CaAddress
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCaaddress(String caaddress) {
		this.caaddress = caaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.CaseDiscuss.CaPeople
	 * @return  the value of dbo.CaseDiscuss.CaPeople
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCapeople() {
		return capeople;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.CaseDiscuss.CaPeople
	 * @param capeople  the value for dbo.CaseDiscuss.CaPeople
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCapeople(String capeople) {
		this.capeople = capeople;
	}
}