package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

public class Dicitem extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DicItem.DicItemID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer dicitemid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DicItem.DicID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer dicid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DicItem.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String dicitem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.DicItem.DicTYBZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer dictybz;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DicItem.DicItemID
	 * @return  the value of dbo.DicItem.DicItemID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDicitemid() {
		return dicitemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DicItem.DicItemID
	 * @param dicitemid  the value for dbo.DicItem.DicItemID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDicitemid(Integer dicitemid) {
		this.dicitemid = dicitemid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DicItem.DicID
	 * @return  the value of dbo.DicItem.DicID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDicid() {
		return dicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DicItem.DicID
	 * @param dicid  the value for dbo.DicItem.DicID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDicid(Integer dicid) {
		this.dicid = dicid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DicItem.DicItem
	 * @return  the value of dbo.DicItem.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getDicitem() {
		return dicitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DicItem.DicItem
	 * @param dicitem  the value for dbo.DicItem.DicItem
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDicitem(String dicitem) {
		this.dicitem = dicitem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.DicItem.DicTYBZ
	 * @return  the value of dbo.DicItem.DicTYBZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDictybz() {
		return dictybz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.DicItem.DicTYBZ
	 * @param dictybz  the value for dbo.DicItem.DicTYBZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDictybz(Integer dictybz) {
		this.dictybz = dictybz;
	}
}