package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

import java.util.Date;

public class Outsecbrief extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.BriefID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer briefid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.BriefRequrie
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String briefrequrie;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.SecAppraise
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String secappraise;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.CySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer cysecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer docgrpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer doccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Boolean checkstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.ChiefCheckContent
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String chiefcheckcontent;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.ChiefUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer chiefuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.ChiefCheckDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date chiefcheckdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer ucsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.TecUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer tecuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.TecCheckDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date teccheckdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.OutDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date outdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.OutSecBrief.OSBHtml
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String osbhtml;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.BriefID
	 * @return  the value of dbo.OutSecBrief.BriefID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getBriefid() {
		return briefid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.BriefID
	 * @param briefid  the value for dbo.OutSecBrief.BriefID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setBriefid(Integer briefid) {
		this.briefid = briefid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.BriefRequrie
	 * @return  the value of dbo.OutSecBrief.BriefRequrie
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getBriefrequrie() {
		return briefrequrie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.BriefRequrie
	 * @param briefrequrie  the value for dbo.OutSecBrief.BriefRequrie
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setBriefrequrie(String briefrequrie) {
		this.briefrequrie = briefrequrie;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.SecAppraise
	 * @return  the value of dbo.OutSecBrief.SecAppraise
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getSecappraise() {
		return secappraise;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.SecAppraise
	 * @param secappraise  the value for dbo.OutSecBrief.SecAppraise
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSecappraise(String secappraise) {
		this.secappraise = secappraise;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.UserID
	 * @return  the value of dbo.OutSecBrief.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.UserID
	 * @param userid  the value for dbo.OutSecBrief.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.CySecID
	 * @return  the value of dbo.OutSecBrief.CySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getCysecid() {
		return cysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.CySecID
	 * @param cysecid  the value for dbo.OutSecBrief.CySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCysecid(Integer cysecid) {
		this.cysecid = cysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.DocGRPID
	 * @return  the value of dbo.OutSecBrief.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDocgrpid() {
		return docgrpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.DocGRPID
	 * @param docgrpid  the value for dbo.OutSecBrief.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDocgrpid(Integer docgrpid) {
		this.docgrpid = docgrpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.DocCount
	 * @return  the value of dbo.OutSecBrief.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDoccount() {
		return doccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.DocCount
	 * @param doccount  the value for dbo.OutSecBrief.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDoccount(Integer doccount) {
		this.doccount = doccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.CheckStatus
	 * @return  the value of dbo.OutSecBrief.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Boolean getCheckstatus() {
		return checkstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.CheckStatus
	 * @param checkstatus  the value for dbo.OutSecBrief.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCheckstatus(Boolean checkstatus) {
		this.checkstatus = checkstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.ChiefCheckContent
	 * @return  the value of dbo.OutSecBrief.ChiefCheckContent
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getChiefcheckcontent() {
		return chiefcheckcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.ChiefCheckContent
	 * @param chiefcheckcontent  the value for dbo.OutSecBrief.ChiefCheckContent
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setChiefcheckcontent(String chiefcheckcontent) {
		this.chiefcheckcontent = chiefcheckcontent;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.ChiefUserID
	 * @return  the value of dbo.OutSecBrief.ChiefUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getChiefuserid() {
		return chiefuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.ChiefUserID
	 * @param chiefuserid  the value for dbo.OutSecBrief.ChiefUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setChiefuserid(Integer chiefuserid) {
		this.chiefuserid = chiefuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.ChiefCheckDate
	 * @return  the value of dbo.OutSecBrief.ChiefCheckDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getChiefcheckdate() {
		return chiefcheckdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.ChiefCheckDate
	 * @param chiefcheckdate  the value for dbo.OutSecBrief.ChiefCheckDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setChiefcheckdate(Date chiefcheckdate) {
		this.chiefcheckdate = chiefcheckdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.UCSID
	 * @return  the value of dbo.OutSecBrief.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUcsid() {
		return ucsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.UCSID
	 * @param ucsid  the value for dbo.OutSecBrief.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUcsid(Integer ucsid) {
		this.ucsid = ucsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.TecUserID
	 * @return  the value of dbo.OutSecBrief.TecUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getTecuserid() {
		return tecuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.TecUserID
	 * @param tecuserid  the value for dbo.OutSecBrief.TecUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTecuserid(Integer tecuserid) {
		this.tecuserid = tecuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.TecCheckDate
	 * @return  the value of dbo.OutSecBrief.TecCheckDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getTeccheckdate() {
		return teccheckdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.TecCheckDate
	 * @param teccheckdate  the value for dbo.OutSecBrief.TecCheckDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTeccheckdate(Date teccheckdate) {
		this.teccheckdate = teccheckdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.OutDate
	 * @return  the value of dbo.OutSecBrief.OutDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getOutdate() {
		return outdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.OutDate
	 * @param outdate  the value for dbo.OutSecBrief.OutDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOutdate(Date outdate) {
		this.outdate = outdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.OutSecBrief.OSBHtml
	 * @return  the value of dbo.OutSecBrief.OSBHtml
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOsbhtml() {
		return osbhtml;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.OutSecBrief.OSBHtml
	 * @param osbhtml  the value for dbo.OutSecBrief.OSBHtml
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOsbhtml(String osbhtml) {
		this.osbhtml = osbhtml;
	}
}