package com.pinde.res.model.njmu.mo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OutsecbriefExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public OutsecbriefExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andBriefidIsNull() {
			addCriterion("BriefID is null");
			return (Criteria) this;
		}

		public Criteria andBriefidIsNotNull() {
			addCriterion("BriefID is not null");
			return (Criteria) this;
		}

		public Criteria andBriefidEqualTo(Integer value) {
			addCriterion("BriefID =", value, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidNotEqualTo(Integer value) {
			addCriterion("BriefID <>", value, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidGreaterThan(Integer value) {
			addCriterion("BriefID >", value, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidGreaterThanOrEqualTo(Integer value) {
			addCriterion("BriefID >=", value, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidLessThan(Integer value) {
			addCriterion("BriefID <", value, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidLessThanOrEqualTo(Integer value) {
			addCriterion("BriefID <=", value, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidIn(List<Integer> values) {
			addCriterion("BriefID in", values, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidNotIn(List<Integer> values) {
			addCriterion("BriefID not in", values, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidBetween(Integer value1, Integer value2) {
			addCriterion("BriefID between", value1, value2, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefidNotBetween(Integer value1, Integer value2) {
			addCriterion("BriefID not between", value1, value2, "briefid");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieIsNull() {
			addCriterion("BriefRequrie is null");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieIsNotNull() {
			addCriterion("BriefRequrie is not null");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieEqualTo(String value) {
			addCriterion("BriefRequrie =", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieNotEqualTo(String value) {
			addCriterion("BriefRequrie <>", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieGreaterThan(String value) {
			addCriterion("BriefRequrie >", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieGreaterThanOrEqualTo(String value) {
			addCriterion("BriefRequrie >=", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieLessThan(String value) {
			addCriterion("BriefRequrie <", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieLessThanOrEqualTo(String value) {
			addCriterion("BriefRequrie <=", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieLike(String value) {
			addCriterion("BriefRequrie like", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieNotLike(String value) {
			addCriterion("BriefRequrie not like", value, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieIn(List<String> values) {
			addCriterion("BriefRequrie in", values, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieNotIn(List<String> values) {
			addCriterion("BriefRequrie not in", values, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieBetween(String value1, String value2) {
			addCriterion("BriefRequrie between", value1, value2, "briefrequrie");
			return (Criteria) this;
		}

		public Criteria andBriefrequrieNotBetween(String value1, String value2) {
			addCriterion("BriefRequrie not between", value1, value2,
					"briefrequrie");
			return (Criteria) this;
		}

		public Criteria andSecappraiseIsNull() {
			addCriterion("SecAppraise is null");
			return (Criteria) this;
		}

		public Criteria andSecappraiseIsNotNull() {
			addCriterion("SecAppraise is not null");
			return (Criteria) this;
		}

		public Criteria andSecappraiseEqualTo(String value) {
			addCriterion("SecAppraise =", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseNotEqualTo(String value) {
			addCriterion("SecAppraise <>", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseGreaterThan(String value) {
			addCriterion("SecAppraise >", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseGreaterThanOrEqualTo(String value) {
			addCriterion("SecAppraise >=", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseLessThan(String value) {
			addCriterion("SecAppraise <", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseLessThanOrEqualTo(String value) {
			addCriterion("SecAppraise <=", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseLike(String value) {
			addCriterion("SecAppraise like", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseNotLike(String value) {
			addCriterion("SecAppraise not like", value, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseIn(List<String> values) {
			addCriterion("SecAppraise in", values, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseNotIn(List<String> values) {
			addCriterion("SecAppraise not in", values, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseBetween(String value1, String value2) {
			addCriterion("SecAppraise between", value1, value2, "secappraise");
			return (Criteria) this;
		}

		public Criteria andSecappraiseNotBetween(String value1, String value2) {
			addCriterion("SecAppraise not between", value1, value2,
					"secappraise");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("UserID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("UserID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("UserID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("UserID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("UserID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("UserID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("UserID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("UserID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("UserID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("UserID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("UserID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("UserID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andCysecidIsNull() {
			addCriterion("CySecID is null");
			return (Criteria) this;
		}

		public Criteria andCysecidIsNotNull() {
			addCriterion("CySecID is not null");
			return (Criteria) this;
		}

		public Criteria andCysecidEqualTo(Integer value) {
			addCriterion("CySecID =", value, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidNotEqualTo(Integer value) {
			addCriterion("CySecID <>", value, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidGreaterThan(Integer value) {
			addCriterion("CySecID >", value, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidGreaterThanOrEqualTo(Integer value) {
			addCriterion("CySecID >=", value, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidLessThan(Integer value) {
			addCriterion("CySecID <", value, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidLessThanOrEqualTo(Integer value) {
			addCriterion("CySecID <=", value, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidIn(List<Integer> values) {
			addCriterion("CySecID in", values, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidNotIn(List<Integer> values) {
			addCriterion("CySecID not in", values, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidBetween(Integer value1, Integer value2) {
			addCriterion("CySecID between", value1, value2, "cysecid");
			return (Criteria) this;
		}

		public Criteria andCysecidNotBetween(Integer value1, Integer value2) {
			addCriterion("CySecID not between", value1, value2, "cysecid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidIsNull() {
			addCriterion("DocGRPID is null");
			return (Criteria) this;
		}

		public Criteria andDocgrpidIsNotNull() {
			addCriterion("DocGRPID is not null");
			return (Criteria) this;
		}

		public Criteria andDocgrpidEqualTo(Integer value) {
			addCriterion("DocGRPID =", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidNotEqualTo(Integer value) {
			addCriterion("DocGRPID <>", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidGreaterThan(Integer value) {
			addCriterion("DocGRPID >", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidGreaterThanOrEqualTo(Integer value) {
			addCriterion("DocGRPID >=", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidLessThan(Integer value) {
			addCriterion("DocGRPID <", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidLessThanOrEqualTo(Integer value) {
			addCriterion("DocGRPID <=", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidIn(List<Integer> values) {
			addCriterion("DocGRPID in", values, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidNotIn(List<Integer> values) {
			addCriterion("DocGRPID not in", values, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidBetween(Integer value1, Integer value2) {
			addCriterion("DocGRPID between", value1, value2, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidNotBetween(Integer value1, Integer value2) {
			addCriterion("DocGRPID not between", value1, value2, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDoccountIsNull() {
			addCriterion("DocCount is null");
			return (Criteria) this;
		}

		public Criteria andDoccountIsNotNull() {
			addCriterion("DocCount is not null");
			return (Criteria) this;
		}

		public Criteria andDoccountEqualTo(Integer value) {
			addCriterion("DocCount =", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountNotEqualTo(Integer value) {
			addCriterion("DocCount <>", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountGreaterThan(Integer value) {
			addCriterion("DocCount >", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountGreaterThanOrEqualTo(Integer value) {
			addCriterion("DocCount >=", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountLessThan(Integer value) {
			addCriterion("DocCount <", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountLessThanOrEqualTo(Integer value) {
			addCriterion("DocCount <=", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountIn(List<Integer> values) {
			addCriterion("DocCount in", values, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountNotIn(List<Integer> values) {
			addCriterion("DocCount not in", values, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountBetween(Integer value1, Integer value2) {
			addCriterion("DocCount between", value1, value2, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountNotBetween(Integer value1, Integer value2) {
			addCriterion("DocCount not between", value1, value2, "doccount");
			return (Criteria) this;
		}

		public Criteria andCheckstatusIsNull() {
			addCriterion("CheckStatus is null");
			return (Criteria) this;
		}

		public Criteria andCheckstatusIsNotNull() {
			addCriterion("CheckStatus is not null");
			return (Criteria) this;
		}

		public Criteria andCheckstatusEqualTo(Boolean value) {
			addCriterion("CheckStatus =", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusNotEqualTo(Boolean value) {
			addCriterion("CheckStatus <>", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusGreaterThan(Boolean value) {
			addCriterion("CheckStatus >", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusGreaterThanOrEqualTo(Boolean value) {
			addCriterion("CheckStatus >=", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusLessThan(Boolean value) {
			addCriterion("CheckStatus <", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusLessThanOrEqualTo(Boolean value) {
			addCriterion("CheckStatus <=", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusIn(List<Boolean> values) {
			addCriterion("CheckStatus in", values, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusNotIn(List<Boolean> values) {
			addCriterion("CheckStatus not in", values, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusBetween(Boolean value1, Boolean value2) {
			addCriterion("CheckStatus between", value1, value2, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusNotBetween(Boolean value1, Boolean value2) {
			addCriterion("CheckStatus not between", value1, value2,
					"checkstatus");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentIsNull() {
			addCriterion("ChiefCheckContent is null");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentIsNotNull() {
			addCriterion("ChiefCheckContent is not null");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentEqualTo(String value) {
			addCriterion("ChiefCheckContent =", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentNotEqualTo(String value) {
			addCriterion("ChiefCheckContent <>", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentGreaterThan(String value) {
			addCriterion("ChiefCheckContent >", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentGreaterThanOrEqualTo(String value) {
			addCriterion("ChiefCheckContent >=", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentLessThan(String value) {
			addCriterion("ChiefCheckContent <", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentLessThanOrEqualTo(String value) {
			addCriterion("ChiefCheckContent <=", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentLike(String value) {
			addCriterion("ChiefCheckContent like", value, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentNotLike(String value) {
			addCriterion("ChiefCheckContent not like", value,
					"chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentIn(List<String> values) {
			addCriterion("ChiefCheckContent in", values, "chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentNotIn(List<String> values) {
			addCriterion("ChiefCheckContent not in", values,
					"chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentBetween(String value1, String value2) {
			addCriterion("ChiefCheckContent between", value1, value2,
					"chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefcheckcontentNotBetween(String value1,
				String value2) {
			addCriterion("ChiefCheckContent not between", value1, value2,
					"chiefcheckcontent");
			return (Criteria) this;
		}

		public Criteria andChiefuseridIsNull() {
			addCriterion("ChiefUserID is null");
			return (Criteria) this;
		}

		public Criteria andChiefuseridIsNotNull() {
			addCriterion("ChiefUserID is not null");
			return (Criteria) this;
		}

		public Criteria andChiefuseridEqualTo(Integer value) {
			addCriterion("ChiefUserID =", value, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridNotEqualTo(Integer value) {
			addCriterion("ChiefUserID <>", value, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridGreaterThan(Integer value) {
			addCriterion("ChiefUserID >", value, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("ChiefUserID >=", value, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridLessThan(Integer value) {
			addCriterion("ChiefUserID <", value, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridLessThanOrEqualTo(Integer value) {
			addCriterion("ChiefUserID <=", value, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridIn(List<Integer> values) {
			addCriterion("ChiefUserID in", values, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridNotIn(List<Integer> values) {
			addCriterion("ChiefUserID not in", values, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridBetween(Integer value1, Integer value2) {
			addCriterion("ChiefUserID between", value1, value2, "chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefuseridNotBetween(Integer value1, Integer value2) {
			addCriterion("ChiefUserID not between", value1, value2,
					"chiefuserid");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateIsNull() {
			addCriterion("ChiefCheckDate is null");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateIsNotNull() {
			addCriterion("ChiefCheckDate is not null");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateEqualTo(Date value) {
			addCriterion("ChiefCheckDate =", value, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateNotEqualTo(Date value) {
			addCriterion("ChiefCheckDate <>", value, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateGreaterThan(Date value) {
			addCriterion("ChiefCheckDate >", value, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateGreaterThanOrEqualTo(Date value) {
			addCriterion("ChiefCheckDate >=", value, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateLessThan(Date value) {
			addCriterion("ChiefCheckDate <", value, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateLessThanOrEqualTo(Date value) {
			addCriterion("ChiefCheckDate <=", value, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateIn(List<Date> values) {
			addCriterion("ChiefCheckDate in", values, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateNotIn(List<Date> values) {
			addCriterion("ChiefCheckDate not in", values, "chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateBetween(Date value1, Date value2) {
			addCriterion("ChiefCheckDate between", value1, value2,
					"chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andChiefcheckdateNotBetween(Date value1, Date value2) {
			addCriterion("ChiefCheckDate not between", value1, value2,
					"chiefcheckdate");
			return (Criteria) this;
		}

		public Criteria andUcsidIsNull() {
			addCriterion("UCSID is null");
			return (Criteria) this;
		}

		public Criteria andUcsidIsNotNull() {
			addCriterion("UCSID is not null");
			return (Criteria) this;
		}

		public Criteria andUcsidEqualTo(Integer value) {
			addCriterion("UCSID =", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidNotEqualTo(Integer value) {
			addCriterion("UCSID <>", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidGreaterThan(Integer value) {
			addCriterion("UCSID >", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidGreaterThanOrEqualTo(Integer value) {
			addCriterion("UCSID >=", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidLessThan(Integer value) {
			addCriterion("UCSID <", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidLessThanOrEqualTo(Integer value) {
			addCriterion("UCSID <=", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidIn(List<Integer> values) {
			addCriterion("UCSID in", values, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidNotIn(List<Integer> values) {
			addCriterion("UCSID not in", values, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidBetween(Integer value1, Integer value2) {
			addCriterion("UCSID between", value1, value2, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidNotBetween(Integer value1, Integer value2) {
			addCriterion("UCSID not between", value1, value2, "ucsid");
			return (Criteria) this;
		}

		public Criteria andTecuseridIsNull() {
			addCriterion("TecUserID is null");
			return (Criteria) this;
		}

		public Criteria andTecuseridIsNotNull() {
			addCriterion("TecUserID is not null");
			return (Criteria) this;
		}

		public Criteria andTecuseridEqualTo(Integer value) {
			addCriterion("TecUserID =", value, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridNotEqualTo(Integer value) {
			addCriterion("TecUserID <>", value, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridGreaterThan(Integer value) {
			addCriterion("TecUserID >", value, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("TecUserID >=", value, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridLessThan(Integer value) {
			addCriterion("TecUserID <", value, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridLessThanOrEqualTo(Integer value) {
			addCriterion("TecUserID <=", value, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridIn(List<Integer> values) {
			addCriterion("TecUserID in", values, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridNotIn(List<Integer> values) {
			addCriterion("TecUserID not in", values, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridBetween(Integer value1, Integer value2) {
			addCriterion("TecUserID between", value1, value2, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTecuseridNotBetween(Integer value1, Integer value2) {
			addCriterion("TecUserID not between", value1, value2, "tecuserid");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateIsNull() {
			addCriterion("TecCheckDate is null");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateIsNotNull() {
			addCriterion("TecCheckDate is not null");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateEqualTo(Date value) {
			addCriterion("TecCheckDate =", value, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateNotEqualTo(Date value) {
			addCriterion("TecCheckDate <>", value, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateGreaterThan(Date value) {
			addCriterion("TecCheckDate >", value, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateGreaterThanOrEqualTo(Date value) {
			addCriterion("TecCheckDate >=", value, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateLessThan(Date value) {
			addCriterion("TecCheckDate <", value, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateLessThanOrEqualTo(Date value) {
			addCriterion("TecCheckDate <=", value, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateIn(List<Date> values) {
			addCriterion("TecCheckDate in", values, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateNotIn(List<Date> values) {
			addCriterion("TecCheckDate not in", values, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateBetween(Date value1, Date value2) {
			addCriterion("TecCheckDate between", value1, value2, "teccheckdate");
			return (Criteria) this;
		}

		public Criteria andTeccheckdateNotBetween(Date value1, Date value2) {
			addCriterion("TecCheckDate not between", value1, value2,
					"teccheckdate");
			return (Criteria) this;
		}

		public Criteria andOutdateIsNull() {
			addCriterion("OutDate is null");
			return (Criteria) this;
		}

		public Criteria andOutdateIsNotNull() {
			addCriterion("OutDate is not null");
			return (Criteria) this;
		}

		public Criteria andOutdateEqualTo(Date value) {
			addCriterion("OutDate =", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateNotEqualTo(Date value) {
			addCriterion("OutDate <>", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateGreaterThan(Date value) {
			addCriterion("OutDate >", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateGreaterThanOrEqualTo(Date value) {
			addCriterion("OutDate >=", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateLessThan(Date value) {
			addCriterion("OutDate <", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateLessThanOrEqualTo(Date value) {
			addCriterion("OutDate <=", value, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateIn(List<Date> values) {
			addCriterion("OutDate in", values, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateNotIn(List<Date> values) {
			addCriterion("OutDate not in", values, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateBetween(Date value1, Date value2) {
			addCriterion("OutDate between", value1, value2, "outdate");
			return (Criteria) this;
		}

		public Criteria andOutdateNotBetween(Date value1, Date value2) {
			addCriterion("OutDate not between", value1, value2, "outdate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.OutSecBrief
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.OutSecBrief
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 30 09:32:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}