package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

import java.util.Date;

public class RecCaseclass extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer recid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.FromID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer fromid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer checkstatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer doccount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer docgrpid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date recdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData1
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData2
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData3
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData4
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData5
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData6
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata6;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData7
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata7;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData8
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata8;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData9
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata9;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData10
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata10;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData11
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata11;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData12
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata12;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData13
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata13;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData14
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata14;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData15
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata15;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData16
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata16;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData17
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata17;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData18
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata18;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData19
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata19;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.RecData20
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String recdata20;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.Rec_CaseClass.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer hossecid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecID
	 * @return  the value of dbo.Rec_CaseClass.RecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getRecid() {
		return recid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecID
	 * @param recid  the value for dbo.Rec_CaseClass.RecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecid(Integer recid) {
		this.recid = recid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.UserID
	 * @return  the value of dbo.Rec_CaseClass.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.UserID
	 * @param userid  the value for dbo.Rec_CaseClass.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.FromID
	 * @return  the value of dbo.Rec_CaseClass.FromID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getFromid() {
		return fromid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.FromID
	 * @param fromid  the value for dbo.Rec_CaseClass.FromID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setFromid(Integer fromid) {
		this.fromid = fromid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.CheckStatus
	 * @return  the value of dbo.Rec_CaseClass.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getCheckstatus() {
		return checkstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.CheckStatus
	 * @param checkstatus  the value for dbo.Rec_CaseClass.CheckStatus
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCheckstatus(Integer checkstatus) {
		this.checkstatus = checkstatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.DocCount
	 * @return  the value of dbo.Rec_CaseClass.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDoccount() {
		return doccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.DocCount
	 * @param doccount  the value for dbo.Rec_CaseClass.DocCount
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDoccount(Integer doccount) {
		this.doccount = doccount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.DocGRPID
	 * @return  the value of dbo.Rec_CaseClass.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDocgrpid() {
		return docgrpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.DocGRPID
	 * @param docgrpid  the value for dbo.Rec_CaseClass.DocGRPID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDocgrpid(Integer docgrpid) {
		this.docgrpid = docgrpid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecDate
	 * @return  the value of dbo.Rec_CaseClass.RecDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getRecdate() {
		return recdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecDate
	 * @param recdate  the value for dbo.Rec_CaseClass.RecDate
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdate(Date recdate) {
		this.recdate = recdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData1
	 * @return  the value of dbo.Rec_CaseClass.RecData1
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata1() {
		return recdata1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData1
	 * @param recdata1  the value for dbo.Rec_CaseClass.RecData1
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata1(String recdata1) {
		this.recdata1 = recdata1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData2
	 * @return  the value of dbo.Rec_CaseClass.RecData2
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata2() {
		return recdata2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData2
	 * @param recdata2  the value for dbo.Rec_CaseClass.RecData2
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata2(String recdata2) {
		this.recdata2 = recdata2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData3
	 * @return  the value of dbo.Rec_CaseClass.RecData3
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata3() {
		return recdata3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData3
	 * @param recdata3  the value for dbo.Rec_CaseClass.RecData3
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata3(String recdata3) {
		this.recdata3 = recdata3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData4
	 * @return  the value of dbo.Rec_CaseClass.RecData4
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata4() {
		return recdata4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData4
	 * @param recdata4  the value for dbo.Rec_CaseClass.RecData4
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata4(String recdata4) {
		this.recdata4 = recdata4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData5
	 * @return  the value of dbo.Rec_CaseClass.RecData5
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata5() {
		return recdata5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData5
	 * @param recdata5  the value for dbo.Rec_CaseClass.RecData5
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata5(String recdata5) {
		this.recdata5 = recdata5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData6
	 * @return  the value of dbo.Rec_CaseClass.RecData6
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata6() {
		return recdata6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData6
	 * @param recdata6  the value for dbo.Rec_CaseClass.RecData6
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata6(String recdata6) {
		this.recdata6 = recdata6;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData7
	 * @return  the value of dbo.Rec_CaseClass.RecData7
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata7() {
		return recdata7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData7
	 * @param recdata7  the value for dbo.Rec_CaseClass.RecData7
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata7(String recdata7) {
		this.recdata7 = recdata7;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData8
	 * @return  the value of dbo.Rec_CaseClass.RecData8
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata8() {
		return recdata8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData8
	 * @param recdata8  the value for dbo.Rec_CaseClass.RecData8
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata8(String recdata8) {
		this.recdata8 = recdata8;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData9
	 * @return  the value of dbo.Rec_CaseClass.RecData9
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata9() {
		return recdata9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData9
	 * @param recdata9  the value for dbo.Rec_CaseClass.RecData9
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata9(String recdata9) {
		this.recdata9 = recdata9;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData10
	 * @return  the value of dbo.Rec_CaseClass.RecData10
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata10() {
		return recdata10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData10
	 * @param recdata10  the value for dbo.Rec_CaseClass.RecData10
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata10(String recdata10) {
		this.recdata10 = recdata10;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData11
	 * @return  the value of dbo.Rec_CaseClass.RecData11
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata11() {
		return recdata11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData11
	 * @param recdata11  the value for dbo.Rec_CaseClass.RecData11
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata11(String recdata11) {
		this.recdata11 = recdata11;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData12
	 * @return  the value of dbo.Rec_CaseClass.RecData12
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata12() {
		return recdata12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData12
	 * @param recdata12  the value for dbo.Rec_CaseClass.RecData12
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata12(String recdata12) {
		this.recdata12 = recdata12;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData13
	 * @return  the value of dbo.Rec_CaseClass.RecData13
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata13() {
		return recdata13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData13
	 * @param recdata13  the value for dbo.Rec_CaseClass.RecData13
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata13(String recdata13) {
		this.recdata13 = recdata13;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData14
	 * @return  the value of dbo.Rec_CaseClass.RecData14
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata14() {
		return recdata14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData14
	 * @param recdata14  the value for dbo.Rec_CaseClass.RecData14
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata14(String recdata14) {
		this.recdata14 = recdata14;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData15
	 * @return  the value of dbo.Rec_CaseClass.RecData15
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata15() {
		return recdata15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData15
	 * @param recdata15  the value for dbo.Rec_CaseClass.RecData15
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata15(String recdata15) {
		this.recdata15 = recdata15;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData16
	 * @return  the value of dbo.Rec_CaseClass.RecData16
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata16() {
		return recdata16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData16
	 * @param recdata16  the value for dbo.Rec_CaseClass.RecData16
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata16(String recdata16) {
		this.recdata16 = recdata16;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData17
	 * @return  the value of dbo.Rec_CaseClass.RecData17
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata17() {
		return recdata17;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData17
	 * @param recdata17  the value for dbo.Rec_CaseClass.RecData17
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata17(String recdata17) {
		this.recdata17 = recdata17;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData18
	 * @return  the value of dbo.Rec_CaseClass.RecData18
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata18() {
		return recdata18;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData18
	 * @param recdata18  the value for dbo.Rec_CaseClass.RecData18
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata18(String recdata18) {
		this.recdata18 = recdata18;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData19
	 * @return  the value of dbo.Rec_CaseClass.RecData19
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata19() {
		return recdata19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData19
	 * @param recdata19  the value for dbo.Rec_CaseClass.RecData19
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata19(String recdata19) {
		this.recdata19 = recdata19;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.RecData20
	 * @return  the value of dbo.Rec_CaseClass.RecData20
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRecdata20() {
		return recdata20;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.RecData20
	 * @param recdata20  the value for dbo.Rec_CaseClass.RecData20
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRecdata20(String recdata20) {
		this.recdata20 = recdata20;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.Rec_CaseClass.HosSecID
	 * @return  the value of dbo.Rec_CaseClass.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getHossecid() {
		return hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.Rec_CaseClass.HosSecID
	 * @param hossecid  the value for dbo.Rec_CaseClass.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setHossecid(Integer hossecid) {
		this.hossecid = hossecid;
	}
}