package com.pinde.res.model.njmu.mo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class RecOperateskillExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public RecOperateskillExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRecidIsNull() {
			addCriterion("RecID is null");
			return (Criteria) this;
		}

		public Criteria andRecidIsNotNull() {
			addCriterion("RecID is not null");
			return (Criteria) this;
		}

		public Criteria andRecidEqualTo(Integer value) {
			addCriterion("RecID =", value, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidNotEqualTo(Integer value) {
			addCriterion("RecID <>", value, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidGreaterThan(Integer value) {
			addCriterion("RecID >", value, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidGreaterThanOrEqualTo(Integer value) {
			addCriterion("RecID >=", value, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidLessThan(Integer value) {
			addCriterion("RecID <", value, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidLessThanOrEqualTo(Integer value) {
			addCriterion("RecID <=", value, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidIn(List<Integer> values) {
			addCriterion("RecID in", values, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidNotIn(List<Integer> values) {
			addCriterion("RecID not in", values, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidBetween(Integer value1, Integer value2) {
			addCriterion("RecID between", value1, value2, "recid");
			return (Criteria) this;
		}

		public Criteria andRecidNotBetween(Integer value1, Integer value2) {
			addCriterion("RecID not between", value1, value2, "recid");
			return (Criteria) this;
		}

		public Criteria andUseridIsNull() {
			addCriterion("UserID is null");
			return (Criteria) this;
		}

		public Criteria andUseridIsNotNull() {
			addCriterion("UserID is not null");
			return (Criteria) this;
		}

		public Criteria andUseridEqualTo(Integer value) {
			addCriterion("UserID =", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotEqualTo(Integer value) {
			addCriterion("UserID <>", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThan(Integer value) {
			addCriterion("UserID >", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("UserID >=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThan(Integer value) {
			addCriterion("UserID <", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridLessThanOrEqualTo(Integer value) {
			addCriterion("UserID <=", value, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridIn(List<Integer> values) {
			addCriterion("UserID in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotIn(List<Integer> values) {
			addCriterion("UserID not in", values, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridBetween(Integer value1, Integer value2) {
			addCriterion("UserID between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andUseridNotBetween(Integer value1, Integer value2) {
			addCriterion("UserID not between", value1, value2, "userid");
			return (Criteria) this;
		}

		public Criteria andFromidIsNull() {
			addCriterion("FromID is null");
			return (Criteria) this;
		}

		public Criteria andFromidIsNotNull() {
			addCriterion("FromID is not null");
			return (Criteria) this;
		}

		public Criteria andFromidEqualTo(Integer value) {
			addCriterion("FromID =", value, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidNotEqualTo(Integer value) {
			addCriterion("FromID <>", value, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidGreaterThan(Integer value) {
			addCriterion("FromID >", value, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidGreaterThanOrEqualTo(Integer value) {
			addCriterion("FromID >=", value, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidLessThan(Integer value) {
			addCriterion("FromID <", value, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidLessThanOrEqualTo(Integer value) {
			addCriterion("FromID <=", value, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidIn(List<Integer> values) {
			addCriterion("FromID in", values, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidNotIn(List<Integer> values) {
			addCriterion("FromID not in", values, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidBetween(Integer value1, Integer value2) {
			addCriterion("FromID between", value1, value2, "fromid");
			return (Criteria) this;
		}

		public Criteria andFromidNotBetween(Integer value1, Integer value2) {
			addCriterion("FromID not between", value1, value2, "fromid");
			return (Criteria) this;
		}

		public Criteria andCheckstatusIsNull() {
			addCriterion("CheckStatus is null");
			return (Criteria) this;
		}

		public Criteria andCheckstatusIsNotNull() {
			addCriterion("CheckStatus is not null");
			return (Criteria) this;
		}

		public Criteria andCheckstatusEqualTo(Integer value) {
			addCriterion("CheckStatus =", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusNotEqualTo(Integer value) {
			addCriterion("CheckStatus <>", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusGreaterThan(Integer value) {
			addCriterion("CheckStatus >", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("CheckStatus >=", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusLessThan(Integer value) {
			addCriterion("CheckStatus <", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusLessThanOrEqualTo(Integer value) {
			addCriterion("CheckStatus <=", value, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusIn(List<Integer> values) {
			addCriterion("CheckStatus in", values, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusNotIn(List<Integer> values) {
			addCriterion("CheckStatus not in", values, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusBetween(Integer value1, Integer value2) {
			addCriterion("CheckStatus between", value1, value2, "checkstatus");
			return (Criteria) this;
		}

		public Criteria andCheckstatusNotBetween(Integer value1, Integer value2) {
			addCriterion("CheckStatus not between", value1, value2,
					"checkstatus");
			return (Criteria) this;
		}

		public Criteria andDoccountIsNull() {
			addCriterion("DocCount is null");
			return (Criteria) this;
		}

		public Criteria andDoccountIsNotNull() {
			addCriterion("DocCount is not null");
			return (Criteria) this;
		}

		public Criteria andDoccountEqualTo(Integer value) {
			addCriterion("DocCount =", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountNotEqualTo(Integer value) {
			addCriterion("DocCount <>", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountGreaterThan(Integer value) {
			addCriterion("DocCount >", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountGreaterThanOrEqualTo(Integer value) {
			addCriterion("DocCount >=", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountLessThan(Integer value) {
			addCriterion("DocCount <", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountLessThanOrEqualTo(Integer value) {
			addCriterion("DocCount <=", value, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountIn(List<Integer> values) {
			addCriterion("DocCount in", values, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountNotIn(List<Integer> values) {
			addCriterion("DocCount not in", values, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountBetween(Integer value1, Integer value2) {
			addCriterion("DocCount between", value1, value2, "doccount");
			return (Criteria) this;
		}

		public Criteria andDoccountNotBetween(Integer value1, Integer value2) {
			addCriterion("DocCount not between", value1, value2, "doccount");
			return (Criteria) this;
		}

		public Criteria andDocgrpidIsNull() {
			addCriterion("DocGRPID is null");
			return (Criteria) this;
		}

		public Criteria andDocgrpidIsNotNull() {
			addCriterion("DocGRPID is not null");
			return (Criteria) this;
		}

		public Criteria andDocgrpidEqualTo(Integer value) {
			addCriterion("DocGRPID =", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidNotEqualTo(Integer value) {
			addCriterion("DocGRPID <>", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidGreaterThan(Integer value) {
			addCriterion("DocGRPID >", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidGreaterThanOrEqualTo(Integer value) {
			addCriterion("DocGRPID >=", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidLessThan(Integer value) {
			addCriterion("DocGRPID <", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidLessThanOrEqualTo(Integer value) {
			addCriterion("DocGRPID <=", value, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidIn(List<Integer> values) {
			addCriterion("DocGRPID in", values, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidNotIn(List<Integer> values) {
			addCriterion("DocGRPID not in", values, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidBetween(Integer value1, Integer value2) {
			addCriterion("DocGRPID between", value1, value2, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andDocgrpidNotBetween(Integer value1, Integer value2) {
			addCriterion("DocGRPID not between", value1, value2, "docgrpid");
			return (Criteria) this;
		}

		public Criteria andRecdateIsNull() {
			addCriterion("RecDate is null");
			return (Criteria) this;
		}

		public Criteria andRecdateIsNotNull() {
			addCriterion("RecDate is not null");
			return (Criteria) this;
		}

		public Criteria andRecdateEqualTo(Date value) {
			addCriterion("RecDate =", value, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateNotEqualTo(Date value) {
			addCriterion("RecDate <>", value, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateGreaterThan(Date value) {
			addCriterion("RecDate >", value, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateGreaterThanOrEqualTo(Date value) {
			addCriterion("RecDate >=", value, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateLessThan(Date value) {
			addCriterion("RecDate <", value, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateLessThanOrEqualTo(Date value) {
			addCriterion("RecDate <=", value, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateIn(List<Date> values) {
			addCriterion("RecDate in", values, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateNotIn(List<Date> values) {
			addCriterion("RecDate not in", values, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateBetween(Date value1, Date value2) {
			addCriterion("RecDate between", value1, value2, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdateNotBetween(Date value1, Date value2) {
			addCriterion("RecDate not between", value1, value2, "recdate");
			return (Criteria) this;
		}

		public Criteria andRecdata1IsNull() {
			addCriterion("RecData1 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata1IsNotNull() {
			addCriterion("RecData1 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata1EqualTo(String value) {
			addCriterion("RecData1 =", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1NotEqualTo(String value) {
			addCriterion("RecData1 <>", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1GreaterThan(String value) {
			addCriterion("RecData1 >", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1GreaterThanOrEqualTo(String value) {
			addCriterion("RecData1 >=", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1LessThan(String value) {
			addCriterion("RecData1 <", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1LessThanOrEqualTo(String value) {
			addCriterion("RecData1 <=", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1Like(String value) {
			addCriterion("RecData1 like", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1NotLike(String value) {
			addCriterion("RecData1 not like", value, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1In(List<String> values) {
			addCriterion("RecData1 in", values, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1NotIn(List<String> values) {
			addCriterion("RecData1 not in", values, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1Between(String value1, String value2) {
			addCriterion("RecData1 between", value1, value2, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata1NotBetween(String value1, String value2) {
			addCriterion("RecData1 not between", value1, value2, "recdata1");
			return (Criteria) this;
		}

		public Criteria andRecdata2IsNull() {
			addCriterion("RecData2 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata2IsNotNull() {
			addCriterion("RecData2 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata2EqualTo(String value) {
			addCriterion("RecData2 =", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2NotEqualTo(String value) {
			addCriterion("RecData2 <>", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2GreaterThan(String value) {
			addCriterion("RecData2 >", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2GreaterThanOrEqualTo(String value) {
			addCriterion("RecData2 >=", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2LessThan(String value) {
			addCriterion("RecData2 <", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2LessThanOrEqualTo(String value) {
			addCriterion("RecData2 <=", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2Like(String value) {
			addCriterion("RecData2 like", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2NotLike(String value) {
			addCriterion("RecData2 not like", value, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2In(List<String> values) {
			addCriterion("RecData2 in", values, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2NotIn(List<String> values) {
			addCriterion("RecData2 not in", values, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2Between(String value1, String value2) {
			addCriterion("RecData2 between", value1, value2, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata2NotBetween(String value1, String value2) {
			addCriterion("RecData2 not between", value1, value2, "recdata2");
			return (Criteria) this;
		}

		public Criteria andRecdata3IsNull() {
			addCriterion("RecData3 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata3IsNotNull() {
			addCriterion("RecData3 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata3EqualTo(String value) {
			addCriterion("RecData3 =", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3NotEqualTo(String value) {
			addCriterion("RecData3 <>", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3GreaterThan(String value) {
			addCriterion("RecData3 >", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3GreaterThanOrEqualTo(String value) {
			addCriterion("RecData3 >=", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3LessThan(String value) {
			addCriterion("RecData3 <", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3LessThanOrEqualTo(String value) {
			addCriterion("RecData3 <=", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3Like(String value) {
			addCriterion("RecData3 like", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3NotLike(String value) {
			addCriterion("RecData3 not like", value, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3In(List<String> values) {
			addCriterion("RecData3 in", values, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3NotIn(List<String> values) {
			addCriterion("RecData3 not in", values, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3Between(String value1, String value2) {
			addCriterion("RecData3 between", value1, value2, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata3NotBetween(String value1, String value2) {
			addCriterion("RecData3 not between", value1, value2, "recdata3");
			return (Criteria) this;
		}

		public Criteria andRecdata4IsNull() {
			addCriterion("RecData4 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata4IsNotNull() {
			addCriterion("RecData4 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata4EqualTo(String value) {
			addCriterion("RecData4 =", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4NotEqualTo(String value) {
			addCriterion("RecData4 <>", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4GreaterThan(String value) {
			addCriterion("RecData4 >", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4GreaterThanOrEqualTo(String value) {
			addCriterion("RecData4 >=", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4LessThan(String value) {
			addCriterion("RecData4 <", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4LessThanOrEqualTo(String value) {
			addCriterion("RecData4 <=", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4Like(String value) {
			addCriterion("RecData4 like", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4NotLike(String value) {
			addCriterion("RecData4 not like", value, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4In(List<String> values) {
			addCriterion("RecData4 in", values, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4NotIn(List<String> values) {
			addCriterion("RecData4 not in", values, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4Between(String value1, String value2) {
			addCriterion("RecData4 between", value1, value2, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata4NotBetween(String value1, String value2) {
			addCriterion("RecData4 not between", value1, value2, "recdata4");
			return (Criteria) this;
		}

		public Criteria andRecdata5IsNull() {
			addCriterion("RecData5 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata5IsNotNull() {
			addCriterion("RecData5 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata5EqualTo(String value) {
			addCriterion("RecData5 =", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5NotEqualTo(String value) {
			addCriterion("RecData5 <>", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5GreaterThan(String value) {
			addCriterion("RecData5 >", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5GreaterThanOrEqualTo(String value) {
			addCriterion("RecData5 >=", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5LessThan(String value) {
			addCriterion("RecData5 <", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5LessThanOrEqualTo(String value) {
			addCriterion("RecData5 <=", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5Like(String value) {
			addCriterion("RecData5 like", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5NotLike(String value) {
			addCriterion("RecData5 not like", value, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5In(List<String> values) {
			addCriterion("RecData5 in", values, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5NotIn(List<String> values) {
			addCriterion("RecData5 not in", values, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5Between(String value1, String value2) {
			addCriterion("RecData5 between", value1, value2, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata5NotBetween(String value1, String value2) {
			addCriterion("RecData5 not between", value1, value2, "recdata5");
			return (Criteria) this;
		}

		public Criteria andRecdata6IsNull() {
			addCriterion("RecData6 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata6IsNotNull() {
			addCriterion("RecData6 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata6EqualTo(String value) {
			addCriterion("RecData6 =", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6NotEqualTo(String value) {
			addCriterion("RecData6 <>", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6GreaterThan(String value) {
			addCriterion("RecData6 >", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6GreaterThanOrEqualTo(String value) {
			addCriterion("RecData6 >=", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6LessThan(String value) {
			addCriterion("RecData6 <", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6LessThanOrEqualTo(String value) {
			addCriterion("RecData6 <=", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6Like(String value) {
			addCriterion("RecData6 like", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6NotLike(String value) {
			addCriterion("RecData6 not like", value, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6In(List<String> values) {
			addCriterion("RecData6 in", values, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6NotIn(List<String> values) {
			addCriterion("RecData6 not in", values, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6Between(String value1, String value2) {
			addCriterion("RecData6 between", value1, value2, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata6NotBetween(String value1, String value2) {
			addCriterion("RecData6 not between", value1, value2, "recdata6");
			return (Criteria) this;
		}

		public Criteria andRecdata7IsNull() {
			addCriterion("RecData7 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata7IsNotNull() {
			addCriterion("RecData7 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata7EqualTo(String value) {
			addCriterion("RecData7 =", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7NotEqualTo(String value) {
			addCriterion("RecData7 <>", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7GreaterThan(String value) {
			addCriterion("RecData7 >", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7GreaterThanOrEqualTo(String value) {
			addCriterion("RecData7 >=", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7LessThan(String value) {
			addCriterion("RecData7 <", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7LessThanOrEqualTo(String value) {
			addCriterion("RecData7 <=", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7Like(String value) {
			addCriterion("RecData7 like", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7NotLike(String value) {
			addCriterion("RecData7 not like", value, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7In(List<String> values) {
			addCriterion("RecData7 in", values, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7NotIn(List<String> values) {
			addCriterion("RecData7 not in", values, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7Between(String value1, String value2) {
			addCriterion("RecData7 between", value1, value2, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata7NotBetween(String value1, String value2) {
			addCriterion("RecData7 not between", value1, value2, "recdata7");
			return (Criteria) this;
		}

		public Criteria andRecdata8IsNull() {
			addCriterion("RecData8 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata8IsNotNull() {
			addCriterion("RecData8 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata8EqualTo(String value) {
			addCriterion("RecData8 =", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8NotEqualTo(String value) {
			addCriterion("RecData8 <>", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8GreaterThan(String value) {
			addCriterion("RecData8 >", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8GreaterThanOrEqualTo(String value) {
			addCriterion("RecData8 >=", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8LessThan(String value) {
			addCriterion("RecData8 <", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8LessThanOrEqualTo(String value) {
			addCriterion("RecData8 <=", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8Like(String value) {
			addCriterion("RecData8 like", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8NotLike(String value) {
			addCriterion("RecData8 not like", value, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8In(List<String> values) {
			addCriterion("RecData8 in", values, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8NotIn(List<String> values) {
			addCriterion("RecData8 not in", values, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8Between(String value1, String value2) {
			addCriterion("RecData8 between", value1, value2, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata8NotBetween(String value1, String value2) {
			addCriterion("RecData8 not between", value1, value2, "recdata8");
			return (Criteria) this;
		}

		public Criteria andRecdata9IsNull() {
			addCriterion("RecData9 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata9IsNotNull() {
			addCriterion("RecData9 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata9EqualTo(String value) {
			addCriterion("RecData9 =", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9NotEqualTo(String value) {
			addCriterion("RecData9 <>", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9GreaterThan(String value) {
			addCriterion("RecData9 >", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9GreaterThanOrEqualTo(String value) {
			addCriterion("RecData9 >=", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9LessThan(String value) {
			addCriterion("RecData9 <", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9LessThanOrEqualTo(String value) {
			addCriterion("RecData9 <=", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9Like(String value) {
			addCriterion("RecData9 like", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9NotLike(String value) {
			addCriterion("RecData9 not like", value, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9In(List<String> values) {
			addCriterion("RecData9 in", values, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9NotIn(List<String> values) {
			addCriterion("RecData9 not in", values, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9Between(String value1, String value2) {
			addCriterion("RecData9 between", value1, value2, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata9NotBetween(String value1, String value2) {
			addCriterion("RecData9 not between", value1, value2, "recdata9");
			return (Criteria) this;
		}

		public Criteria andRecdata10IsNull() {
			addCriterion("RecData10 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata10IsNotNull() {
			addCriterion("RecData10 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata10EqualTo(String value) {
			addCriterion("RecData10 =", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10NotEqualTo(String value) {
			addCriterion("RecData10 <>", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10GreaterThan(String value) {
			addCriterion("RecData10 >", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10GreaterThanOrEqualTo(String value) {
			addCriterion("RecData10 >=", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10LessThan(String value) {
			addCriterion("RecData10 <", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10LessThanOrEqualTo(String value) {
			addCriterion("RecData10 <=", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10Like(String value) {
			addCriterion("RecData10 like", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10NotLike(String value) {
			addCriterion("RecData10 not like", value, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10In(List<String> values) {
			addCriterion("RecData10 in", values, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10NotIn(List<String> values) {
			addCriterion("RecData10 not in", values, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10Between(String value1, String value2) {
			addCriterion("RecData10 between", value1, value2, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata10NotBetween(String value1, String value2) {
			addCriterion("RecData10 not between", value1, value2, "recdata10");
			return (Criteria) this;
		}

		public Criteria andRecdata11IsNull() {
			addCriterion("RecData11 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata11IsNotNull() {
			addCriterion("RecData11 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata11EqualTo(String value) {
			addCriterion("RecData11 =", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11NotEqualTo(String value) {
			addCriterion("RecData11 <>", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11GreaterThan(String value) {
			addCriterion("RecData11 >", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11GreaterThanOrEqualTo(String value) {
			addCriterion("RecData11 >=", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11LessThan(String value) {
			addCriterion("RecData11 <", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11LessThanOrEqualTo(String value) {
			addCriterion("RecData11 <=", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11Like(String value) {
			addCriterion("RecData11 like", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11NotLike(String value) {
			addCriterion("RecData11 not like", value, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11In(List<String> values) {
			addCriterion("RecData11 in", values, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11NotIn(List<String> values) {
			addCriterion("RecData11 not in", values, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11Between(String value1, String value2) {
			addCriterion("RecData11 between", value1, value2, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata11NotBetween(String value1, String value2) {
			addCriterion("RecData11 not between", value1, value2, "recdata11");
			return (Criteria) this;
		}

		public Criteria andRecdata12IsNull() {
			addCriterion("RecData12 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata12IsNotNull() {
			addCriterion("RecData12 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata12EqualTo(String value) {
			addCriterion("RecData12 =", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12NotEqualTo(String value) {
			addCriterion("RecData12 <>", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12GreaterThan(String value) {
			addCriterion("RecData12 >", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12GreaterThanOrEqualTo(String value) {
			addCriterion("RecData12 >=", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12LessThan(String value) {
			addCriterion("RecData12 <", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12LessThanOrEqualTo(String value) {
			addCriterion("RecData12 <=", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12Like(String value) {
			addCriterion("RecData12 like", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12NotLike(String value) {
			addCriterion("RecData12 not like", value, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12In(List<String> values) {
			addCriterion("RecData12 in", values, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12NotIn(List<String> values) {
			addCriterion("RecData12 not in", values, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12Between(String value1, String value2) {
			addCriterion("RecData12 between", value1, value2, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata12NotBetween(String value1, String value2) {
			addCriterion("RecData12 not between", value1, value2, "recdata12");
			return (Criteria) this;
		}

		public Criteria andRecdata13IsNull() {
			addCriterion("RecData13 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata13IsNotNull() {
			addCriterion("RecData13 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata13EqualTo(String value) {
			addCriterion("RecData13 =", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13NotEqualTo(String value) {
			addCriterion("RecData13 <>", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13GreaterThan(String value) {
			addCriterion("RecData13 >", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13GreaterThanOrEqualTo(String value) {
			addCriterion("RecData13 >=", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13LessThan(String value) {
			addCriterion("RecData13 <", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13LessThanOrEqualTo(String value) {
			addCriterion("RecData13 <=", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13Like(String value) {
			addCriterion("RecData13 like", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13NotLike(String value) {
			addCriterion("RecData13 not like", value, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13In(List<String> values) {
			addCriterion("RecData13 in", values, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13NotIn(List<String> values) {
			addCriterion("RecData13 not in", values, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13Between(String value1, String value2) {
			addCriterion("RecData13 between", value1, value2, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata13NotBetween(String value1, String value2) {
			addCriterion("RecData13 not between", value1, value2, "recdata13");
			return (Criteria) this;
		}

		public Criteria andRecdata14IsNull() {
			addCriterion("RecData14 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata14IsNotNull() {
			addCriterion("RecData14 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata14EqualTo(String value) {
			addCriterion("RecData14 =", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14NotEqualTo(String value) {
			addCriterion("RecData14 <>", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14GreaterThan(String value) {
			addCriterion("RecData14 >", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14GreaterThanOrEqualTo(String value) {
			addCriterion("RecData14 >=", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14LessThan(String value) {
			addCriterion("RecData14 <", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14LessThanOrEqualTo(String value) {
			addCriterion("RecData14 <=", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14Like(String value) {
			addCriterion("RecData14 like", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14NotLike(String value) {
			addCriterion("RecData14 not like", value, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14In(List<String> values) {
			addCriterion("RecData14 in", values, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14NotIn(List<String> values) {
			addCriterion("RecData14 not in", values, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14Between(String value1, String value2) {
			addCriterion("RecData14 between", value1, value2, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata14NotBetween(String value1, String value2) {
			addCriterion("RecData14 not between", value1, value2, "recdata14");
			return (Criteria) this;
		}

		public Criteria andRecdata15IsNull() {
			addCriterion("RecData15 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata15IsNotNull() {
			addCriterion("RecData15 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata15EqualTo(String value) {
			addCriterion("RecData15 =", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15NotEqualTo(String value) {
			addCriterion("RecData15 <>", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15GreaterThan(String value) {
			addCriterion("RecData15 >", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15GreaterThanOrEqualTo(String value) {
			addCriterion("RecData15 >=", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15LessThan(String value) {
			addCriterion("RecData15 <", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15LessThanOrEqualTo(String value) {
			addCriterion("RecData15 <=", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15Like(String value) {
			addCriterion("RecData15 like", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15NotLike(String value) {
			addCriterion("RecData15 not like", value, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15In(List<String> values) {
			addCriterion("RecData15 in", values, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15NotIn(List<String> values) {
			addCriterion("RecData15 not in", values, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15Between(String value1, String value2) {
			addCriterion("RecData15 between", value1, value2, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata15NotBetween(String value1, String value2) {
			addCriterion("RecData15 not between", value1, value2, "recdata15");
			return (Criteria) this;
		}

		public Criteria andRecdata16IsNull() {
			addCriterion("RecData16 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata16IsNotNull() {
			addCriterion("RecData16 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata16EqualTo(String value) {
			addCriterion("RecData16 =", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16NotEqualTo(String value) {
			addCriterion("RecData16 <>", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16GreaterThan(String value) {
			addCriterion("RecData16 >", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16GreaterThanOrEqualTo(String value) {
			addCriterion("RecData16 >=", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16LessThan(String value) {
			addCriterion("RecData16 <", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16LessThanOrEqualTo(String value) {
			addCriterion("RecData16 <=", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16Like(String value) {
			addCriterion("RecData16 like", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16NotLike(String value) {
			addCriterion("RecData16 not like", value, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16In(List<String> values) {
			addCriterion("RecData16 in", values, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16NotIn(List<String> values) {
			addCriterion("RecData16 not in", values, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16Between(String value1, String value2) {
			addCriterion("RecData16 between", value1, value2, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata16NotBetween(String value1, String value2) {
			addCriterion("RecData16 not between", value1, value2, "recdata16");
			return (Criteria) this;
		}

		public Criteria andRecdata17IsNull() {
			addCriterion("RecData17 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata17IsNotNull() {
			addCriterion("RecData17 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata17EqualTo(String value) {
			addCriterion("RecData17 =", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17NotEqualTo(String value) {
			addCriterion("RecData17 <>", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17GreaterThan(String value) {
			addCriterion("RecData17 >", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17GreaterThanOrEqualTo(String value) {
			addCriterion("RecData17 >=", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17LessThan(String value) {
			addCriterion("RecData17 <", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17LessThanOrEqualTo(String value) {
			addCriterion("RecData17 <=", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17Like(String value) {
			addCriterion("RecData17 like", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17NotLike(String value) {
			addCriterion("RecData17 not like", value, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17In(List<String> values) {
			addCriterion("RecData17 in", values, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17NotIn(List<String> values) {
			addCriterion("RecData17 not in", values, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17Between(String value1, String value2) {
			addCriterion("RecData17 between", value1, value2, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata17NotBetween(String value1, String value2) {
			addCriterion("RecData17 not between", value1, value2, "recdata17");
			return (Criteria) this;
		}

		public Criteria andRecdata18IsNull() {
			addCriterion("RecData18 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata18IsNotNull() {
			addCriterion("RecData18 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata18EqualTo(String value) {
			addCriterion("RecData18 =", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18NotEqualTo(String value) {
			addCriterion("RecData18 <>", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18GreaterThan(String value) {
			addCriterion("RecData18 >", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18GreaterThanOrEqualTo(String value) {
			addCriterion("RecData18 >=", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18LessThan(String value) {
			addCriterion("RecData18 <", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18LessThanOrEqualTo(String value) {
			addCriterion("RecData18 <=", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18Like(String value) {
			addCriterion("RecData18 like", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18NotLike(String value) {
			addCriterion("RecData18 not like", value, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18In(List<String> values) {
			addCriterion("RecData18 in", values, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18NotIn(List<String> values) {
			addCriterion("RecData18 not in", values, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18Between(String value1, String value2) {
			addCriterion("RecData18 between", value1, value2, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata18NotBetween(String value1, String value2) {
			addCriterion("RecData18 not between", value1, value2, "recdata18");
			return (Criteria) this;
		}

		public Criteria andRecdata19IsNull() {
			addCriterion("RecData19 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata19IsNotNull() {
			addCriterion("RecData19 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata19EqualTo(String value) {
			addCriterion("RecData19 =", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19NotEqualTo(String value) {
			addCriterion("RecData19 <>", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19GreaterThan(String value) {
			addCriterion("RecData19 >", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19GreaterThanOrEqualTo(String value) {
			addCriterion("RecData19 >=", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19LessThan(String value) {
			addCriterion("RecData19 <", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19LessThanOrEqualTo(String value) {
			addCriterion("RecData19 <=", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19Like(String value) {
			addCriterion("RecData19 like", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19NotLike(String value) {
			addCriterion("RecData19 not like", value, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19In(List<String> values) {
			addCriterion("RecData19 in", values, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19NotIn(List<String> values) {
			addCriterion("RecData19 not in", values, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19Between(String value1, String value2) {
			addCriterion("RecData19 between", value1, value2, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata19NotBetween(String value1, String value2) {
			addCriterion("RecData19 not between", value1, value2, "recdata19");
			return (Criteria) this;
		}

		public Criteria andRecdata20IsNull() {
			addCriterion("RecData20 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata20IsNotNull() {
			addCriterion("RecData20 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata20EqualTo(String value) {
			addCriterion("RecData20 =", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20NotEqualTo(String value) {
			addCriterion("RecData20 <>", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20GreaterThan(String value) {
			addCriterion("RecData20 >", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20GreaterThanOrEqualTo(String value) {
			addCriterion("RecData20 >=", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20LessThan(String value) {
			addCriterion("RecData20 <", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20LessThanOrEqualTo(String value) {
			addCriterion("RecData20 <=", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20Like(String value) {
			addCriterion("RecData20 like", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20NotLike(String value) {
			addCriterion("RecData20 not like", value, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20In(List<String> values) {
			addCriterion("RecData20 in", values, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20NotIn(List<String> values) {
			addCriterion("RecData20 not in", values, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20Between(String value1, String value2) {
			addCriterion("RecData20 between", value1, value2, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata20NotBetween(String value1, String value2) {
			addCriterion("RecData20 not between", value1, value2, "recdata20");
			return (Criteria) this;
		}

		public Criteria andRecdata21IsNull() {
			addCriterion("RecData21 is null");
			return (Criteria) this;
		}

		public Criteria andRecdata21IsNotNull() {
			addCriterion("RecData21 is not null");
			return (Criteria) this;
		}

		public Criteria andRecdata21EqualTo(String value) {
			addCriterion("RecData21 =", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21NotEqualTo(String value) {
			addCriterion("RecData21 <>", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21GreaterThan(String value) {
			addCriterion("RecData21 >", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21GreaterThanOrEqualTo(String value) {
			addCriterion("RecData21 >=", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21LessThan(String value) {
			addCriterion("RecData21 <", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21LessThanOrEqualTo(String value) {
			addCriterion("RecData21 <=", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21Like(String value) {
			addCriterion("RecData21 like", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21NotLike(String value) {
			addCriterion("RecData21 not like", value, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21In(List<String> values) {
			addCriterion("RecData21 in", values, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21NotIn(List<String> values) {
			addCriterion("RecData21 not in", values, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21Between(String value1, String value2) {
			addCriterion("RecData21 between", value1, value2, "recdata21");
			return (Criteria) this;
		}

		public Criteria andRecdata21NotBetween(String value1, String value2) {
			addCriterion("RecData21 not between", value1, value2, "recdata21");
			return (Criteria) this;
		}

		public Criteria andHossecidIsNull() {
			addCriterion("HosSecID is null");
			return (Criteria) this;
		}

		public Criteria andHossecidIsNotNull() {
			addCriterion("HosSecID is not null");
			return (Criteria) this;
		}

		public Criteria andHossecidEqualTo(Integer value) {
			addCriterion("HosSecID =", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidNotEqualTo(Integer value) {
			addCriterion("HosSecID <>", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidGreaterThan(Integer value) {
			addCriterion("HosSecID >", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidGreaterThanOrEqualTo(Integer value) {
			addCriterion("HosSecID >=", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidLessThan(Integer value) {
			addCriterion("HosSecID <", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidLessThanOrEqualTo(Integer value) {
			addCriterion("HosSecID <=", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidIn(List<Integer> values) {
			addCriterion("HosSecID in", values, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidNotIn(List<Integer> values) {
			addCriterion("HosSecID not in", values, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidBetween(Integer value1, Integer value2) {
			addCriterion("HosSecID between", value1, value2, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidNotBetween(Integer value1, Integer value2) {
			addCriterion("HosSecID not between", value1, value2, "hossecid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.Rec_OperateSkill
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.Rec_OperateSkill
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 30 09:32:58 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}