package com.pinde.res.model.njmu.mo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserrealcyclesecExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public UserrealcyclesecExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andRuseridIsNull() {
			addCriterion("RUserID is null");
			return (Criteria) this;
		}

		public Criteria andRuseridIsNotNull() {
			addCriterion("RUserID is not null");
			return (Criteria) this;
		}

		public Criteria andRuseridEqualTo(Integer value) {
			addCriterion("RUserID =", value, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridNotEqualTo(Integer value) {
			addCriterion("RUserID <>", value, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridGreaterThan(Integer value) {
			addCriterion("RUserID >", value, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("RUserID >=", value, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridLessThan(Integer value) {
			addCriterion("RUserID <", value, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridLessThanOrEqualTo(Integer value) {
			addCriterion("RUserID <=", value, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridIn(List<Integer> values) {
			addCriterion("RUserID in", values, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridNotIn(List<Integer> values) {
			addCriterion("RUserID not in", values, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridBetween(Integer value1, Integer value2) {
			addCriterion("RUserID between", value1, value2, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRuseridNotBetween(Integer value1, Integer value2) {
			addCriterion("RUserID not between", value1, value2, "ruserid");
			return (Criteria) this;
		}

		public Criteria andRstarttimeIsNull() {
			addCriterion("RStartTime is null");
			return (Criteria) this;
		}

		public Criteria andRstarttimeIsNotNull() {
			addCriterion("RStartTime is not null");
			return (Criteria) this;
		}

		public Criteria andRstarttimeEqualTo(Date value) {
			addCriterion("RStartTime =", value, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeNotEqualTo(Date value) {
			addCriterion("RStartTime <>", value, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeGreaterThan(Date value) {
			addCriterion("RStartTime >", value, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeGreaterThanOrEqualTo(Date value) {
			addCriterion("RStartTime >=", value, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeLessThan(Date value) {
			addCriterion("RStartTime <", value, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeLessThanOrEqualTo(Date value) {
			addCriterion("RStartTime <=", value, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeIn(List<Date> values) {
			addCriterion("RStartTime in", values, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeNotIn(List<Date> values) {
			addCriterion("RStartTime not in", values, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeBetween(Date value1, Date value2) {
			addCriterion("RStartTime between", value1, value2, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRstarttimeNotBetween(Date value1, Date value2) {
			addCriterion("RStartTime not between", value1, value2, "rstarttime");
			return (Criteria) this;
		}

		public Criteria andRendtimeIsNull() {
			addCriterion("REndTime is null");
			return (Criteria) this;
		}

		public Criteria andRendtimeIsNotNull() {
			addCriterion("REndTime is not null");
			return (Criteria) this;
		}

		public Criteria andRendtimeEqualTo(Date value) {
			addCriterion("REndTime =", value, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeNotEqualTo(Date value) {
			addCriterion("REndTime <>", value, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeGreaterThan(Date value) {
			addCriterion("REndTime >", value, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("REndTime >=", value, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeLessThan(Date value) {
			addCriterion("REndTime <", value, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeLessThanOrEqualTo(Date value) {
			addCriterion("REndTime <=", value, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeIn(List<Date> values) {
			addCriterion("REndTime in", values, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeNotIn(List<Date> values) {
			addCriterion("REndTime not in", values, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeBetween(Date value1, Date value2) {
			addCriterion("REndTime between", value1, value2, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRendtimeNotBetween(Date value1, Date value2) {
			addCriterion("REndTime not between", value1, value2, "rendtime");
			return (Criteria) this;
		}

		public Criteria andRcysecidIsNull() {
			addCriterion("RCySecID is null");
			return (Criteria) this;
		}

		public Criteria andRcysecidIsNotNull() {
			addCriterion("RCySecID is not null");
			return (Criteria) this;
		}

		public Criteria andRcysecidEqualTo(Integer value) {
			addCriterion("RCySecID =", value, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidNotEqualTo(Integer value) {
			addCriterion("RCySecID <>", value, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidGreaterThan(Integer value) {
			addCriterion("RCySecID >", value, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidGreaterThanOrEqualTo(Integer value) {
			addCriterion("RCySecID >=", value, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidLessThan(Integer value) {
			addCriterion("RCySecID <", value, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidLessThanOrEqualTo(Integer value) {
			addCriterion("RCySecID <=", value, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidIn(List<Integer> values) {
			addCriterion("RCySecID in", values, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidNotIn(List<Integer> values) {
			addCriterion("RCySecID not in", values, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidBetween(Integer value1, Integer value2) {
			addCriterion("RCySecID between", value1, value2, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRcysecidNotBetween(Integer value1, Integer value2) {
			addCriterion("RCySecID not between", value1, value2, "rcysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidIsNull() {
			addCriterion("RHosCySecID is null");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidIsNotNull() {
			addCriterion("RHosCySecID is not null");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidEqualTo(Integer value) {
			addCriterion("RHosCySecID =", value, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidNotEqualTo(Integer value) {
			addCriterion("RHosCySecID <>", value, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidGreaterThan(Integer value) {
			addCriterion("RHosCySecID >", value, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidGreaterThanOrEqualTo(Integer value) {
			addCriterion("RHosCySecID >=", value, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidLessThan(Integer value) {
			addCriterion("RHosCySecID <", value, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidLessThanOrEqualTo(Integer value) {
			addCriterion("RHosCySecID <=", value, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidIn(List<Integer> values) {
			addCriterion("RHosCySecID in", values, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidNotIn(List<Integer> values) {
			addCriterion("RHosCySecID not in", values, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidBetween(Integer value1, Integer value2) {
			addCriterion("RHosCySecID between", value1, value2, "rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRhoscysecidNotBetween(Integer value1, Integer value2) {
			addCriterion("RHosCySecID not between", value1, value2,
					"rhoscysecid");
			return (Criteria) this;
		}

		public Criteria andRucsidIsNull() {
			addCriterion("RUCSID is null");
			return (Criteria) this;
		}

		public Criteria andRucsidIsNotNull() {
			addCriterion("RUCSID is not null");
			return (Criteria) this;
		}

		public Criteria andRucsidEqualTo(Integer value) {
			addCriterion("RUCSID =", value, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidNotEqualTo(Integer value) {
			addCriterion("RUCSID <>", value, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidGreaterThan(Integer value) {
			addCriterion("RUCSID >", value, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidGreaterThanOrEqualTo(Integer value) {
			addCriterion("RUCSID >=", value, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidLessThan(Integer value) {
			addCriterion("RUCSID <", value, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidLessThanOrEqualTo(Integer value) {
			addCriterion("RUCSID <=", value, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidIn(List<Integer> values) {
			addCriterion("RUCSID in", values, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidNotIn(List<Integer> values) {
			addCriterion("RUCSID not in", values, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidBetween(Integer value1, Integer value2) {
			addCriterion("RUCSID between", value1, value2, "rucsid");
			return (Criteria) this;
		}

		public Criteria andRucsidNotBetween(Integer value1, Integer value2) {
			addCriterion("RUCSID not between", value1, value2, "rucsid");
			return (Criteria) this;
		}

		public Criteria andHisstateIsNull() {
			addCriterion("HisState is null");
			return (Criteria) this;
		}

		public Criteria andHisstateIsNotNull() {
			addCriterion("HisState is not null");
			return (Criteria) this;
		}

		public Criteria andHisstateEqualTo(Integer value) {
			addCriterion("HisState =", value, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateNotEqualTo(Integer value) {
			addCriterion("HisState <>", value, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateGreaterThan(Integer value) {
			addCriterion("HisState >", value, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateGreaterThanOrEqualTo(Integer value) {
			addCriterion("HisState >=", value, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateLessThan(Integer value) {
			addCriterion("HisState <", value, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateLessThanOrEqualTo(Integer value) {
			addCriterion("HisState <=", value, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateIn(List<Integer> values) {
			addCriterion("HisState in", values, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateNotIn(List<Integer> values) {
			addCriterion("HisState not in", values, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateBetween(Integer value1, Integer value2) {
			addCriterion("HisState between", value1, value2, "hisstate");
			return (Criteria) this;
		}

		public Criteria andHisstateNotBetween(Integer value1, Integer value2) {
			addCriterion("HisState not between", value1, value2, "hisstate");
			return (Criteria) this;
		}

		public Criteria andLockstateIsNull() {
			addCriterion("LockState is null");
			return (Criteria) this;
		}

		public Criteria andLockstateIsNotNull() {
			addCriterion("LockState is not null");
			return (Criteria) this;
		}

		public Criteria andLockstateEqualTo(Integer value) {
			addCriterion("LockState =", value, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateNotEqualTo(Integer value) {
			addCriterion("LockState <>", value, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateGreaterThan(Integer value) {
			addCriterion("LockState >", value, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateGreaterThanOrEqualTo(Integer value) {
			addCriterion("LockState >=", value, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateLessThan(Integer value) {
			addCriterion("LockState <", value, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateLessThanOrEqualTo(Integer value) {
			addCriterion("LockState <=", value, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateIn(List<Integer> values) {
			addCriterion("LockState in", values, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateNotIn(List<Integer> values) {
			addCriterion("LockState not in", values, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateBetween(Integer value1, Integer value2) {
			addCriterion("LockState between", value1, value2, "lockstate");
			return (Criteria) this;
		}

		public Criteria andLockstateNotBetween(Integer value1, Integer value2) {
			addCriterion("LockState not between", value1, value2, "lockstate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.UserRealCycleSec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.UserRealCycleSec
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 14 11:10:30 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}