package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

public class Usersectionmanager extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserSectionManager.ID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserSectionManager.StudentID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer studentid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserSectionManager.SectionManagerID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer sectionmanagerid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserSectionManager.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer hossecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserSectionManager.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer ucsid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserSectionManager.ID
	 * @return  the value of dbo.UserSectionManager.ID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserSectionManager.ID
	 * @param id  the value for dbo.UserSectionManager.ID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserSectionManager.StudentID
	 * @return  the value of dbo.UserSectionManager.StudentID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getStudentid() {
		return studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserSectionManager.StudentID
	 * @param studentid  the value for dbo.UserSectionManager.StudentID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setStudentid(Integer studentid) {
		this.studentid = studentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserSectionManager.SectionManagerID
	 * @return  the value of dbo.UserSectionManager.SectionManagerID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getSectionmanagerid() {
		return sectionmanagerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserSectionManager.SectionManagerID
	 * @param sectionmanagerid  the value for dbo.UserSectionManager.SectionManagerID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSectionmanagerid(Integer sectionmanagerid) {
		this.sectionmanagerid = sectionmanagerid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserSectionManager.HosSecID
	 * @return  the value of dbo.UserSectionManager.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getHossecid() {
		return hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserSectionManager.HosSecID
	 * @param hossecid  the value for dbo.UserSectionManager.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setHossecid(Integer hossecid) {
		this.hossecid = hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserSectionManager.UCSID
	 * @return  the value of dbo.UserSectionManager.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUcsid() {
		return ucsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserSectionManager.UCSID
	 * @param ucsid  the value for dbo.UserSectionManager.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUcsid(Integer ucsid) {
		this.ucsid = ucsid;
	}
}