package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;
import java.util.Date;

public class Userinfo extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer userid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.UserName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.PassWord
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.TrueName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String truename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.WorkSpace
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String workspace;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.CardID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String cardid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Sex
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Boolean sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Duty
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String duty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.SectionID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer sectionid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.RoleIDs
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String roleids;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.SchoolID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer schoolid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.TeacherID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer teacherid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.DegreeID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer degreeid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.SpecialtyID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer specialtyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.GraduateTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date graduatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Email
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.MobileTel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String mobiletel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Tel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.CreateTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.LastEnterTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date lastentertime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.StartYear
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String startyear;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.IsComplete
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Boolean iscomplete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.IsAdmin
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Boolean isadmin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.FLability
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer flability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Comability
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer comability;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.DipState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer dipstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.DipTakeTo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer diptaketo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.PersonSpecialtyID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String personspecialtyid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.DiplomaNum
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String diplomanum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.OverTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date overtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.TtpName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String ttpname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.HosID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String hosid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.RYSJ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date rysj;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.XNJB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String xnjb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.PYNX
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String pynx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.JYZSBH
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String jyzsbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.SZKS
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer szks;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.BZPX
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer bzpx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.CSNY
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String csny;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Marry
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String marry;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.MZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer mz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.ZZMM
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer zzmm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.JKZK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer jkzk;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.JWBS
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String jwbs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.xueli
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer xueli;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.ISFresh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String isfresh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Fllevel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer fllevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.YB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String yb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.zyzbh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String zyzbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.zydd
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String zydd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.zyfw
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String zyfw;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.byzsbh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String byzsbh;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.syd
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String syd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.lcjnkhfs
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String lcjnkhfs;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.JSLB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String jslb;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.ZYYSZGZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String zyyszgz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.getDateOfZGZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date getdateofzgz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.ZYYSZCZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String zyyszcz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.areaOfZY
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String areaofzy;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.DocTemp
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String doctemp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.IsUser
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer isuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.Tec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer tec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.No
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String no;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.workNo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String workno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.workLevel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer worklevel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.WorkCardNo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String workcardno;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.XWZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String xwzurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.ZYYSZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String zyyszurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.GPHGZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String gphgzurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.YSZGUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String yszgurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserInfo.OtherUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String otherurl;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.UserID
	 * @return  the value of dbo.UserInfo.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUserid() {
		return userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.UserID
	 * @param userid  the value for dbo.UserInfo.UserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.UserName
	 * @return  the value of dbo.UserInfo.UserName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.UserName
	 * @param username  the value for dbo.UserInfo.UserName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.PassWord
	 * @return  the value of dbo.UserInfo.PassWord
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.PassWord
	 * @param password  the value for dbo.UserInfo.PassWord
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.TrueName
	 * @return  the value of dbo.UserInfo.TrueName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getTruename() {
		return truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.TrueName
	 * @param truename  the value for dbo.UserInfo.TrueName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTruename(String truename) {
		this.truename = truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.WorkSpace
	 * @return  the value of dbo.UserInfo.WorkSpace
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWorkspace() {
		return workspace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.WorkSpace
	 * @param workspace  the value for dbo.UserInfo.WorkSpace
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWorkspace(String workspace) {
		this.workspace = workspace;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.CardID
	 * @return  the value of dbo.UserInfo.CardID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCardid() {
		return cardid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.CardID
	 * @param cardid  the value for dbo.UserInfo.CardID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCardid(String cardid) {
		this.cardid = cardid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Sex
	 * @return  the value of dbo.UserInfo.Sex
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Boolean getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Sex
	 * @param sex  the value for dbo.UserInfo.Sex
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSex(Boolean sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Duty
	 * @return  the value of dbo.UserInfo.Duty
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getDuty() {
		return duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Duty
	 * @param duty  the value for dbo.UserInfo.Duty
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDuty(String duty) {
		this.duty = duty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.SectionID
	 * @return  the value of dbo.UserInfo.SectionID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getSectionid() {
		return sectionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.SectionID
	 * @param sectionid  the value for dbo.UserInfo.SectionID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSectionid(Integer sectionid) {
		this.sectionid = sectionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.RoleIDs
	 * @return  the value of dbo.UserInfo.RoleIDs
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getRoleids() {
		return roleids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.RoleIDs
	 * @param roleids  the value for dbo.UserInfo.RoleIDs
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRoleids(String roleids) {
		this.roleids = roleids;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.SchoolID
	 * @return  the value of dbo.UserInfo.SchoolID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getSchoolid() {
		return schoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.SchoolID
	 * @param schoolid  the value for dbo.UserInfo.SchoolID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSchoolid(Integer schoolid) {
		this.schoolid = schoolid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.TeacherID
	 * @return  the value of dbo.UserInfo.TeacherID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getTeacherid() {
		return teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.TeacherID
	 * @param teacherid  the value for dbo.UserInfo.TeacherID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTeacherid(Integer teacherid) {
		this.teacherid = teacherid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.DegreeID
	 * @return  the value of dbo.UserInfo.DegreeID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDegreeid() {
		return degreeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.DegreeID
	 * @param degreeid  the value for dbo.UserInfo.DegreeID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDegreeid(Integer degreeid) {
		this.degreeid = degreeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.SpecialtyID
	 * @return  the value of dbo.UserInfo.SpecialtyID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getSpecialtyid() {
		return specialtyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.SpecialtyID
	 * @param specialtyid  the value for dbo.UserInfo.SpecialtyID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSpecialtyid(Integer specialtyid) {
		this.specialtyid = specialtyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.GraduateTime
	 * @return  the value of dbo.UserInfo.GraduateTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getGraduatetime() {
		return graduatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.GraduateTime
	 * @param graduatetime  the value for dbo.UserInfo.GraduateTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setGraduatetime(Date graduatetime) {
		this.graduatetime = graduatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Email
	 * @return  the value of dbo.UserInfo.Email
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Email
	 * @param email  the value for dbo.UserInfo.Email
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.MobileTel
	 * @return  the value of dbo.UserInfo.MobileTel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getMobiletel() {
		return mobiletel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.MobileTel
	 * @param mobiletel  the value for dbo.UserInfo.MobileTel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setMobiletel(String mobiletel) {
		this.mobiletel = mobiletel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Tel
	 * @return  the value of dbo.UserInfo.Tel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Tel
	 * @param tel  the value for dbo.UserInfo.Tel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.CreateTime
	 * @return  the value of dbo.UserInfo.CreateTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.CreateTime
	 * @param createtime  the value for dbo.UserInfo.CreateTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.LastEnterTime
	 * @return  the value of dbo.UserInfo.LastEnterTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getLastentertime() {
		return lastentertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.LastEnterTime
	 * @param lastentertime  the value for dbo.UserInfo.LastEnterTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setLastentertime(Date lastentertime) {
		this.lastentertime = lastentertime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.StartYear
	 * @return  the value of dbo.UserInfo.StartYear
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getStartyear() {
		return startyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.StartYear
	 * @param startyear  the value for dbo.UserInfo.StartYear
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setStartyear(String startyear) {
		this.startyear = startyear;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.IsComplete
	 * @return  the value of dbo.UserInfo.IsComplete
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Boolean getIscomplete() {
		return iscomplete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.IsComplete
	 * @param iscomplete  the value for dbo.UserInfo.IsComplete
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setIscomplete(Boolean iscomplete) {
		this.iscomplete = iscomplete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.IsAdmin
	 * @return  the value of dbo.UserInfo.IsAdmin
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Boolean getIsadmin() {
		return isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.IsAdmin
	 * @param isadmin  the value for dbo.UserInfo.IsAdmin
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setIsadmin(Boolean isadmin) {
		this.isadmin = isadmin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.FLability
	 * @return  the value of dbo.UserInfo.FLability
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getFlability() {
		return flability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.FLability
	 * @param flability  the value for dbo.UserInfo.FLability
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setFlability(Integer flability) {
		this.flability = flability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Comability
	 * @return  the value of dbo.UserInfo.Comability
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getComability() {
		return comability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Comability
	 * @param comability  the value for dbo.UserInfo.Comability
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setComability(Integer comability) {
		this.comability = comability;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.DipState
	 * @return  the value of dbo.UserInfo.DipState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDipstate() {
		return dipstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.DipState
	 * @param dipstate  the value for dbo.UserInfo.DipState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDipstate(Integer dipstate) {
		this.dipstate = dipstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.DipTakeTo
	 * @return  the value of dbo.UserInfo.DipTakeTo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getDiptaketo() {
		return diptaketo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.DipTakeTo
	 * @param diptaketo  the value for dbo.UserInfo.DipTakeTo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDiptaketo(Integer diptaketo) {
		this.diptaketo = diptaketo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.PersonSpecialtyID
	 * @return  the value of dbo.UserInfo.PersonSpecialtyID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getPersonspecialtyid() {
		return personspecialtyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.PersonSpecialtyID
	 * @param personspecialtyid  the value for dbo.UserInfo.PersonSpecialtyID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setPersonspecialtyid(String personspecialtyid) {
		this.personspecialtyid = personspecialtyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.DiplomaNum
	 * @return  the value of dbo.UserInfo.DiplomaNum
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getDiplomanum() {
		return diplomanum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.DiplomaNum
	 * @param diplomanum  the value for dbo.UserInfo.DiplomaNum
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDiplomanum(String diplomanum) {
		this.diplomanum = diplomanum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.OverTime
	 * @return  the value of dbo.UserInfo.OverTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getOvertime() {
		return overtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.OverTime
	 * @param overtime  the value for dbo.UserInfo.OverTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOvertime(Date overtime) {
		this.overtime = overtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.TtpName
	 * @return  the value of dbo.UserInfo.TtpName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getTtpname() {
		return ttpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.TtpName
	 * @param ttpname  the value for dbo.UserInfo.TtpName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTtpname(String ttpname) {
		this.ttpname = ttpname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.HosID
	 * @return  the value of dbo.UserInfo.HosID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getHosid() {
		return hosid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.HosID
	 * @param hosid  the value for dbo.UserInfo.HosID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setHosid(String hosid) {
		this.hosid = hosid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.RYSJ
	 * @return  the value of dbo.UserInfo.RYSJ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getRysj() {
		return rysj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.RYSJ
	 * @param rysj  the value for dbo.UserInfo.RYSJ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRysj(Date rysj) {
		this.rysj = rysj;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.XNJB
	 * @return  the value of dbo.UserInfo.XNJB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getXnjb() {
		return xnjb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.XNJB
	 * @param xnjb  the value for dbo.UserInfo.XNJB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setXnjb(String xnjb) {
		this.xnjb = xnjb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.PYNX
	 * @return  the value of dbo.UserInfo.PYNX
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getPynx() {
		return pynx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.PYNX
	 * @param pynx  the value for dbo.UserInfo.PYNX
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setPynx(String pynx) {
		this.pynx = pynx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.JYZSBH
	 * @return  the value of dbo.UserInfo.JYZSBH
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getJyzsbh() {
		return jyzsbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.JYZSBH
	 * @param jyzsbh  the value for dbo.UserInfo.JYZSBH
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setJyzsbh(String jyzsbh) {
		this.jyzsbh = jyzsbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.SZKS
	 * @return  the value of dbo.UserInfo.SZKS
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getSzks() {
		return szks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.SZKS
	 * @param szks  the value for dbo.UserInfo.SZKS
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSzks(Integer szks) {
		this.szks = szks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.BZPX
	 * @return  the value of dbo.UserInfo.BZPX
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getBzpx() {
		return bzpx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.BZPX
	 * @param bzpx  the value for dbo.UserInfo.BZPX
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setBzpx(Integer bzpx) {
		this.bzpx = bzpx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.CSNY
	 * @return  the value of dbo.UserInfo.CSNY
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getCsny() {
		return csny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.CSNY
	 * @param csny  the value for dbo.UserInfo.CSNY
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setCsny(String csny) {
		this.csny = csny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Marry
	 * @return  the value of dbo.UserInfo.Marry
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getMarry() {
		return marry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Marry
	 * @param marry  the value for dbo.UserInfo.Marry
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setMarry(String marry) {
		this.marry = marry;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.MZ
	 * @return  the value of dbo.UserInfo.MZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getMz() {
		return mz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.MZ
	 * @param mz  the value for dbo.UserInfo.MZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setMz(Integer mz) {
		this.mz = mz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.ZZMM
	 * @return  the value of dbo.UserInfo.ZZMM
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getZzmm() {
		return zzmm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.ZZMM
	 * @param zzmm  the value for dbo.UserInfo.ZZMM
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZzmm(Integer zzmm) {
		this.zzmm = zzmm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.JKZK
	 * @return  the value of dbo.UserInfo.JKZK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getJkzk() {
		return jkzk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.JKZK
	 * @param jkzk  the value for dbo.UserInfo.JKZK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setJkzk(Integer jkzk) {
		this.jkzk = jkzk;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.JWBS
	 * @return  the value of dbo.UserInfo.JWBS
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getJwbs() {
		return jwbs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.JWBS
	 * @param jwbs  the value for dbo.UserInfo.JWBS
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setJwbs(String jwbs) {
		this.jwbs = jwbs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.xueli
	 * @return  the value of dbo.UserInfo.xueli
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getXueli() {
		return xueli;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.xueli
	 * @param xueli  the value for dbo.UserInfo.xueli
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setXueli(Integer xueli) {
		this.xueli = xueli;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.ISFresh
	 * @return  the value of dbo.UserInfo.ISFresh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getIsfresh() {
		return isfresh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.ISFresh
	 * @param isfresh  the value for dbo.UserInfo.ISFresh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setIsfresh(String isfresh) {
		this.isfresh = isfresh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Fllevel
	 * @return  the value of dbo.UserInfo.Fllevel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getFllevel() {
		return fllevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Fllevel
	 * @param fllevel  the value for dbo.UserInfo.Fllevel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setFllevel(Integer fllevel) {
		this.fllevel = fllevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.YB
	 * @return  the value of dbo.UserInfo.YB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getYb() {
		return yb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.YB
	 * @param yb  the value for dbo.UserInfo.YB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setYb(String yb) {
		this.yb = yb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.zyzbh
	 * @return  the value of dbo.UserInfo.zyzbh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getZyzbh() {
		return zyzbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.zyzbh
	 * @param zyzbh  the value for dbo.UserInfo.zyzbh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZyzbh(String zyzbh) {
		this.zyzbh = zyzbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.zydd
	 * @return  the value of dbo.UserInfo.zydd
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getZydd() {
		return zydd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.zydd
	 * @param zydd  the value for dbo.UserInfo.zydd
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZydd(String zydd) {
		this.zydd = zydd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.zyfw
	 * @return  the value of dbo.UserInfo.zyfw
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getZyfw() {
		return zyfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.zyfw
	 * @param zyfw  the value for dbo.UserInfo.zyfw
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZyfw(String zyfw) {
		this.zyfw = zyfw;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.byzsbh
	 * @return  the value of dbo.UserInfo.byzsbh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getByzsbh() {
		return byzsbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.byzsbh
	 * @param byzsbh  the value for dbo.UserInfo.byzsbh
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setByzsbh(String byzsbh) {
		this.byzsbh = byzsbh;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.syd
	 * @return  the value of dbo.UserInfo.syd
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getSyd() {
		return syd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.syd
	 * @param syd  the value for dbo.UserInfo.syd
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setSyd(String syd) {
		this.syd = syd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.lcjnkhfs
	 * @return  the value of dbo.UserInfo.lcjnkhfs
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getLcjnkhfs() {
		return lcjnkhfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.lcjnkhfs
	 * @param lcjnkhfs  the value for dbo.UserInfo.lcjnkhfs
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setLcjnkhfs(String lcjnkhfs) {
		this.lcjnkhfs = lcjnkhfs;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.JSLB
	 * @return  the value of dbo.UserInfo.JSLB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getJslb() {
		return jslb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.JSLB
	 * @param jslb  the value for dbo.UserInfo.JSLB
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setJslb(String jslb) {
		this.jslb = jslb;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.ZYYSZGZ
	 * @return  the value of dbo.UserInfo.ZYYSZGZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getZyyszgz() {
		return zyyszgz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.ZYYSZGZ
	 * @param zyyszgz  the value for dbo.UserInfo.ZYYSZGZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZyyszgz(String zyyszgz) {
		this.zyyszgz = zyyszgz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.getDateOfZGZ
	 * @return  the value of dbo.UserInfo.getDateOfZGZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getGetdateofzgz() {
		return getdateofzgz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.getDateOfZGZ
	 * @param getdateofzgz  the value for dbo.UserInfo.getDateOfZGZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setGetdateofzgz(Date getdateofzgz) {
		this.getdateofzgz = getdateofzgz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.ZYYSZCZ
	 * @return  the value of dbo.UserInfo.ZYYSZCZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getZyyszcz() {
		return zyyszcz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.ZYYSZCZ
	 * @param zyyszcz  the value for dbo.UserInfo.ZYYSZCZ
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZyyszcz(String zyyszcz) {
		this.zyyszcz = zyyszcz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.areaOfZY
	 * @return  the value of dbo.UserInfo.areaOfZY
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getAreaofzy() {
		return areaofzy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.areaOfZY
	 * @param areaofzy  the value for dbo.UserInfo.areaOfZY
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setAreaofzy(String areaofzy) {
		this.areaofzy = areaofzy;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.DocTemp
	 * @return  the value of dbo.UserInfo.DocTemp
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getDoctemp() {
		return doctemp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.DocTemp
	 * @param doctemp  the value for dbo.UserInfo.DocTemp
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDoctemp(String doctemp) {
		this.doctemp = doctemp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.IsUser
	 * @return  the value of dbo.UserInfo.IsUser
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getIsuser() {
		return isuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.IsUser
	 * @param isuser  the value for dbo.UserInfo.IsUser
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setIsuser(Integer isuser) {
		this.isuser = isuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.Tec
	 * @return  the value of dbo.UserInfo.Tec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getTec() {
		return tec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.Tec
	 * @param tec  the value for dbo.UserInfo.Tec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setTec(Integer tec) {
		this.tec = tec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.No
	 * @return  the value of dbo.UserInfo.No
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getNo() {
		return no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.No
	 * @param no  the value for dbo.UserInfo.No
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setNo(String no) {
		this.no = no;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.workNo
	 * @return  the value of dbo.UserInfo.workNo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWorkno() {
		return workno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.workNo
	 * @param workno  the value for dbo.UserInfo.workNo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWorkno(String workno) {
		this.workno = workno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.workLevel
	 * @return  the value of dbo.UserInfo.workLevel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getWorklevel() {
		return worklevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.workLevel
	 * @param worklevel  the value for dbo.UserInfo.workLevel
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWorklevel(Integer worklevel) {
		this.worklevel = worklevel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.WorkCardNo
	 * @return  the value of dbo.UserInfo.WorkCardNo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWorkcardno() {
		return workcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.WorkCardNo
	 * @param workcardno  the value for dbo.UserInfo.WorkCardNo
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWorkcardno(String workcardno) {
		this.workcardno = workcardno;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.XWZUrl
	 * @return  the value of dbo.UserInfo.XWZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getXwzurl() {
		return xwzurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.XWZUrl
	 * @param xwzurl  the value for dbo.UserInfo.XWZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setXwzurl(String xwzurl) {
		this.xwzurl = xwzurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.ZYYSZUrl
	 * @return  the value of dbo.UserInfo.ZYYSZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getZyyszurl() {
		return zyyszurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.ZYYSZUrl
	 * @param zyyszurl  the value for dbo.UserInfo.ZYYSZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setZyyszurl(String zyyszurl) {
		this.zyyszurl = zyyszurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.GPHGZUrl
	 * @return  the value of dbo.UserInfo.GPHGZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getGphgzurl() {
		return gphgzurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.GPHGZUrl
	 * @param gphgzurl  the value for dbo.UserInfo.GPHGZUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setGphgzurl(String gphgzurl) {
		this.gphgzurl = gphgzurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.YSZGUrl
	 * @return  the value of dbo.UserInfo.YSZGUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getYszgurl() {
		return yszgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.YSZGUrl
	 * @param yszgurl  the value for dbo.UserInfo.YSZGUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setYszgurl(String yszgurl) {
		this.yszgurl = yszgurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserInfo.OtherUrl
	 * @return  the value of dbo.UserInfo.OtherUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOtherurl() {
		return otherurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserInfo.OtherUrl
	 * @param otherurl  the value for dbo.UserInfo.OtherUrl
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOtherurl(String otherurl) {
		this.otherurl = otherurl;
	}
}