package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

public class Userrealtec extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealTec.UserDipID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer userdipid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealTec.UserTecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String usertecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealTec.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer hossecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealTec.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer ucsid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealTec.UserDipID
	 * @return  the value of dbo.UserRealTec.UserDipID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUserdipid() {
		return userdipid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealTec.UserDipID
	 * @param userdipid  the value for dbo.UserRealTec.UserDipID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUserdipid(Integer userdipid) {
		this.userdipid = userdipid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealTec.UserTecID
	 * @return  the value of dbo.UserRealTec.UserTecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getUsertecid() {
		return usertecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealTec.UserTecID
	 * @param usertecid  the value for dbo.UserRealTec.UserTecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUsertecid(String usertecid) {
		this.usertecid = usertecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealTec.HosSecID
	 * @return  the value of dbo.UserRealTec.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getHossecid() {
		return hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealTec.HosSecID
	 * @param hossecid  the value for dbo.UserRealTec.HosSecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setHossecid(Integer hossecid) {
		this.hossecid = hossecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealTec.UCSID
	 * @return  the value of dbo.UserRealTec.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getUcsid() {
		return ucsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealTec.UCSID
	 * @param ucsid  the value for dbo.UserRealTec.UCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setUcsid(Integer ucsid) {
		this.ucsid = ucsid;
	}
}