package com.pinde.res.model.njmu.mo;

import java.util.ArrayList;
import java.util.List;

public class UserrealtecExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public UserrealtecExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUserdipidIsNull() {
			addCriterion("UserDipID is null");
			return (Criteria) this;
		}

		public Criteria andUserdipidIsNotNull() {
			addCriterion("UserDipID is not null");
			return (Criteria) this;
		}

		public Criteria andUserdipidEqualTo(Integer value) {
			addCriterion("UserDipID =", value, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidNotEqualTo(Integer value) {
			addCriterion("UserDipID <>", value, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidGreaterThan(Integer value) {
			addCriterion("UserDipID >", value, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidGreaterThanOrEqualTo(Integer value) {
			addCriterion("UserDipID >=", value, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidLessThan(Integer value) {
			addCriterion("UserDipID <", value, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidLessThanOrEqualTo(Integer value) {
			addCriterion("UserDipID <=", value, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidIn(List<Integer> values) {
			addCriterion("UserDipID in", values, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidNotIn(List<Integer> values) {
			addCriterion("UserDipID not in", values, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidBetween(Integer value1, Integer value2) {
			addCriterion("UserDipID between", value1, value2, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUserdipidNotBetween(Integer value1, Integer value2) {
			addCriterion("UserDipID not between", value1, value2, "userdipid");
			return (Criteria) this;
		}

		public Criteria andUsertecidIsNull() {
			addCriterion("UserTecID is null");
			return (Criteria) this;
		}

		public Criteria andUsertecidIsNotNull() {
			addCriterion("UserTecID is not null");
			return (Criteria) this;
		}

		public Criteria andUsertecidEqualTo(String value) {
			addCriterion("UserTecID =", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidNotEqualTo(String value) {
			addCriterion("UserTecID <>", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidGreaterThan(String value) {
			addCriterion("UserTecID >", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidGreaterThanOrEqualTo(String value) {
			addCriterion("UserTecID >=", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidLessThan(String value) {
			addCriterion("UserTecID <", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidLessThanOrEqualTo(String value) {
			addCriterion("UserTecID <=", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidLike(String value) {
			addCriterion("UserTecID like", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidNotLike(String value) {
			addCriterion("UserTecID not like", value, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidIn(List<String> values) {
			addCriterion("UserTecID in", values, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidNotIn(List<String> values) {
			addCriterion("UserTecID not in", values, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidBetween(String value1, String value2) {
			addCriterion("UserTecID between", value1, value2, "usertecid");
			return (Criteria) this;
		}

		public Criteria andUsertecidNotBetween(String value1, String value2) {
			addCriterion("UserTecID not between", value1, value2, "usertecid");
			return (Criteria) this;
		}

		public Criteria andHossecidIsNull() {
			addCriterion("HosSecID is null");
			return (Criteria) this;
		}

		public Criteria andHossecidIsNotNull() {
			addCriterion("HosSecID is not null");
			return (Criteria) this;
		}

		public Criteria andHossecidEqualTo(Integer value) {
			addCriterion("HosSecID =", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidNotEqualTo(Integer value) {
			addCriterion("HosSecID <>", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidGreaterThan(Integer value) {
			addCriterion("HosSecID >", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidGreaterThanOrEqualTo(Integer value) {
			addCriterion("HosSecID >=", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidLessThan(Integer value) {
			addCriterion("HosSecID <", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidLessThanOrEqualTo(Integer value) {
			addCriterion("HosSecID <=", value, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidIn(List<Integer> values) {
			addCriterion("HosSecID in", values, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidNotIn(List<Integer> values) {
			addCriterion("HosSecID not in", values, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidBetween(Integer value1, Integer value2) {
			addCriterion("HosSecID between", value1, value2, "hossecid");
			return (Criteria) this;
		}

		public Criteria andHossecidNotBetween(Integer value1, Integer value2) {
			addCriterion("HosSecID not between", value1, value2, "hossecid");
			return (Criteria) this;
		}

		public Criteria andUcsidIsNull() {
			addCriterion("UCSID is null");
			return (Criteria) this;
		}

		public Criteria andUcsidIsNotNull() {
			addCriterion("UCSID is not null");
			return (Criteria) this;
		}

		public Criteria andUcsidEqualTo(Integer value) {
			addCriterion("UCSID =", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidNotEqualTo(Integer value) {
			addCriterion("UCSID <>", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidGreaterThan(Integer value) {
			addCriterion("UCSID >", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidGreaterThanOrEqualTo(Integer value) {
			addCriterion("UCSID >=", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidLessThan(Integer value) {
			addCriterion("UCSID <", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidLessThanOrEqualTo(Integer value) {
			addCriterion("UCSID <=", value, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidIn(List<Integer> values) {
			addCriterion("UCSID in", values, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidNotIn(List<Integer> values) {
			addCriterion("UCSID not in", values, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidBetween(Integer value1, Integer value2) {
			addCriterion("UCSID between", value1, value2, "ucsid");
			return (Criteria) this;
		}

		public Criteria andUcsidNotBetween(Integer value1, Integer value2) {
			addCriterion("UCSID not between", value1, value2, "ucsid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.UserRealTec
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.UserRealTec
     *
     * @mbggenerated do_not_delete_during_merge Wed Jan 14 11:10:56 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}