package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

import java.util.Date;

public class Userrealcyclesec extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.RUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer ruserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.RStartTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date rstarttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.REndTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date rendtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.RCySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer rcysecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.RHosCySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer rhoscysecid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.RUCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer rucsid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.HisState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer hisstate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.UserRealCycleSec.LockState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer lockstate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.RUserID
	 * @return  the value of dbo.UserRealCycleSec.RUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getRuserid() {
		return ruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.RUserID
	 * @param ruserid  the value for dbo.UserRealCycleSec.RUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRuserid(Integer ruserid) {
		this.ruserid = ruserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.RStartTime
	 * @return  the value of dbo.UserRealCycleSec.RStartTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getRstarttime() {
		return rstarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.RStartTime
	 * @param rstarttime  the value for dbo.UserRealCycleSec.RStartTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRstarttime(Date rstarttime) {
		this.rstarttime = rstarttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.REndTime
	 * @return  the value of dbo.UserRealCycleSec.REndTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getRendtime() {
		return rendtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.REndTime
	 * @param rendtime  the value for dbo.UserRealCycleSec.REndTime
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRendtime(Date rendtime) {
		this.rendtime = rendtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.RCySecID
	 * @return  the value of dbo.UserRealCycleSec.RCySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getRcysecid() {
		return rcysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.RCySecID
	 * @param rcysecid  the value for dbo.UserRealCycleSec.RCySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRcysecid(Integer rcysecid) {
		this.rcysecid = rcysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.RHosCySecID
	 * @return  the value of dbo.UserRealCycleSec.RHosCySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getRhoscysecid() {
		return rhoscysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.RHosCySecID
	 * @param rhoscysecid  the value for dbo.UserRealCycleSec.RHosCySecID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRhoscysecid(Integer rhoscysecid) {
		this.rhoscysecid = rhoscysecid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.RUCSID
	 * @return  the value of dbo.UserRealCycleSec.RUCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getRucsid() {
		return rucsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.RUCSID
	 * @param rucsid  the value for dbo.UserRealCycleSec.RUCSID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setRucsid(Integer rucsid) {
		this.rucsid = rucsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.HisState
	 * @return  the value of dbo.UserRealCycleSec.HisState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getHisstate() {
		return hisstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.HisState
	 * @param hisstate  the value for dbo.UserRealCycleSec.HisState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setHisstate(Integer hisstate) {
		this.hisstate = hisstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.UserRealCycleSec.LockState
	 * @return  the value of dbo.UserRealCycleSec.LockState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getLockstate() {
		return lockstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.UserRealCycleSec.LockState
	 * @param lockstate  the value for dbo.UserRealCycleSec.LockState
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setLockstate(Integer lockstate) {
		this.lockstate = lockstate;
	}
}