package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;

import java.util.Date;

public class Wfwork extends MybatisObject {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_ID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer wfworkId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_DataID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkDataid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_TableName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkTablename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_TITLE
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_AWAITER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkAwaiter;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_CreateUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer wfworkCreateuserid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_CREATER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkCreater;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_HANDLER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkHandler;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_PBEGIN
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date wfworkPbegin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_ABEGIN
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Date wfworkAbegin;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_STATE
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer wfworkState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_URL
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private String wfworkUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column dbo.WFWORK.WFWORK_ROLEID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	private Integer wfworkRoleid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_ID
	 * @return  the value of dbo.WFWORK.WFWORK_ID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getWfworkId() {
		return wfworkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_ID
	 * @param wfworkId  the value for dbo.WFWORK.WFWORK_ID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkId(Integer wfworkId) {
		this.wfworkId = wfworkId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_DataID
	 * @return  the value of dbo.WFWORK.WFWORK_DataID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkDataid() {
		return wfworkDataid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_DataID
	 * @param wfworkDataid  the value for dbo.WFWORK.WFWORK_DataID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkDataid(String wfworkDataid) {
		this.wfworkDataid = wfworkDataid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_TableName
	 * @return  the value of dbo.WFWORK.WFWORK_TableName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkTablename() {
		return wfworkTablename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_TableName
	 * @param wfworkTablename  the value for dbo.WFWORK.WFWORK_TableName
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkTablename(String wfworkTablename) {
		this.wfworkTablename = wfworkTablename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_TITLE
	 * @return  the value of dbo.WFWORK.WFWORK_TITLE
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkTitle() {
		return wfworkTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_TITLE
	 * @param wfworkTitle  the value for dbo.WFWORK.WFWORK_TITLE
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkTitle(String wfworkTitle) {
		this.wfworkTitle = wfworkTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_AWAITER
	 * @return  the value of dbo.WFWORK.WFWORK_AWAITER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkAwaiter() {
		return wfworkAwaiter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_AWAITER
	 * @param wfworkAwaiter  the value for dbo.WFWORK.WFWORK_AWAITER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkAwaiter(String wfworkAwaiter) {
		this.wfworkAwaiter = wfworkAwaiter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_CreateUserID
	 * @return  the value of dbo.WFWORK.WFWORK_CreateUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getWfworkCreateuserid() {
		return wfworkCreateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_CreateUserID
	 * @param wfworkCreateuserid  the value for dbo.WFWORK.WFWORK_CreateUserID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkCreateuserid(Integer wfworkCreateuserid) {
		this.wfworkCreateuserid = wfworkCreateuserid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_CREATER
	 * @return  the value of dbo.WFWORK.WFWORK_CREATER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkCreater() {
		return wfworkCreater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_CREATER
	 * @param wfworkCreater  the value for dbo.WFWORK.WFWORK_CREATER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkCreater(String wfworkCreater) {
		this.wfworkCreater = wfworkCreater;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_HANDLER
	 * @return  the value of dbo.WFWORK.WFWORK_HANDLER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkHandler() {
		return wfworkHandler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_HANDLER
	 * @param wfworkHandler  the value for dbo.WFWORK.WFWORK_HANDLER
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkHandler(String wfworkHandler) {
		this.wfworkHandler = wfworkHandler;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_PBEGIN
	 * @return  the value of dbo.WFWORK.WFWORK_PBEGIN
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getWfworkPbegin() {
		return wfworkPbegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_PBEGIN
	 * @param wfworkPbegin  the value for dbo.WFWORK.WFWORK_PBEGIN
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkPbegin(Date wfworkPbegin) {
		this.wfworkPbegin = wfworkPbegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_ABEGIN
	 * @return  the value of dbo.WFWORK.WFWORK_ABEGIN
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Date getWfworkAbegin() {
		return wfworkAbegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_ABEGIN
	 * @param wfworkAbegin  the value for dbo.WFWORK.WFWORK_ABEGIN
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkAbegin(Date wfworkAbegin) {
		this.wfworkAbegin = wfworkAbegin;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_STATE
	 * @return  the value of dbo.WFWORK.WFWORK_STATE
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getWfworkState() {
		return wfworkState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_STATE
	 * @param wfworkState  the value for dbo.WFWORK.WFWORK_STATE
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkState(Integer wfworkState) {
		this.wfworkState = wfworkState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_URL
	 * @return  the value of dbo.WFWORK.WFWORK_URL
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getWfworkUrl() {
		return wfworkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_URL
	 * @param wfworkUrl  the value for dbo.WFWORK.WFWORK_URL
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkUrl(String wfworkUrl) {
		this.wfworkUrl = wfworkUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column dbo.WFWORK.WFWORK_ROLEID
	 * @return  the value of dbo.WFWORK.WFWORK_ROLEID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Integer getWfworkRoleid() {
		return wfworkRoleid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column dbo.WFWORK.WFWORK_ROLEID
	 * @param wfworkRoleid  the value for dbo.WFWORK.WFWORK_ROLEID
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setWfworkRoleid(Integer wfworkRoleid) {
		this.wfworkRoleid = wfworkRoleid;
	}
}