package com.pinde.res.model.njmu.mo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WfworkExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public WfworkExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andWfworkIdIsNull() {
			addCriterion("WFWORK_ID is null");
			return (Criteria) this;
		}

		public Criteria andWfworkIdIsNotNull() {
			addCriterion("WFWORK_ID is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkIdEqualTo(Integer value) {
			addCriterion("WFWORK_ID =", value, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdNotEqualTo(Integer value) {
			addCriterion("WFWORK_ID <>", value, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdGreaterThan(Integer value) {
			addCriterion("WFWORK_ID >", value, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_ID >=", value, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdLessThan(Integer value) {
			addCriterion("WFWORK_ID <", value, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdLessThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_ID <=", value, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdIn(List<Integer> values) {
			addCriterion("WFWORK_ID in", values, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdNotIn(List<Integer> values) {
			addCriterion("WFWORK_ID not in", values, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdBetween(Integer value1, Integer value2) {
			addCriterion("WFWORK_ID between", value1, value2, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkIdNotBetween(Integer value1, Integer value2) {
			addCriterion("WFWORK_ID not between", value1, value2, "wfworkId");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidIsNull() {
			addCriterion("WFWORK_DataID is null");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidIsNotNull() {
			addCriterion("WFWORK_DataID is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidEqualTo(String value) {
			addCriterion("WFWORK_DataID =", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidNotEqualTo(String value) {
			addCriterion("WFWORK_DataID <>", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidGreaterThan(String value) {
			addCriterion("WFWORK_DataID >", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_DataID >=", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidLessThan(String value) {
			addCriterion("WFWORK_DataID <", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_DataID <=", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidLike(String value) {
			addCriterion("WFWORK_DataID like", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidNotLike(String value) {
			addCriterion("WFWORK_DataID not like", value, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidIn(List<String> values) {
			addCriterion("WFWORK_DataID in", values, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidNotIn(List<String> values) {
			addCriterion("WFWORK_DataID not in", values, "wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidBetween(String value1, String value2) {
			addCriterion("WFWORK_DataID between", value1, value2,
					"wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkDataidNotBetween(String value1, String value2) {
			addCriterion("WFWORK_DataID not between", value1, value2,
					"wfworkDataid");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameIsNull() {
			addCriterion("WFWORK_TableName is null");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameIsNotNull() {
			addCriterion("WFWORK_TableName is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameEqualTo(String value) {
			addCriterion("WFWORK_TableName =", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameNotEqualTo(String value) {
			addCriterion("WFWORK_TableName <>", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameGreaterThan(String value) {
			addCriterion("WFWORK_TableName >", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_TableName >=", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameLessThan(String value) {
			addCriterion("WFWORK_TableName <", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_TableName <=", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameLike(String value) {
			addCriterion("WFWORK_TableName like", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameNotLike(String value) {
			addCriterion("WFWORK_TableName not like", value, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameIn(List<String> values) {
			addCriterion("WFWORK_TableName in", values, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameNotIn(List<String> values) {
			addCriterion("WFWORK_TableName not in", values, "wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameBetween(String value1, String value2) {
			addCriterion("WFWORK_TableName between", value1, value2,
					"wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTablenameNotBetween(String value1,
				String value2) {
			addCriterion("WFWORK_TableName not between", value1, value2,
					"wfworkTablename");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleIsNull() {
			addCriterion("WFWORK_TITLE is null");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleIsNotNull() {
			addCriterion("WFWORK_TITLE is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleEqualTo(String value) {
			addCriterion("WFWORK_TITLE =", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleNotEqualTo(String value) {
			addCriterion("WFWORK_TITLE <>", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleGreaterThan(String value) {
			addCriterion("WFWORK_TITLE >", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_TITLE >=", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleLessThan(String value) {
			addCriterion("WFWORK_TITLE <", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_TITLE <=", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleLike(String value) {
			addCriterion("WFWORK_TITLE like", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleNotLike(String value) {
			addCriterion("WFWORK_TITLE not like", value, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleIn(List<String> values) {
			addCriterion("WFWORK_TITLE in", values, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleNotIn(List<String> values) {
			addCriterion("WFWORK_TITLE not in", values, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleBetween(String value1, String value2) {
			addCriterion("WFWORK_TITLE between", value1, value2, "wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkTitleNotBetween(String value1, String value2) {
			addCriterion("WFWORK_TITLE not between", value1, value2,
					"wfworkTitle");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterIsNull() {
			addCriterion("WFWORK_AWAITER is null");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterIsNotNull() {
			addCriterion("WFWORK_AWAITER is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterEqualTo(String value) {
			addCriterion("WFWORK_AWAITER =", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterNotEqualTo(String value) {
			addCriterion("WFWORK_AWAITER <>", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterGreaterThan(String value) {
			addCriterion("WFWORK_AWAITER >", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_AWAITER >=", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterLessThan(String value) {
			addCriterion("WFWORK_AWAITER <", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_AWAITER <=", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterLike(String value) {
			addCriterion("WFWORK_AWAITER like", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterNotLike(String value) {
			addCriterion("WFWORK_AWAITER not like", value, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterIn(List<String> values) {
			addCriterion("WFWORK_AWAITER in", values, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterNotIn(List<String> values) {
			addCriterion("WFWORK_AWAITER not in", values, "wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterBetween(String value1, String value2) {
			addCriterion("WFWORK_AWAITER between", value1, value2,
					"wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkAwaiterNotBetween(String value1, String value2) {
			addCriterion("WFWORK_AWAITER not between", value1, value2,
					"wfworkAwaiter");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridIsNull() {
			addCriterion("WFWORK_CreateUserID is null");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridIsNotNull() {
			addCriterion("WFWORK_CreateUserID is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridEqualTo(Integer value) {
			addCriterion("WFWORK_CreateUserID =", value, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridNotEqualTo(Integer value) {
			addCriterion("WFWORK_CreateUserID <>", value, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridGreaterThan(Integer value) {
			addCriterion("WFWORK_CreateUserID >", value, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridGreaterThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_CreateUserID >=", value, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridLessThan(Integer value) {
			addCriterion("WFWORK_CreateUserID <", value, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridLessThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_CreateUserID <=", value, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridIn(List<Integer> values) {
			addCriterion("WFWORK_CreateUserID in", values, "wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridNotIn(List<Integer> values) {
			addCriterion("WFWORK_CreateUserID not in", values,
					"wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridBetween(Integer value1,
				Integer value2) {
			addCriterion("WFWORK_CreateUserID between", value1, value2,
					"wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreateuseridNotBetween(Integer value1,
				Integer value2) {
			addCriterion("WFWORK_CreateUserID not between", value1, value2,
					"wfworkCreateuserid");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterIsNull() {
			addCriterion("WFWORK_CREATER is null");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterIsNotNull() {
			addCriterion("WFWORK_CREATER is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterEqualTo(String value) {
			addCriterion("WFWORK_CREATER =", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterNotEqualTo(String value) {
			addCriterion("WFWORK_CREATER <>", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterGreaterThan(String value) {
			addCriterion("WFWORK_CREATER >", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_CREATER >=", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterLessThan(String value) {
			addCriterion("WFWORK_CREATER <", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_CREATER <=", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterLike(String value) {
			addCriterion("WFWORK_CREATER like", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterNotLike(String value) {
			addCriterion("WFWORK_CREATER not like", value, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterIn(List<String> values) {
			addCriterion("WFWORK_CREATER in", values, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterNotIn(List<String> values) {
			addCriterion("WFWORK_CREATER not in", values, "wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterBetween(String value1, String value2) {
			addCriterion("WFWORK_CREATER between", value1, value2,
					"wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkCreaterNotBetween(String value1, String value2) {
			addCriterion("WFWORK_CREATER not between", value1, value2,
					"wfworkCreater");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerIsNull() {
			addCriterion("WFWORK_HANDLER is null");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerIsNotNull() {
			addCriterion("WFWORK_HANDLER is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerEqualTo(String value) {
			addCriterion("WFWORK_HANDLER =", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerNotEqualTo(String value) {
			addCriterion("WFWORK_HANDLER <>", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerGreaterThan(String value) {
			addCriterion("WFWORK_HANDLER >", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_HANDLER >=", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerLessThan(String value) {
			addCriterion("WFWORK_HANDLER <", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_HANDLER <=", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerLike(String value) {
			addCriterion("WFWORK_HANDLER like", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerNotLike(String value) {
			addCriterion("WFWORK_HANDLER not like", value, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerIn(List<String> values) {
			addCriterion("WFWORK_HANDLER in", values, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerNotIn(List<String> values) {
			addCriterion("WFWORK_HANDLER not in", values, "wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerBetween(String value1, String value2) {
			addCriterion("WFWORK_HANDLER between", value1, value2,
					"wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkHandlerNotBetween(String value1, String value2) {
			addCriterion("WFWORK_HANDLER not between", value1, value2,
					"wfworkHandler");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginIsNull() {
			addCriterion("WFWORK_PBEGIN is null");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginIsNotNull() {
			addCriterion("WFWORK_PBEGIN is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginEqualTo(Date value) {
			addCriterion("WFWORK_PBEGIN =", value, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginNotEqualTo(Date value) {
			addCriterion("WFWORK_PBEGIN <>", value, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginGreaterThan(Date value) {
			addCriterion("WFWORK_PBEGIN >", value, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginGreaterThanOrEqualTo(Date value) {
			addCriterion("WFWORK_PBEGIN >=", value, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginLessThan(Date value) {
			addCriterion("WFWORK_PBEGIN <", value, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginLessThanOrEqualTo(Date value) {
			addCriterion("WFWORK_PBEGIN <=", value, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginIn(List<Date> values) {
			addCriterion("WFWORK_PBEGIN in", values, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginNotIn(List<Date> values) {
			addCriterion("WFWORK_PBEGIN not in", values, "wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginBetween(Date value1, Date value2) {
			addCriterion("WFWORK_PBEGIN between", value1, value2,
					"wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkPbeginNotBetween(Date value1, Date value2) {
			addCriterion("WFWORK_PBEGIN not between", value1, value2,
					"wfworkPbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginIsNull() {
			addCriterion("WFWORK_ABEGIN is null");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginIsNotNull() {
			addCriterion("WFWORK_ABEGIN is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginEqualTo(Date value) {
			addCriterion("WFWORK_ABEGIN =", value, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginNotEqualTo(Date value) {
			addCriterion("WFWORK_ABEGIN <>", value, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginGreaterThan(Date value) {
			addCriterion("WFWORK_ABEGIN >", value, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginGreaterThanOrEqualTo(Date value) {
			addCriterion("WFWORK_ABEGIN >=", value, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginLessThan(Date value) {
			addCriterion("WFWORK_ABEGIN <", value, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginLessThanOrEqualTo(Date value) {
			addCriterion("WFWORK_ABEGIN <=", value, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginIn(List<Date> values) {
			addCriterion("WFWORK_ABEGIN in", values, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginNotIn(List<Date> values) {
			addCriterion("WFWORK_ABEGIN not in", values, "wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginBetween(Date value1, Date value2) {
			addCriterion("WFWORK_ABEGIN between", value1, value2,
					"wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkAbeginNotBetween(Date value1, Date value2) {
			addCriterion("WFWORK_ABEGIN not between", value1, value2,
					"wfworkAbegin");
			return (Criteria) this;
		}

		public Criteria andWfworkStateIsNull() {
			addCriterion("WFWORK_STATE is null");
			return (Criteria) this;
		}

		public Criteria andWfworkStateIsNotNull() {
			addCriterion("WFWORK_STATE is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkStateEqualTo(Integer value) {
			addCriterion("WFWORK_STATE =", value, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateNotEqualTo(Integer value) {
			addCriterion("WFWORK_STATE <>", value, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateGreaterThan(Integer value) {
			addCriterion("WFWORK_STATE >", value, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateGreaterThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_STATE >=", value, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateLessThan(Integer value) {
			addCriterion("WFWORK_STATE <", value, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateLessThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_STATE <=", value, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateIn(List<Integer> values) {
			addCriterion("WFWORK_STATE in", values, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateNotIn(List<Integer> values) {
			addCriterion("WFWORK_STATE not in", values, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateBetween(Integer value1, Integer value2) {
			addCriterion("WFWORK_STATE between", value1, value2, "wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkStateNotBetween(Integer value1, Integer value2) {
			addCriterion("WFWORK_STATE not between", value1, value2,
					"wfworkState");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlIsNull() {
			addCriterion("WFWORK_URL is null");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlIsNotNull() {
			addCriterion("WFWORK_URL is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlEqualTo(String value) {
			addCriterion("WFWORK_URL =", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlNotEqualTo(String value) {
			addCriterion("WFWORK_URL <>", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlGreaterThan(String value) {
			addCriterion("WFWORK_URL >", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlGreaterThanOrEqualTo(String value) {
			addCriterion("WFWORK_URL >=", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlLessThan(String value) {
			addCriterion("WFWORK_URL <", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlLessThanOrEqualTo(String value) {
			addCriterion("WFWORK_URL <=", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlLike(String value) {
			addCriterion("WFWORK_URL like", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlNotLike(String value) {
			addCriterion("WFWORK_URL not like", value, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlIn(List<String> values) {
			addCriterion("WFWORK_URL in", values, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlNotIn(List<String> values) {
			addCriterion("WFWORK_URL not in", values, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlBetween(String value1, String value2) {
			addCriterion("WFWORK_URL between", value1, value2, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkUrlNotBetween(String value1, String value2) {
			addCriterion("WFWORK_URL not between", value1, value2, "wfworkUrl");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidIsNull() {
			addCriterion("WFWORK_ROLEID is null");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidIsNotNull() {
			addCriterion("WFWORK_ROLEID is not null");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidEqualTo(Integer value) {
			addCriterion("WFWORK_ROLEID =", value, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidNotEqualTo(Integer value) {
			addCriterion("WFWORK_ROLEID <>", value, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidGreaterThan(Integer value) {
			addCriterion("WFWORK_ROLEID >", value, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidGreaterThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_ROLEID >=", value, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidLessThan(Integer value) {
			addCriterion("WFWORK_ROLEID <", value, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidLessThanOrEqualTo(Integer value) {
			addCriterion("WFWORK_ROLEID <=", value, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidIn(List<Integer> values) {
			addCriterion("WFWORK_ROLEID in", values, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidNotIn(List<Integer> values) {
			addCriterion("WFWORK_ROLEID not in", values, "wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidBetween(Integer value1, Integer value2) {
			addCriterion("WFWORK_ROLEID between", value1, value2,
					"wfworkRoleid");
			return (Criteria) this;
		}

		public Criteria andWfworkRoleidNotBetween(Integer value1, Integer value2) {
			addCriterion("WFWORK_ROLEID not between", value1, value2,
					"wfworkRoleid");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table dbo.WFWORK
	 * @mbggenerated  Fri Feb 27 17:26:51 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dbo.WFWORK
     *
     * @mbggenerated do_not_delete_during_merge Thu Feb 05 10:05:42 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}