package com.pinde.res.model.njmu.mo;

import com.pinde.core.model.MybatisObject;
import java.util.Date;

public class Worklog extends MybatisObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WorkLog.WorkID
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    private String workid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WorkLog.Work_UserID
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    private Integer workUserid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WorkLog.Work_Content
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    private String workContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WorkLog.Work_Type
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbo.WorkLog.Work_Time
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    private Date workTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WorkLog.WorkID
     *
     * @return the value of dbo.WorkLog.WorkID
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public String getWorkid() {
        return workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WorkLog.WorkID
     *
     * @param workid the value for dbo.WorkLog.WorkID
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public void setWorkid(String workid) {
        this.workid = workid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WorkLog.Work_UserID
     *
     * @return the value of dbo.WorkLog.Work_UserID
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public Integer getWorkUserid() {
        return workUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WorkLog.Work_UserID
     *
     * @param workUserid the value for dbo.WorkLog.Work_UserID
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public void setWorkUserid(Integer workUserid) {
        this.workUserid = workUserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WorkLog.Work_Content
     *
     * @return the value of dbo.WorkLog.Work_Content
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public String getWorkContent() {
        return workContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WorkLog.Work_Content
     *
     * @param workContent the value for dbo.WorkLog.Work_Content
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public void setWorkContent(String workContent) {
        this.workContent = workContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WorkLog.Work_Type
     *
     * @return the value of dbo.WorkLog.Work_Type
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WorkLog.Work_Type
     *
     * @param workType the value for dbo.WorkLog.Work_Type
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public void setWorkType(String workType) {
        this.workType = workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbo.WorkLog.Work_Time
     *
     * @return the value of dbo.WorkLog.Work_Time
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public Date getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbo.WorkLog.Work_Time
     *
     * @param workTime the value for dbo.WorkLog.Work_Time
     *
     * @mbggenerated Fri Feb 27 17:26:51 CST 2015
     */
    public void setWorkTime(Date workTime) {
        this.workTime = workTime;
    }
}