<%@ page language="java" contentType="application/json; charset=UTF-8" pageEncoding="UTF-8"%>
{
    "resultId": ${resultId},
    "resultType": ${pdfn:toJsonString(resultType)}
    <c:if test="${resultId eq '200' }">
,
    "info": {
        "docFlow": "${param.docFlow}",
        "cySecId": "${param.cySecId}",
        "caReqNum": "${caReqNum}",
        "caReqFinishNum": "${caReqFinishNum}",
        "caReqBiLi": "${caReqBiLi}",
        "disReqNum": "${disReqNum}",
        "disReqFinishNum": "${disReqFinishNum}",
        "disReqBiLi": "${disReqBiLi}",
        "opReqNum": "${opReqNum}",
        "opReqFinishNum": "${opReqFinishNum}",
        "opReqBiLi": "${opReqBiLi}",
        "opsReqNum": "${opsReqNum}",
        "opsReqFinishNum": "${opsReqFinishNum}",
        "opsReqBiLi": "${opsReqBiLi}",
        "activityNum": "${activityNum}",
        "dayLogCount": "${dayLogCount}",
        "cycDayCount": "${cycDayCount}",
        "id": "${scoreMap.ID}",
        "LJXY": "${scoreMap.LJXY}",
        "GZZRX": "${scoreMap.GZZRX}",
        "YLCCSG": "${scoreMap.YLCCSG}",
        "YHGTNL": "${scoreMap.YHGTNL}",
        "JBLL": "${scoreMap.JBLL}",
        "JBJN": "${scoreMap.JBJN}",
        "JBCZ": "${scoreMap.JBCZ}",
        "TGJC": "${scoreMap.TGJC}",
        "ZYLL": "${scoreMap.ZYLL}",
        "CLCJBR": "${scoreMap.CLCJBR}",
        "CLWZBR": "${scoreMap.CLWZBR}",
        "SYJC": "${scoreMap.SYJC}",
        "LCSW": "${scoreMap.LCSW}",
        "RZQQ": "${scoreMap.RZQQ}",
        "GLBZ": "${scoreMap.GLBZ}",
        "GLBL": "${scoreMap.GLBL}",
        "CZSS": "${scoreMap.CZSS}",
        "CCHD": "${scoreMap.CCHD}",
        "LLKS": "${scoreMap.LLKS}",
        "JNKS": "${scoreMap.JNKS}",
        "TotalScore": "${scoreMap.TotalScore}",
        "YDJF": "${scoreMap.YDJF}",
        "RZJF": "${scoreMap.RZJF}",
        "BZJF": "${scoreMap.BZJF}",
        "BLJF": "${scoreMap.BLJF}",
        "CZJF": "${scoreMap.CZJF}",
        "TecID": "${scoreMap.TecID}",
        "TecName": "${user.userName}",
        "TecCheckDate": "${scoreMap.TecCheckDate}",
        "SectionManagerID": "${scoreMap.SectionManagerID}",
        "headName": "${scoreMap.headName}",
        "SMCheckDate": "${scoreMap.SMCheckDate}",
        "hasEva": "${count}"
    }
    </c:if>
}
