<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"search":[
        {
            "name":"操作技能",
            "key":"name",
            "type":"text"
        }
    ],
	"catagories":[
		{
			"auditedNum":0,
			"cataFlow":"18024",
			"finishedNum":0,
			"labelsNum":3,
			"neededNum":0,
			"progress":100,
			"title":"急进性肾炎"
		},
		{
			"auditedNum":1,
			"cataFlow":"18019",
			"finishedNum":1,
			"labelsNum":3,
			"neededNum":1,
			"progress":100,
			"title":"急性肾衰竭"
		},
		{
			"auditedNum":1,
			"cataFlow":"18017",
			"finishedNum":1,
			"labelsNum":3,
			"neededNum":1,
			"progress":100,
			"title":"继发性肾小球肾炎(狼疮性肾炎、过敏性紫瘫性肾炎）"
		},
		{
			"auditedNum":3,
			"cataFlow":"18020",
			"finishedNum":3,
			"labelsNum":3,
			"neededNum":3,
			"progress":100,
			"title":"漫性肾衰竭"
		},
		{
			"auditedNum":1,
			"cataFlow":"18018",
			"finishedNum":1,
			"labelsNum":3,
			"neededNum":1,
			"progress":100,
			"title":"尿路感染"
		},
		{
			"auditedNum":0,
			"cataFlow":"21208",
			"finishedNum":0,
			"labelsNum":3,
			"neededNum":0,
			"progress":100,
			"title":"其它"
		},
		{
			"auditedNum":1,
			"cataFlow":"18022",
			"finishedNum":1,
			"labelsNum":3,
			"neededNum":1,
			"progress":100,
			"title":"肾间质小管病（急性间质性肾炎、慢性间质小管病）"
		},
		{
			"auditedNum":2,
			"cataFlow":"18023",
			"finishedNum":2,
			"labelsNum":3,
			"neededNum":2,
			"progress":100,
			"title":"糖尿病肾病"
		},
		{
			"auditedNum":10,
			"cataFlow":"18021",
			"finishedNum":10,
			"labelsNum":3,
			"neededNum":10,
			"progress":100,
			"title":"原发肾小球肾炎（急性肾炎、急进性肾炎、慢性肾炎、肾病综合征、隐匿性肾炎）"
		}
	]