<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"head":[
		{
			"headId":"time",
			"label":"时间"
		},
		{
			"headId":"content",
			"label":"实习主要内容"
		}
	],
	"datas":[
		{
			"dataFlow":"35991",
			"time":"2015-07-20",
			"content":"门诊常规心电图操作",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"35991",
			"time":"2015-07-20",
			"content":"门诊常规心电图操作",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]