<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"search":[
        {
            "name":"未审核",
            "key":"join",
            "value":"NotAudit",
            "type":"tab"
        },
        {
            "name":"已审核",
            "key":"join",
            "value":"Audited",
            "type":"tab"
        },
        {
            "name":"教师姓名",
            "key":"teacherName",
            "value":"",
            "type":"text"
        }
    ],
	"head":[
		{
			"headId":"teachDate",
			"label":"教学日期"
		},
		{
			"headId":"teacher",
			"label":"教师"
		},
		{
			"headId":"teachType",
			"label":"活动形式"
		}
	],
	"datas":[
		{
			"dataFlow":"35991",
			"teachDate":"2015-12-12",
			"teacher":"张三",
			"teachType":"讲课",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"35991",
			"teachDate":"2015-12-12",
			"teacher":"李四",
			"teachType":"讲课",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]