<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"head":[
		{
			"headId":"time",
			"label":"时间"
		},
		{
			"headId":"name",
			"label":"病名"
		},
		{
			"headId":"caseNo",
			"label":"病历号"
		}
	],
	"datas":[
		{
			"dataFlow":"161294",
			"time":"2015-02-15",
			"name":"结肠癌",
			"caseNo":"0812709",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"161292",
			"time":"2015-02-15",
			"name":"结肠癌",
			"caseNo":"0812709",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"161295",
			"time":"2015-02-15",
			"name":"结肠癌",
			"caseNo":"0812709",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]