<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"search":[
        {
           "name":"未审核",
            "key":"join",
            "value":"NotAudit",
            "type":"tab"
        },
        {
            "name":"已审核",
            "key":"join",
            "value":"Audited",
            "type":"tab"
        },
        {
            "name":"病历号",
            "key":"hospitalNumbers",
            "type":"text"
        }
    ],
	"category":{
		"auditedNum":1,
		"cataFlow":"1378",
		"finishedNum":2,
		"labelsNum":3,
		"neededNum":5,
		"progress":40,
		"title":"大病历"
	},
	"head":[
		{
			"headId":"finishTime",
			"label":"时间"
		},
		{
			"headId":"diseaseName",
			"label":"病名"
		},
		{
			"headId":"hospitalNumbers",
			"label":"病历号"
		}
	],
	"datas":[
		{
			"dataFlow":"35991",
			"finishTime":"2015-12-12",
			"diseaseName":"肛瘘",
			"hospitalNumbers":"875385",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"35992",
			"finishTime":"2015-12-12",
			"diseaseName":"肛瘘",
			"hospitalNumbers":"875385",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]