<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"head":[
		{
			"headId":"skillName",
			"label":"操作名称"
		},
		{
			"headId":"operateDate",
			"label":"时间"
		},
		{
			"headId":"status",
			"label":"操作方式"
		}
	],
	"datas":[
		{
			"dataFlow":"161294",
			"skillName":"腹腔穿刺",
			"operateDate":"2015-02-15",
			"status":"参观,二助",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"161295",
			"skillName":"腹腔穿刺",
			"operateDate":"2015-02-15",
			"status":"参观",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"161296",
			"skillName":"腹腔穿刺",
			"operateDate":"2015-02-15",
			"status":"参观",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]