<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"head":[
		{
			"headId":"time",
			"label":"时间"
		},
		{
			"headId":"caseName",
			"label":"病名"
		},
		{
			"headId":"caseNo",
			"label":"病例号"
		}
	],
	"datas":[
		{
			"dataFlow":"161294",
			"time":"2015-08-12",
			"caseName":"中风",
			"caseNo":"123123",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"161292",
			"time":"2015-08-12",
			"caseName":"中风",
			"caseNo":"123123",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"161295",
			"time":"2015-08-12 11:42:38",
			"caseName":"中风",
			"caseNo":"123123",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]