<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"add":"新增",
		"del":"删除"
	},
	"head":[
		{
			"headId":"activeDate",
			"label":"活动日期"
		},
		{
			"headId":"activeTitle",
			"label":"讲座题目"
		}
	],
	"datas":[
		{
			"dataFlow":"35991",
			"activeDate":"2015-07-20",
			"activeTitle":"肺脓肿与肺曲霉的鉴别",
			"statusDesc":"已审核",
			"statusId":"Audited"
		},
		{
			"dataFlow":"35992",
			"activeDate":"2015-07-20",
			"activeTitle":"肺脓肿与肺曲霉的鉴别",
			"statusDesc":"已审核",
			"statusId":"Audited"
		}
	]