<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"save":"保存", 
		"del":"删除"
	},
	"inputs":[
		{
			"inputId":"dept",
			"inputType":"select",
			"label":"科室",
			 "options":[{
				"optionId":"普外科",
				"optionDesc":"普外科"
			}],
			"required":true
		},
		{
			"inputId":"finishTime",
			"inputType":"date",
			"label":"时间",
			"required":true
		},
		{
			"inputId":"diseaseName",
			"inputType":"text",
			"label":"病名",
			"required":true
		}
		,
		{
			"inputId":"hospitalNumbers",
			"inputType":"text",
			"label":"病案号",
			"required":true
		}
	],
	"values":[
		{
			"inputId":"dept",
			"value":"普外科"
		},
		{
			"inputId":"finishTime",
			"value":"2015-06-29"
		},
		{
			"inputId":"diseaseName",
			"value":"肛瘘"
		},
		{
			"inputId":"hospitalNumbers",
			"value":"875385"
		}
	]