<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"save":"保存", 
		"del":"删除"
	},
	"inputs":[
		{
			"inputId":"skillName",
			"inputType":"select",
			"label":"操作名称",
			"options": [
                {
                    "optionId": "腹腔穿刺",
                    "optionDesc": "腹腔穿刺"
                }
            ],
			"required":true
		},
		{
			"inputId":"dept",
			"inputType":"select",
			"label":"科室",
			 "options":[{
				"optionId":"消化",
				"optionDesc":"消化"
			}],
			"required":true
		},
		{
			"inputId":"operateDate",
			"inputType":"date",
			"label":"时间",
			"required":true
		},
		{
			"inputId":"status",
			"inputType":"checkbox",
			"label":"操作方式",
			"options":[{
				"optionDesc":"亲自",
				"optionId":"亲自"
			},{
				"optionDesc":"一助",
				"optionId":"一助"
			},{
				"optionDesc":"二助",
				"optionId":"二助"
			},{
				"optionDesc":"参观",
				"optionId":"参观"
			}],
			"required":true
		}
	],
	"values":[
		{
			"inputId":"skillName",
			"value":"腹腔穿刺"
		},
		{
			"inputId":"dept",
			"value":"消化"
		},
		{
			"inputId":"operateDate",
			"value":"2015-10-28"
		},
		{
			"inputId":"status",
			"values": [
				"参观",
				"二助"
			]
		}
	]