<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
			"save":"保存", 
			"del":"删除"
		},
	"inputs":[
		{
			
			"inputId":"dept",
			"inputType":"select",
			"label":"科室",
			 "options":[{
				"optionId":"呼吸科",
				"optionDesc":"呼吸科"
			}],
			"required":true
		},
		{
			"inputId":"time",
			"inputType":"date",
			"label":"时间",
			"required":true
		},
		{
			"inputId":"caseName",
			"inputType":"text",
			"label":"病名",
			"required":true
		},
		{
			"inputId":"caseNo",
			"inputType":"text",
			"label":"病历号",
			"required":false
		}
	],
	"values":[
		{
			"inputId":"dept",
			"value":"呼吸科"
		},
		{
			"inputId":"time",
			"value":"2015-08-12"
		},
		{
			"inputId":"caseName",
			"value":"中风"
		},
		{
			"inputId":"caseNo",
			"value":"123123"
		}
	]