<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		"save":"保存", 
		"del":"删除"
	},
	"inputs":[
		{
			"inputId":"teachDate",
			"inputType":"date",
			"label":"教学日期",
			"placeholder":"教学日期",
			"required":true
		},
		{
			"inputId":"teacher",
			"inputType":"text",
			"label":"教师",
			"placeholder":"教师",
			"required":true
		}
		,
		{
			"inputId":"teachType",
			"inputType":"select",
			"label":"活动形式",
			"placeholder":"活动形式",
			 "options":[{
				"optionId":"讲课",
				"optionDesc":"讲课"
			},
			{
				"optionId":"示教",
				"optionDesc":"示教"
			}
			,
			{
				"optionId":"讨论",
				"optionDesc":"讨论"
			}
			,
			{
				"optionId":"教学查房",
				"optionDesc":"教学查房"
			}]
			,
			"required":true
		},
		{
			"inputId":"teachDetail",
			"inputType":"textarea",
			"label":"活动内容",
			"placeholder":"活动内容",
			"required":true
		}
	]
	,
	"values":[
		{
			"inputId":"teachDate",
			"value":"2015-12-12"
		},
		{
			"inputId":"teacher",
			"value":"张三"
		}
		,
		{
			"inputId":"teachType",
			"value":"讲课"
		}
		,
		{
			"inputId":"teachDetail",
			"value":"讲课内容"
		}
	]
