<%@ page language="java" contentType="aplication/json; charset=UTF-8" pageEncoding="UTF-8"%>
	"action":{
		<c:if test="${sSwitch && !isAudit}">
			"save":"保存", 
			"del":"删除"
		</c:if>
		<c:if test="${tSwitch && !isAudit}">
			"save":"审核"
		</c:if>
	},
	"inputs":[
		{
			"inputId":"teachDate",
			"inputType":"date",
			"label":"教学日期",
			"placeholder":"教学日期",
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		},
		{
			"inputId":"teacher",
			"inputType":"text",
			"label":"教师",
			"placeholder":"教师",
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		}
		,
		{
			"inputId":"teachType",
			"inputType":"select",
			"label":"活动形式",
			"placeholder":"活动形式",
			 "options":[{
				"optionId":"1",
				"optionDesc":"讲课"
			},
			{
				"optionId":"2",
				"optionDesc":"示教"
			}
			,
			{
				"optionId":"3",
				"optionDesc":"讨论"
			}
			,
			{
				"optionId":"4",
				"optionDesc":"教学查房"
			}]
			,
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		},
		{
			"inputId":"teachDetail",
			"inputType":"textarea",
			"label":"活动内容",
			"placeholder":"活动内容",
			"required":true
			<c:if test="${cannotOperSwitch}">
				,
				"readonly":true
			</c:if>
		}
	]
	,
	"values":[
		{
			"inputId":"teachDate",
			"value":${pdfn:toJsonString(formDataMap.teachDate)}
		},
		{
			"inputId":"teacher",
			"value":${pdfn:toJsonString(formDataMap.teacher)}
		}
		,
		{
			"inputId":"teachType",
			"value":${pdfn:toJsonString(formDataMap.teachType_id)}
		}
		,
		{
			"inputId":"teachDetail",
			"value":${pdfn:toJsonString(formDataMap.teachDetail)}
		}
	]
